### PR TITLE
OCPBUGS-23896:  Fix device uncertain errors on reboot

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGS-23896

### CODE REVIEW

**Comment by duanwei33** [comment]
The issue could be reproduced in both `4.12.0-0.nightly-2023-12-18-194028` and `4.15.0-ec.3`, and when tested with the open PR, it did not hit the issue again.
so looks good from the QE side.

**Comment by gnufied** [comment]
Unit test flake looks unrelated. 

/retest

**Comment by gnufied** [comment]
The unit test failures are clearly unrelated:

```
=== Failed
=== FAIL: pkg/registry/networking/ingress  (0.00s)
signal: segmentation fault (core dumped)
FAIL	k8s.io/kubernetes/pkg/registry/networking/ingress	2.545s

=== FAIL: vendor/k8s.io/apimachinery/pkg/util/net TestIsConnectionReset (0.03s)
    util_test.go:199: expected HTTP2ConnectionLost error, got <nil>

```

/retest

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
