### PR TITLE
Bug OCPBUGS-2991: Disable expansion in SC, if driver does not support it

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGS-2991

### CODE REVIEW

**Comment by gnufied** [comment]
This is a important fix that improves the health of vSphere CSI tests. 

/assign @deads2k @soltysh

**Comment by dcbw** [comment]
/override ci/prow/e2e-gcp-ovn-upgrade

This error is bogus and shouldn't count toward an e2e failure...

```
ns/openshift-monitoring pod/prometheus-k8s-0 node/ci-op-mvlm7tft-194fd-vjx2j-worker-b-mb8th - 1846.62 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_prometheus-k8s-0_openshift-monitoring_e067f976-a795-46a5-8d0c-aaa98e270638_0(872a1008a0a0728e2054184877da3ded158dbda13a776aef5ae4d46356017341): error adding pod openshift-monitoring_prometheus-k8s-0 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): Multus: [openshift-monitoring/prometheus-k8s-0/e067f976-a795-46a5-8d0c-aaa98e270638]: error setting the networks status, pod was already deleted: SetNetworkStatus: failed to query the pod prometheus-k8s-0 in out of cluster comm: rpc error: code = Unknown desc = malformed header: missing HTTP content-type}
```

/override ci/prow/e2e-aws-ovn-crun

This seems like the coredump pod only gets 30s to live and couldn't gather cores that quickly... in any case unrelated.
`{  "e2e-aws-ovn-crun" pod "e2e-aws-ovn-crun-gather-core-dump" failed: the pod ci-op-mvlm7tft/e2e-aws-ovn-crun-gather-core-dump was deleted without completing after 30s (failed containers: )`

**Comment by dobsonj** [comment]
EC2 InsufficientInstanceCapacity
/retest-required

**Comment by vrutkovs** [comment]
`Error: error reading Route Table (rtb-06764f194f08e3b30): couldn't find resource`
/test e2e-aws-serial

**Pull request merged**
