### PR TITLE
Base kubernetes branch for 1.19-rc.1 (oc-only)

### PR DESCRIPTION
**Pull request by damemi**
[1.19 pick list](https://docs.google.com/spreadsheets/d/1R_NK2gmx9BTIM92qewjgET-m8jQ9NCgSZedUiNSDQYY/edit#gid=0)

Previous base https://github.com/openshift/kubernetes/pull/123

Following https://github.com/openshift/enhancements/blob/master/enhancements/oc/upgrade_kubernetes.md

### CODE REVIEW

**Comment by damemi** [comment]
/hold
on getting CI for this branch https://github.com/openshift/release/pull/10265

**Comment by droslean** [comment]
Presubmit added manually

**Comment by soltysh** [comment]
@damemi from what I see here's what the situation looks like these failures are quite repeating and we can safely ignore these packages:

- k8s.io/kubernetes/pkg/registry/
- k8s.io/apiextensions-apiserver/pkg/registry/
- k8s.io/apiserver/pkg/apis/config/validation/
- k8s.io/apiserver/pkg/registry/
- k8s.io/apiserver/pkg/storage/

This failure is real:
- k8s.io/kubectl/pkg/cmd/config

**Comment by damemi** [comment]
@soltysh I think something is off with your fix, see https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/169/pull-ci-openshift-kubernetes-oc-4.6-kubernetes-1.19-rc.1-unit/1285253603426045952#1:build-log.txt%3A3852

```
 === FAIL: vendor/k8s.io/kubectl/pkg/cmd/config TestSetCurrentContext (0.20s)
error: mkdir /.kube: permission denied
FAIL	k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config	0.205s 
```

**Comment by damemi** [comment]
@soltysh this is green now, want to merge?

**Comment by soltysh** [comment]
> @soltysh this is green now, want to merge?

yeah, let's proceed, we'll fix it during another bump, later on.

**Pull request merged**
