### PR TITLE
STOR-1263: Update to Kubernetes 1.27.1

### PR DESCRIPTION
**Pull request by bertinatto**

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/hold to not accidentally merge this :sweat_smile:

**Comment by bertinatto** [comment]
/payload 4.14 nightly informing
Many jobs encountered errors to start, restarting.

**Comment by bertinatto** [comment]
/payload periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-aws-sdn-upgrade
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-upgrade-ovn-ipv6
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-upi
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-alibaba-ovn
/payload periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-sdn-upgrade
/payload periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade
/payload periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview
/payload periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-serial

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-aws-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-upi
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-alibaba-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-aws-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-serial

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g: 64bbe949-e5ec-11ed-bc97-0a580a8109c1
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-alibaba-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g: 64bbe949-e5ec-11ed-bc97-0a580a8109c1
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g: 64bbe949-e5ec-11ed-bc97-0a580a8109c1
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g: 64bbe949-e5ec-11ed-bc97-0a580a8109c1
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g: 64bbe949-e5ec-11ed-bc97-0a580a8109c1
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-upgrade-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-deploy-cnv
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade

**Comment by deads2k** [comment]
diff of diff looks ok

/lgtm
/approve
/hold cancel

**Comment by bertinatto** [comment]
Seems like transient failures:

```
STEP 3/5: RUN ["/bin/bash","-c","set -o errexit; umask 0002; openshift-hack/build-go.sh"]
Error: received unexpected terminate signal, the build bin failed after 0s with reason BuildPodDeleted: The pod for this build was deleted before the build completed., the build bin failed after 7m25s with reason BuildPodDeleted: The pod for this build was deleted before the build completed.
```

Retesting to make sure:

/retest-required

**Comment by deads2k** [comment]
TRT confirmed prior state

diff of diffs clean.  install clean.   payload passed. merging

**Pull request merged**
