### PR TITLE
Bug 1951815: UPSTREAM: 99393: kubelet: reduce configmap and secret watch

### PR DESCRIPTION
**Pull request by ehashman**
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1951815

/cc @rphillips @mrunalp

### CODE REVIEW

**Comment by ehashman** [comment]
Unit test flake is unrelated, looks like https://github.com/kubernetes/kubernetes/issues/96908

/retest

**Comment by knobunc** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

We keep flaking on infrastructure problems (image pull failures, etc.) and have previously passed that job with this PR.

**Pull request merged**
