### PR TITLE
UPSTREAM: 114994: kubelet: fix readiness probes with pod termination

### PR DESCRIPTION
**Pull request by rphillips**
Fixes readiness status propagation on pod termination.

### CODE REVIEW

**Comment by rphillips** [comment]
Seeing if I fixed the tests...

still watching... https://pr-payload-tests.ci.openshift.org/runs/ci/150524c0-9077-11ed-8423-a21d829dcb7d-0

**Comment by rphillips** [comment]
Still working on the upstream comments.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Pull request merged**
