### PR TITLE
OCPBUGS-39014: Bump 1.30.4

### PR DESCRIPTION
**Pull request by dinhxuanvu**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
Looke like we need to carry this patch: https://github.com/kubernetes/kubernetes/pull/126920

**Comment by dinhxuanvu** [comment]
@bertinatto @tkashem PTAL

**Comment by bertinatto** [comment]
For context, the 4.18 Kubernetes update work in ongoing. This means we don't have a valid 4.18 bug to link to, so as a result, we're setting the tags manually. 

/remove-label jira/invalid-bug
/label jira/valid-bug

**Pull request merged**
