### PR TITLE
UPSTREAM: 94693: test/e2e: Busybox image is not being templatized

### PR DESCRIPTION
**Pull request by smarterclayton**
All images used by e2e tests must use templates in order to allow
relocation. In addition this is hitting Dockerhub which will be
getting throttled soon.

Required for offline test

### CODE REVIEW

**Comment by smarterclayton** [comment]
@sttts @soltysh backported from 1.20 so we can land the offline images PR (this is the last place in kube e2e that accessed a non-mirrored image)

**Comment by soltysh** [comment]
@smarterclayton fix the commit message and you're good, it still need to be `UPSTREAM: 94693: ...` prefixed.

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by smarterclayton** [comment]
Fixed the verify job (my bad)

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by sttts** [comment]
Is fips in such a bad state or is this a real issue?

**Pull request merged**
