### PR TITLE
STOR-1425: Update to Kubernetes 1.28.1

### PR DESCRIPTION
**Pull request by bertinatto**

### CODE REVIEW

**Comment by dgoodwin** [comment]
IIRC there's a significant build step required for payload testing in this repo, and results like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade/1684997352038862848 and https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade/1684997361266331648 look like we need to bump the timeouts we normally do for each rebase. Maciej probably knows best where these all are and we can unrevert the last time they were removed.

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1646-nightly-4.14-e2e-metal-ipi-ovn-ipv6/1684997373052325888 looks like a pretty legit failure?

```


sig-network]  Netpol API should support creating NetworkPolicy with Status  subresource [Feature:NetworkPolicyStatus]  [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less
--
Run #0: Failed expand_less                           1s                                                                                                          {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/network/netpol/network_policy_api.go:327]: request template:&NetworkPolicy{ObjectMeta:{e2e-example-netpol-status-validate87n82 e2e-example-netpol-status-validate e2e-netpol-5739  4e1e6645-05a4-49e6-ae0a-7c6837178b5f 114403 1 2023-07-28 21:04:13 +0000 UTC <nil> <nil> map[special-label:e2e-netpol-5739] map[] [] [] [{openshift-tests Update networking.k8s.io/v1 2023-07-28 21:04:13 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:special-label":{}}},"f:spec":{"f:ingress":{},"f:podSelector":{},"f:policyTypes":{}}} }]},Spec:NetworkPolicySpec{PodSelector:{map[pod-name:test-pod] []},Ingress:[]NetworkPolicyIngressRule{NetworkPolicyIngressRule{Ports:[]NetworkPolicyPort{},From:[]NetworkPolicyPeer{NetworkPolicyPeer{PodSelector:&v1.LabelSelector{MatchLabels:map[string]string{pod-name: client-a,},MatchExpressions:[]LabelSelectorRequirement{},},NamespaceSelector:&v1.LabelSelector{MatchLabels:map[string]string{ns-name: pod-b,},MatchExpressions:[]LabelSelectorRequirement{},},IPBlock:nil,},},},},Egress:[]NetworkPolicyEgressRule{},PolicyTypes:[Ingress],},Status:NetworkPolicyStatus{Conditions:[]Condition{{Accepted True 2 2023-07-28 20:59:13.974519384 +0000 UTC m=-298.965417534 RuleApplied rule was successfully applied},},},}: the server could not find the requested resource Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less                           1s                                                                                                          {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/network/netpol/network_policy_api.go:327]: request template:&NetworkPolicy{ObjectMeta:{e2e-example-netpol-status-validate87n82 e2e-example-netpol-status-validate e2e-netpol-5739  4e1e6645-05a4-49e6-ae0a-7c6837178b5f 114403 1 2023-07-28 21:04:13 +0000 UTC <nil> <nil> map[special-label:e2e-netpol-5739] map[] [] [] [{openshift-tests Update networking.k8s.io/v1 2023-07-28 21:04:13 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:special-label":{}}},"f:spec":{"f:ingress":{},"f:podSelector":{},"f:policyTypes":{}}} }]},Spec:NetworkPolicySpec{PodSelector:{map[pod-name:test-pod] []},Ingress:[]NetworkPolicyIngressRule{NetworkPolicyIngressRule{Ports:[]NetworkPolicyPort{},From:[]NetworkPolicyPeer{NetworkPolicyPeer{PodSelector:&v1.LabelSelector{MatchLabels:map[string]string{pod-name: client-a,},MatchExpressions:[]LabelSelectorRequirement{},},NamespaceSelector:&v1.LabelSelector{MatchLabels:map[string]string{ns-name: pod-b,},MatchExpressions:[]LabelSelectorRequirement{},},IPBlock:nil,},},},},Egress:[]NetworkPolicyEgressRule{},PolicyTypes:[Ingress],},Status:NetworkPolicyStatus{Conditions:[]Condition{{Accepted True 2 2023-07-28 20:59:13.974519384 +0000 UTC m=-298.965417534 RuleApplied rule was successfully applied},},},}: the server could not find the requested resource Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less | 1s | {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/network/netpol/network_policy_api.go:327]: request template:&NetworkPolicy{ObjectMeta:{e2e-example-netpol-status-validate87n82 e2e-example-netpol-status-validate e2e-netpol-5739  4e1e6645-05a4-49e6-ae0a-7c6837178b5f 114403 1 2023-07-28 21:04:13 +0000 UTC <nil> <nil> map[special-label:e2e-netpol-5739] map[] [] [] [{openshift-tests Update networking.k8s.io/v1 2023-07-28 21:04:13 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:special-label":{}}},"f:spec":{"f:ingress":{},"f:podSelector":{},"f:policyTypes":{}}} }]},Spec:NetworkPolicySpec{PodSelector:{map[pod-name:test-pod] []},Ingress:[]NetworkPolicyIngressRule{NetworkPolicyIngressRule{Ports:[]NetworkPolicyPort{},From:[]NetworkPolicyPeer{NetworkPolicyPeer{PodSelector:&v1.LabelSelector{MatchLabels:map[string]string{pod-name: client-a,},MatchExpressions:[]LabelSelectorRequirement{},},NamespaceSelector:&v1.LabelSelector{MatchLabels:map[string]string{ns-name: pod-b,},MatchExpressions:[]LabelSelectorRequirement{},},IPBlock:nil,},},},},Egress:[]NetworkPolicyEgressRule{},PolicyTypes:[Ingress],},Status:NetworkPolicyStatus{Conditions:[]Condition{{Accepted True 2 2023-07-28 20:59:13.974519384 +0000 UTC m=-298.965417534 RuleApplied rule was successfully applied},},},}: the server could not find the requested resource Ginkgo exit error 1: exit with code 1}
Run #0: Failed expand_less                           1s                                                                                                          {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/network/netpol/network_policy_api.go:327]: request template:&NetworkPolicy{ObjectMeta:{e2e-example-netpol-status-validate87n82 e2e-example-netpol-status-validate e2e-netpol-5739  4e1e6645-05a4-49e6-ae0a-7c6837178b5f 114403 1 2023-07-28 21:04:13 +0000 UTC <nil> <nil> map[special-label:e2e-netpol-5739] map[] [] [] [{openshift-tests Update networking.k8s.io/v1 2023-07-28 21:04:13 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:special-label":{}}},"f:spec":{"f:ingress":{},"f:podSelector":{},"f:policyTypes":{}}} }]},Spec:NetworkPolicySpec{PodSelector:{map[pod-name:test-pod] []},Ingress:[]NetworkPolicyIngressRule{NetworkPolicyIngressRule{Ports:[]NetworkPolicyPort{},From:[]NetworkPolicyPeer{NetworkPolicyPeer{PodSelector:&v1.LabelSelector{MatchLabels:map[string]string{pod-name: client-a,},MatchExpressions:[]LabelSelectorRequirement{},},NamespaceSelector:&v1.LabelSelector{MatchLabels:map[string]string{ns-name: pod-b,},MatchExpressions:[]LabelSelectorRequirement{},},IPBlock:nil,},},},},Egress:[]NetworkPolicyEgressRule{},PolicyTypes:[Ingress],},Status:NetworkPolicyStatus{Conditions:[]Condition{{Accepted True 2 2023-07-28 20:59:13.974519384 +0000 UTC m=-298.965417534 RuleApplied rule was successfully applied},},},}: the server could not find the requested resource Ginkgo exit error 1: exit with code 1} | Run #0: Failed expand_less | 1s | {  fail [k8s.io/kubernetes@v1.27.1/test/e2e/network/netpol/network_policy_api.go:327]: request template:&NetworkPolicy{ObjectMeta:{e2e-example-netpol-status-validate87n82 e2e-example-netpol-status-validate e2e-netpol-5739  4e1e6645-05a4-49e6-ae0a-7c6837178b5f 114403 1 2023-07-28 21:04:13 +0000 UTC <nil> <nil> map[special-label:e2e-netpol-5739] map[] [] [] [{openshift-tests Update networking.k8s.io/v1 2023-07-28 21:04:13 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:special-label":{}}},"f:spec":{"f:ingress":{},"f:podSelector":{},"f:policyTypes":{}}} }]},Spec:NetworkPolicySpec{PodSelector:{map[pod-name:test-pod] []},Ingress:[]NetworkPolicyIngressRule{NetworkPolicyIngressRule{Ports:[]NetworkPolicyPort{},From:[]NetworkPolicyPeer{NetworkPolicyPeer{PodSelector:&v1.LabelSelector{MatchLabels:map[string]string{pod-name: client-a,},MatchExpressions:[]LabelSelectorRequirement{},},NamespaceSelector:&v1.LabelSelector{MatchLabels:map[string]string{ns-name: pod-b,},MatchExpressions:[]LabelSelectorRequirement{},},IPBlock:nil,},},},},Egress:[]NetworkPolicyEgressRule{},PolicyTypes:[Ingress],},Status:NetworkPolicyStatus{Conditions:[]Condition{{Accepted True 2 2023-07-28 20:59:13.974519384 +0000 UTC m=-298.965417534 RuleApplied rule was successfully applied},},},}: the server could not find the requested resource Ginkgo exit error 1: exit with code 1}
Run #0: Failed expand_less | 1s
{  fail [k8s.io/kubernetes@v1.27.1/test/e2e/network/netpol/network_policy_api.go:327]: request template:&NetworkPolicy{ObjectMeta:{e2e-example-netpol-status-validate87n82 e2e-example-netpol-status-validate e2e-netpol-5739  4e1e6645-05a4-49e6-ae0a-7c6837178b5f 114403 1 2023-07-28 21:04:13 +0000 UTC <nil> <nil> map[special-label:e2e-netpol-5739] map[] [] [] [{openshift-tests Update networking.k8s.io/v1 2023-07-28 21:04:13 +0000 UTC FieldsV1 {"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:special-label":{}}},"f:spec":{"f:ingress":{},"f:podSelector":{},"f:policyTypes":{}}} }]},Spec:NetworkPolicySpec{PodSelector:{map[pod-name:test-pod] []},Ingress:[]NetworkPolicyIngressRule{NetworkPolicyIngressRule{Ports:[]NetworkPolicyPort{},From:[]NetworkPolicyPeer{NetworkPolicyPeer{PodSelector:&v1.LabelSelector{MatchLabels:map[string]string{pod-name: client-a,},MatchExpressions:[]LabelSelectorRequirement{},},NamespaceSelector:&v1.LabelSelector{MatchLabels:map[string]string{ns-name: pod-b,},MatchExpressions:[]LabelSelectorRequirement{},},IPBlock:nil,},},},},Egress:[]NetworkPolicyEgressRule{},PolicyTypes:[Ingress],},Status:NetworkPolicyStatus{Conditions:[]Condition{{Accepted True 2 2023-07-28 20:59:13.974519384 +0000 UTC m=-298.965417534 RuleApplied rule was successfully applied},},},}: the server could not find the requested resource Ginkgo exit error 1: exit with code 1}
```

And then another timeout: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1646-nightly-4.14-e2e-metal-ipi-sdn-bm/1684997373891186688

On the CI payload, 



[sig-instrumentation]  Prometheus [apigroup:image.openshift.io] when installed on the cluster  should report telemetry [Late] [Skipped:Disconnected]  [Suite:openshift/conformance/parallel] expand_less | 0s
-- | --
{Failed: Passed 7 times, failed 3 times.  The historical pass rate is 100%.  The required number of passes is 9.  name: '[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed   on the cluster should report telemetry [Late] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]' testsuitename: openshift-tests summary: 'Failed: Passed 7 times, failed 3 times.  The historical pass rate is 100%.  The   required number of passes is 9.' passes:


I think [this test was struggling last week and has since resolved](https://sippy.dptools.openshift.org/sippy-ng/tests/4.14/analysis?test=%5Bsig-instrumentation%5D%20Prometheus%20%5Bapigroup%3Aimage.openshift.io%5D%20when%20installed%20on%20the%20cluster%20should%20report%20telemetry%20%5BLate%5D%20%5BSkipped%3ADisconnected%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22%5Bsig-instrumentation%5D%20Prometheus%20%5Bapigroup%3Aimage.openshift.io%5D%20when%20installed%20on%20the%20cluster%20should%20report%20telemetry%20%5BLate%5D%20%5BSkipped%3ADisconnected%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22not%22%3Atrue%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22never-stable%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22not%22%3Atrue%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22aggregated%22%7D%5D%2C%22linkOperator%22%3A%22and%22%7D), it was a server side problem IIRC.  I wouldn't worry about this one unless it resurfaces.

**Comment by bertinatto** [comment]
Thank you for looking into these results, @dgoodwin!

> https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1646-nightly-4.14-e2e-metal-ipi-ovn-ipv6/1684997373052325888 looks like a pretty legit failure?
> 
> ```
> sig-network]  Netpol API should support creating NetworkPolicy with Status  subresource [Feature:NetworkPolicyStatus]  [Suite:openshift/conformance/parallel] [Suite:k8s] expand_less

We will need to skip this test in o/o because this feature was removed in Kubernetes 1.28: 

* https://github.com/kubernetes/kubernetes/pull/115843
* https://github.com/kubernetes/kubernetes/blob/34a3f2f850021f14d272f2c65e972f7faf310894/CHANGELOG/CHANGELOG-1.28.md?plain=1#L944.

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade
/payload-job periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn-conformance

**Comment by bertinatto** [comment]
Re-running a few nightly informing jobs:

/payload-job openshift-kubernetes-1646-nightly-4.14-e2e-aws-ovn-single-node-serial
/payload-job openshift-kubernetes-1646-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-sdn-upgrade
/payload-job openshift-kubernetes-1646-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job openshift-kubernetes-1646-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview

**Comment by bertinatto** [comment]
/payload 4.14 nightly blocking
/payload 4.14 ci blocking
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview

**Comment by dgoodwin** [comment]
@bertinatto I went through the results, indeed they're all over the place. I don't see anything in there that screams regression, I don't think there's any action to take just yet, but I'd be curious to see another attempt late this week maybe?

**Comment by bertinatto** [comment]
> @bertinatto I went through the results, indeed they're all over the place. I don't see anything in there that screams regression, I don't think there's any action to take just yet, but I'd be curious to see another attempt late this week maybe?

@dgoodwin thank you so much! I'll try again later this week and let you know.

**Comment by bertinatto** [comment]
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade
/payload periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-virtualmedia-bond

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-virtualmedia-bond
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-virtualmedia-bond
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-serial-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-assisted

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade	
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-virtualmedia-bond	
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-virtualmedia-bond
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-virtualmedia-bond
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-driver-toolkit
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-sdn-serial-virtualmedia-bond
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview

**Comment by bertinatto** [comment]
"/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-single-node-serial

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm

**Comment by bertinatto** [comment]
Scheduling jobs that are still red in the test matrix (except the two other metal jobs from my previous comment):

/payload-job periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-serial-virtualmedia-bond
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ovn-single-node-live-iso
/payload-job periodic-ci-openshift-release-master-nightly-4.15-upgrade-from-stable-4.14-e2e-metal-ipi-sdn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-upgrade-from-stable-4.14-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-azure-sdn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-techpreview

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Comment by soltysh** [comment]
/override ci/prow/verify-commits 
this never passes on k8s bump

/label acknowledge-critical-fixes-only

**Comment by bertinatto** [comment]
```
error occurred handling build pod: build not successful after 5 attempts: [the build pod failed after 3m42s with reason PullBuilderImageFailed: Failed pulling builder image., the build pod failed after 3m36s with reason PullBuilderImageFailed: Failed pulling builder image., the build pod failed after 2m59s with reason PullBuilderImageFailed: Failed pulling builder image., the build pod failed after 3m9s with reason PullBuilderImageFailed: Failed pulling builder image., the build pod failed after 3m48s with reason PullBuilderImageFailed: Failed pulling builder image.]}
```

/test e2e-aws-ovn-fips

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-fips

**Comment by bertinatto** [comment]
/hold
There seems to be a regression in FIPS. Holding to discuss with the team.

**Comment by bertinatto** [comment]
```
t.org/ci/entrypoint-wrapper: received unexpected HTTP status: 504 Gateway Time-out
* 2023-09-14T12:24:58Z 3x kubelet: Error: ErrImagePull
* 2023-09-14T12:46:12Z 72x kubelet: Back-off pulling image "registry.ci.openshift.org/ci/entrypoint-wrapper:latest" 
```

/test e2e-gcp

**Comment by bertinatto** [comment]
``` * 2023-09-14T12:26:47Z 3x kubelet: Error: ErrImagePull
* 2023-09-14T12:48:07Z 72x kubelet: Back-off pulling image "registry.ci.openshift.org/ci/entrypoint-wrapper:latest"
* 2023-09-14T12:27:11Z 4x kubelet: Error: ImagePullBackOff
```
/test k8s-e2e-gcp-ovn

**Pull request merged**
