### PR TITLE
UPSTREAM: <carry>: prevent the kubecontrollermanager service-ca from getting less secure

### PR DESCRIPTION
**Pull request by deads2k**
part 5 of the four step plan in https://github.com/openshift/service-ca-operator/pull/167

### CODE REVIEW

**Comment by marun** [comment]
> part 5 of the four step plan 

😆

The intent LGTM.

**Comment by deads2k** [comment]
> /lgtm
> /retest
> 
> /hold
> 
> for @soltysh to have a look on first commit.

rebased, so the first commit has already merged.

/hold cancel

re-applying lgtm

**Review by soltysh — APPROVED** [review]

**Comment by mfojtik** [comment]
/override ci/prow/e2e-gcp-upgrade
/override ci/prow/e2e-agnostic-cmd

These failures are unrelated to this change and need to be investigated.

**Pull request merged**
