### PR TITLE
BUG 1863009: vSphere provision failure on ocp46

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Upstream cherry-pick: https://github.com/kubernetes/kubernetes/pull/93971

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
@gnufied @dav1x May I get an approval, to update origin repo with the vendor update? Whom I could also ping, in case you need additional eyes on that?

**Comment by dav1x** [comment]
@jcpowermac I think the bz pointed to the cloud team?

**Pull request merged**
