### PR TITLE
Bug 1981770: UPSTREAM: <drop>: bump(apiserver-library-go)

### PR DESCRIPTION
**Pull request by atiratree**
#### What this PR does / why we need it:

contains fix https://github.com/openshift/apiserver-library-go/pull/54 for a backport https://bugzilla.redhat.com/show_bug.cgi?id=1981770

#### Which issue(s) this PR fixes:

Fixes #
- https://bugzilla.redhat.com/show_bug.cgi?id=1981770

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by atiratree** [comment]
@mfojtik can you please approve?

**Pull request merged**
