### PR TITLE
Bug 1977924: [release-4.8] Ensure scc compatibility with BoundServiceAccountTokenVolume

### PR DESCRIPTION
**Pull request by stlaz**
Previous to the BoundServiceAccountTokenVolume feature being enabled, the automatic mounting of legacy token secrets required that an scc permit secret volume sources either implicitly (by allowing all volume sources) or explicitly (by specifying 'secret' in the set of allowed volumes).

To ensure compatibility with this permission scheme for the projected token volumes enabled by BoundServiceAccountTokenVolume, this commit ensures that the projected volumes of service account tokens will be permitted under the same criteria (i.e. secret volume sources are allowed by an scc).

/cc @sttts @s-urbaniak @marun

### CODE REVIEW

**Comment by sttts** [comment]
/retest

unrelated

**Comment by marun** [comment]
/retitle Bug 1977924: [release-4.8] Ensure scc compatibility with BoundServiceAccountTokenVolume

**Comment by marun** [comment]
Test failure in e2e-gcp can be overridden. Test should be skipped (addressed by https://github.com/openshift/origin/pull/26267).

Disruptive failure can also be overridden, should be optional (addressed by https://github.com/openshift/release/pull/19909).

**Pull request merged**
