### PR TITLE
UPSTREAM: <carry>: OCPBUGS-25875: [4.10] vendor cadvisor to request the pid of another cont…

### PR DESCRIPTION
**Pull request by haircommander**
…ainer if current pid is not longer valid

#### What type of PR is this?

/kind bug
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
fix a bug where network metrics disappear after a container restarts
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by harche — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request closed without merging**
