### PR TITLE
OCPBUGS-27368: Update to kubernetes 1.28.6

### PR DESCRIPTION
**Pull request by soltysh**
/assign @suleymanakbas91 @jerpeter1

### CODE REVIEW

**Comment by soltysh** [comment]
/remove-label backports/unvalidated-commits
/label backports/validated-commits

Manually overriding valid-bug, since 1.29.1 is in https://github.com/openshift/kubernetes/pull/1858 and it's not being tracked in jira as a bug, yet. 
/remove-label jira/invalid-bug 
/label jira/valid-bug 

/label backport-risk-assessed

**Review by sairameshv — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
