### PR TITLE
NO-JIRA: Revert "OCPBUGS-24404: add ignore for SAST scan"

### PR DESCRIPTION
**Pull request by rphillips**
Reverts openshift/kubernetes#1824

### CODE REVIEW

**Comment by kannon92** [comment]
/lgtm

synk -> snyk is correct via documentation

/assign @soltysh

**Comment by kannon92** [comment]
@soltysh could we get this one merged also? Just removes the misnamed file.

**Comment by kannon92** [comment]
From slack, @rphillips needs to modify the commit message.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Pull request merged**
