### PR TITLE
Bug 1964545: add sysctl defaults for kubelet

### PR DESCRIPTION
**Pull request by rphillips**
Add sysctl defaults

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Review by jmencak — CHANGES_REQUESTED** [review]
Thank you for the PR, Ryan. On the whole this looks sane to me.  However, I wonder if we can rename the file `10-default-openshift-sysctls.conf` to something like `10-default-kubelet-sysctls.conf` as default OpenShift  tuning is delivered by the NTO and we do not want to convey the impression default OpenShift tuning should be set here.  I believe the sysctls set here are really only not to make the *kubelet* crash when the `protectKernelDefaults` kubelet parameter is set (and NTO not yet started), therefore this has nothing to do with OpenShift.

**Comment by jmencak** [comment]
It would also be nice to mention why the sysctl config file is there in the comments inside the sysctl config file itself.

**Comment by jmencak** [comment]
Thank you for the PR and changes, Ryan
/lgtm

**Comment by mrunalp** [comment]
Can we use the MCO to lay down this file?

**Comment by rphillips** [comment]
@mrunalp I don't think so... There would be a circular dependency on MCO.

**Comment by rphillips** [comment]
moving over here: https://github.com/openshift/machine-config-operator/pull/2590

**Pull request closed without merging**
