### PR TITLE
[4.7] Bug 2022720: UPSTREAM: 106261: Don't guess SELinux support on error

### PR DESCRIPTION
**Pull request by jsafrane**
When GetSELinuxSupport() fails, don't assume a mounted filesystem does not support SELinux at all. Try again instead in the next SetUp retry.

cc @openshift/storage

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve

**Comment by jsafrane** [comment]
Added https://github.com/kubernetes/kubernetes/pull/106554, which is not merged upstream yet
/hold

**Review by Phaow — COMMENTED** [review]
/lgtm
/label qe-approved

**Comment by jsafrane** [comment]
/hold cancel
Upstream PR kubernetes#106554 was merged.

**Pull request merged**
