### PR TITLE
Bug 2099800: bump to k8s 1.24.6

### PR DESCRIPTION
**Pull request by soltysh**
Supersedes https://github.com/openshift/kubernetes/pull/1352

### CODE REVIEW

**Comment by vrutkovs** [comment]
`verify` says revendoring is required:
```
 hack/update-vendor.sh
Your vendored results are different: 
....
```

**Comment by soltysh** [comment]
/override ci/prow-verify-commits
this will never pass on a k8s bump bringing in upstream commits not following our commit naming rules

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
this will never pass on a k8s bump bringing in upstream commits not following our commit naming rules

**Comment by soltysh** [comment]
/remove-label backports/unvalidated-commits
/label backports/validated-commits
/label bugzilla/valid-bug
we don't have parent bug for this one, so it's complaining about this issue and I need to manually force it

**Comment by tkashem** [comment]
/lgtm
Thanks!

**Pull request merged**
