### PR TITLE
Bug 1951727: Speed up PV provisioning for vsphere driver (ocp-4.6)

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1951727

### CODE REVIEW

**Comment by gnufied** [comment]
The unit test failure looks unrelated:

```

=== Failed
=== FAIL: vendor/k8s.io/kube-aggregator/pkg/apiserver TestProxyCertReload (0.11s)
2021-05-25 14:21:32.882371 I | http: TLS handshake error from 127.0.0.1:39412: tls: failed to verify client certificate: x509: certificate signed by unknown authority
2021-05-25 14:21:32.948930 I | http: TLS handshake error from 127.0.0.1:39416: tls: failed to verify client certificate: x509: certificate has expired or is not yet valid: current time 2021-05-25T14:21:32Z is after 2021-05-22T08:10:51Z
    handler_proxy_test.go:671: Expected status code 200 but got 503


```

**Comment by deads2k** [comment]
have these been backported to kube 1.19?

**Comment by gnufied** [comment]
@deads2k no they have not been backported. Similarly the fix was not backported to 1.20. I can try backporting these.

**Comment by gnufied** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/102351 for 1.19 backport

**Comment by ehashman** [comment]
@gnufied can we backport the cert fix separately? I will open the cherry-picks, ran into the same issue on a diff 4.6 backport.

**Comment by gnufied** [comment]
@ehashman removed btw. 

/retest

**Comment by duanwei33** [comment]
/lgtm  
/label qe-approved
Using the pre-merged PR to verify and passed.

**Comment by duanwei33** [comment]
I'm following JIRA issue DPTP-660 to do the pre-merge verification. Used the cluster-bot launching an env with the still open but Dev-approved PR(s).
The bug is pre-merge verified in [1951727#c2](https://bugzilla.redhat.com/show_bug.cgi?id=1951727#c2).

**Pull request merged**
