### PR TITLE
OCPBUGS-2474: UPSTREAM: 116995: kubelet: Ensure pods that have not started track pendingUpdate

### PR DESCRIPTION
**Pull request by bertinatto**
/assign @rphillips

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by rphillips** [comment]
/retitle OCPBUGS-2474: UPSTREAM: 116995: kubelet: Ensure pods that have not started track pendingUpdate

**Comment by Gleway** [comment]
Auto-merging pkg/kubelet/kubelet_pods_test.go
CONFLICT (content): Merge conflict in pkg/kubelet/kubelet_pods_test.go

///merge failed?

**Pull request merged**
