### PR TITLE
"Bug 1913069: hold SCC for ten seconds to retry getting providers"

### PR DESCRIPTION
**Pull request by deads2k**
Events from https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-azure-4.6/1312182792934658048 show a race for about 6 seconds 

```
  count: 11
  eventTime: null
  firstTimestamp: "2020-10-03T00:34:32Z"
  involvedObject:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: marketplace-operator-55bd6f6588
    namespace: openshift-marketplace
    resourceVersion: "1355"
    uid: e210d08f-a8f2-437f-b618-0b7555f04cd4
  kind: Event
  lastTimestamp: "2020-10-03T00:34:38Z"
  message: 'Error creating: pods "marketplace-operator-55bd6f6588-" is forbidden: no SecurityContextConstraintsProvider available to validate pod request'
  metadata:
    creationTimestamp: "2020-10-03T00:34:33Z"
```

I suspect there is another issue after this that is taking longer to resolve, but may as well pick up the easy bits.

### CODE REVIEW

**Comment by stlaz** [comment]
/retest
UPSTREAM seems to be required in the commit summary by the verify/verify-commits tests

Won't this fix just hide the issue?

**Comment by deads2k** [comment]
> /retest
> UPSTREAM seems to be required in the commit summary by the verify/verify-commits tests
> 
> Won't this fix just hide the issue?

On a fast namespace create, rolebinding create, and pod create there is a race between this admission plugin, the pod creator and the clusterpolicy controller.  Allowing some slack for observing the current state can help reduce the pod create churn.

**Comment by stlaz** [comment]
/lgtm
Makes sense, it might take time for the policy controller to annotate the NS according to expectations of the SCC admission.

**Comment by deads2k** [comment]
/hold

gottta fix the verify

**Comment by stlaz** [comment]
/retitle "Bug 1913069: hold SCC for ten seconds to retry getting providers"

**Comment by jluhrsen** [comment]
I see there are some checks failing. I know the e2e-aws-fips failure should be resolved now after https://bugzilla.redhat.com/show_bug.cgi?id=1891068 was fixed recently. I didn't know too much off hand about
the other failures.

**Comment by deads2k** [comment]
https://github.com/openshift/kubernetes/pull/573 showed that https://github.com/openshift/cluster-kube-apiserver-operator/pull/1049 could be a better canddiate

**Pull request closed without merging**
