### PR TITLE
OCPBUGS-16166: Update to Kubernetes 1.27.4

### PR DESCRIPTION
**Pull request by soltysh**
Brings back https://github.com/openshift/kubernetes/pull/1645 which was reverted in https://github.com/openshift/kubernetes/pull/1653 due to https://issues.redhat.com/browse/TRT-1179. 

The identified problems were:
1. statefulset, which is fixed as part of this PR (see `UPSTREAM: 119761: Statefulset should wait for new replicas when removing .start.ordinal` commit)
2. the daemonset one is fixed with the fixes in 1.27.4 (specifically https://github.com/kubernetes/kubernetes/pull/118911/), which is included here, but we need to coordinate merging this change immediately with this PR to origin for those cases when external binaries don't work. 

/assign @bertinatto

### CODE REVIEW

**Comment by soltysh** [comment]
/hold 
for https://github.com/openshift/origin/pull/28148

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by stlaz** [comment]
/test e2e-aws-ovn-serial
running out of AWS capacity it seems

**Pull request merged**
