### PR TITLE
UPSTREAM: 113208: Set default test timeouts first, only then modify the required ones

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Comment by soltysh** [comment]
/hold 
for testing

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by soltysh** [comment]
confirmed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27416/pull-ci-openshift-origin-master-e2e-azure/1583101242920407040
/hold cancel

**Pull request merged**
