### PR TITLE
Bug 2063953: UPSTREAM: <carry>: use hardcoded rest mapper from library-go

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by tkashem** [comment]
1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
    - [ ] verified
    - [ ] does not apply
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
    - [ ] verified
    - [ ] does not apply
3. For branches that are in the Maintenance lifecycle phase:
    - [ ] The bug is a critical fix, no reasonable workaround exists, and a recommendation for upgrade has been ruled out, or 
    - [ ] The bug is a security related bug
    - [ ] Branch not in maintenance mode yet (current release + previous release for 90 days after current GA; everything older is in maintenance)
4. The severity field of the bug must be set to accurately reflect criticality.
    - [ ] verified
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
    - [ ] verified

**Comment by marun** [comment]
Wielding my magic rubber stamp!
/lgtm
/approve

**Comment by mffiedler** [comment]
Verified on cluster-bot cluster built from this PR.  See https://bugzilla.redhat.com/show_bug.cgi?id=2063953#c5

/label qe-approved

**Comment by deads2k** [comment]
metal ipv6 is failing on a network policy problem being checked in https://coreos.slack.com/archives/CS05TR7BK/p1650381982946289?thread_ts=1650288231.301399&cid=CS05TR7BK and https://coreos.slack.com/archives/C01CQA76KMX/p1650382104657319 .  The failure mode does not match the equinox infra failure.

/override ci/prow/e2e-metal-ipi-ovn-ipv6

**Comment by wking** [comment]
[Jenkins][1]:

```
level=info msg=ReadyIngressNodesAvailable: Authentication requires functional ingress which requires at least one schedulable and ready node. Got 0 worker nodes, 3 master nodes, 0 custom target nodes (none are schedulable or ready for ingress pods).
```

Sounds like the recent AWS issue:

```console
$ aws --region us-east-1 health describe-events --output json | jq -r '.events[] | select(.statusCode == "open" or (.endTime | gmtime | mktime) > now - 24*60*60).arn'
arn:aws:health:us-east-1::event/EC2/AWS_EC2_OPERATIONAL_ISSUE/AWS_EC2_OPERATIONAL_ISSUE_73F3E_F3EC0FA59A2
...
$ aws --region us-east-1 health describe-event-details --event-arns arn:aws:health:us-east-1::event/EC2/AWS_EC2_OPERATIONAL_ISSUE/AWS_EC2_OPERATIONAL_ISSUE_73F3E_F3EC0FA59A2 --query 'successfulSet[*].eventDescription' --output text
[RESOLVED] Increased Launch Failures

[08:39 AM PDT] We are investigating increased error rates for new launches that uses EBS Encryption by Default in the US-EAST-1 Region for three Availability Zones: use1-az2, use1-az6 and use1-az5.  Existing instances are not affected, and no other launch requests are affected.  We have identified the root cause and are working towards recovery. 

[09:18 AM PDT] We are investigating increased error rates for new launches that use EBS Encryption by Default in the US-EAST-1 Region.  Existing instances are not affected, and no other launch requests are affected. We have identified the root cause.  We are seeing recovery in use1-az5.  We continue to work towards recovery in the following Availability Zones: use1-az2, use1-az6.

[10:18 AM PDT] We have identified the root cause for increased error rates for new launches in the US-EAST-1 Region. The event affects instances which use EBS Encryption with unencrypted AMIs. Existing instances are not affected. The Availability Zone use1-az5 recovered at 9:05 AM PDT.  We continue to work towards recovery in the following Availability Zones: use1-az2, use1-az6.

[10:46 AM PDT] We have identified the root cause for increased error rates for new launches in the US-EAST-1 Region. The event affects instances which use EBS Encryption with unencrypted AMIs. Existing instances are not affected. The Availability Zone use1-az5 recovered at 9:05 AM PDT. We began seeing significant recovery in use-az6 at 10:20 AM PDT and are beginning to see recovery in use1-az2.

[11:30 AM PDT] Between 6:35 AM and 11:00 AM PDT we experienced increased error rates for new instance launches in the US-EAST-1 Region. Existing instances were unaffected by this issue. By 9:05 AM, we had full recovery in use1-az5. By 10:20 AM, we had full recovery in use1-az6, and at 11:00 AM we had recovered the final Availability Zone, use1-az2. The issue has been resolved and the service is operating normally.

The following AWS services were previously impacted but are now operating normally: AUTOSCALING, DATASYNC, EKS, WORKSPACES, SAGEMAKER, ELASTICACHE, FSX, LICENSEMANAGER, EMR, RDS, APPSTREAM2, ELB.
```

/test ci/prow/e2e-aws-jenkins

**Comment by deads2k** [comment]
metal-ipi passed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1245/pull-ci-openshift-kubernetes-release-4.8-e2e-metal-ipi/1516081907073290240

/override ci/prow/e2e-metal-ipi

**Comment by deads2k** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1245/pull-ci-openshift-kubernetes-release-4.8-e2e-aws-upgrade/1516470726968741888 has passed, overriding for speed.

/override ci/prow/e2e-aws-upgrade

**Pull request merged**
