### PR TITLE
Misc post rebase cleanup

### PR DESCRIPTION
**Pull request by marun**
- CSR workaround should no longer be necessary now that https://github.com/openshift/oc/pull/501 has merged.
- Unit test fixes from mfojtik: https://github.com/marun/kubernetes/pull/6
- Finalize switch to klog v2
- Update hyperkube dockerfile version to 1.19.0-rc.2

### CODE REVIEW

**Comment by marun** [comment]
The csr revert means this can't pass CI until the oc bump has merged and become available.

**Comment by marun** [comment]
/retest

oc bump has merged

**Comment by mfojtik** [comment]
@marun https://github.com/kubernetes/kubernetes/pull/93610 replaces https://github.com/openshift/kubernetes/pull/298/commits/5f578ad497f0fb11a1421e2380aafb0e04a0f8a9

**Pull request merged**
