### PR TITLE
Bump to kubernetes-v1.18.2

### PR DESCRIPTION
**Pull request by marun**
**TODO:**
 - [x] move commits
 - [x] code compiling
 - [x] bump to master of {api,apiserver-library-go,client-go,library-go} once updated
 - [x] tests passing
 - [x] verify passing

https://docs.google.com/spreadsheets/d/10KYptJkDB1z8_RYCQVBYDjdTlRfyoXILMa0Fg8tnNlY/edit#gid=1388579334

/cc @sttts @p0lyn0mial

### CODE REVIEW

**Comment by marun** [comment]
`make verify` has a ton of failures:

```
FAILED TESTS
========================
hack/make-rules/../../hack/verify-api-groups.sh
hack/make-rules/../../hack/verify-boilerplate.sh
hack/make-rules/../../hack/verify-conformance-requirements.sh
hack/make-rules/../../hack/verify-external-dependencies-version.sh
hack/make-rules/../../hack/verify-generated-files-remake.sh
hack/make-rules/../../hack/verify-golint.sh
hack/make-rules/../../hack/verify-govet.sh
hack/make-rules/../../hack/verify-import-aliases.sh
hack/make-rules/../../hack/verify-no-vendor-cycles.sh
hack/make-rules/../../hack/verify-openapi-spec.sh
hack/make-rules/../../hack/verify-spelling.sh
hack/make-rules/../../hack/verify-staticcheck.sh
hack/make-rules/../../hack/verify-typecheck-providerless.sh
hack/make-rules/../../hack/verify-typecheck.sh
hack/make-rules/../../hack/verify-vendor.sh
hack/make-rules/../../hack/verify-publishing-bot.py
```

I'm assuming something trivial is wrong here given that rc.1 passed all of these tests and the changes are minimial.

**Comment by marun** [comment]
3 unit tests are failing, all in oom_watcher_linux_test.go:

https://gist.github.com/marun/2e5662ab60eb34ca0de12c0f0a337f30

This despite [carrying the rc.1 fix](https://github.com/openshift/kubernetes/commit/b9a42f3c431cdf78f070f869dc08ed014dbd5e40).

**Comment by p0lyn0mial** [comment]
I think that the following commits are missing.

1. https://github.com/openshift/kubernetes/commit/274c12a30cc3872c6221e2b6c32429959eb94e31 (UPSTREAM: 90234: Remove PreStop hook from hostpath CSI driver)
2. https://github.com/openshift/kubernetes/commit/5db3ed9dc5a84587a026a89dd17742902013ec49 (UPSTREAM: 90254: IngressClass error test is flaky)
3. https://github.com/openshift/kubernetes/commit/bed688bb88774925aa3fe4c8d59e60a558088c38 (UPSTREAM: 89833: kube-openapi bump to release-1.18)
4. https://github.com/openshift/kubernetes/commit/b0c1c91f195641bb7d855a694223dcc2e6378782 (UPSTREAM: <drop>: Increate timeout in volume expansion test)

**Comment by marun** [comment]
> I think that the following commits are missing.
> 
> 1. [274c12a](https://github.com/openshift/kubernetes/commit/274c12a30cc3872c6221e2b6c32429959eb94e31) (UPSTREAM: 90234: Remove PreStop hook from hostpath CSI driver)
> 2. [5db3ed9](https://github.com/openshift/kubernetes/commit/5db3ed9dc5a84587a026a89dd17742902013ec49) (UPSTREAM: 90254: IngressClass error test is flaky)
> 3. [bed688b](https://github.com/openshift/kubernetes/commit/bed688bb88774925aa3fe4c8d59e60a558088c38) (UPSTREAM: 89833: kube-openapi bump to release-1.18)
> 4. [b0c1c91](https://github.com/openshift/kubernetes/commit/b0c1c91f195641bb7d855a694223dcc2e6378782) (UPSTREAM: : Increate timeout in volume expansion test)

Good catch, fixed.

**Comment by marun** [comment]
The unit test failures ended up being due to `/dev/ksmg` being set readable by non-root on my workstation. Apparently that's not the default so the tests will pass on the average system.

**Comment by soltysh** [comment]
Manually adding valid-bug, since the bot can't cope with our branching approach on this repo.

**Pull request merged**
