### PR TITLE
OCPBUGS-42640: Revert #2089 "OCPBUGS-42167: Bump k8s api to 1.30.5"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts #2089 ; tracked by https://issues.redhat.com/browse/TRT-1839

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Seems to have permafailed a test on metal related to aggregated apiserver backward compatability

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ipi-ovn-bm
```

CC: @jerpeter1

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ipi-ovn-bm

**Comment by dgoodwin** [comment]
With @bertinatto help we now know why this was, a new image is used in the tests in this repo, which are not yet vendored into origin. metal jobs (at least some) mirror images, by examining the list used in origin, so this image is not getting mirrored.

We're going to revert, find a hack to get the image mirrored, then bring this back.

Because we have this as the only change in the bad payload, and confirmation why it is happening, we're going to force merge the revert to get payloads back ASAP.

/override ci/prow/e2e-gcp-ovn-upgrade
/override ci/prow/e2e-aws-ovn-downgrade
/override ci/prow/verify-commits
/override ci/prow/k8s-e2e-gcp-serial
/override ci/prow/integration
/override ci/prow/e2e-aws-ovn-serial
/override ci/prow/e2e-aws-ovn-crun
/override ci/prow/k8s-e2e-gcp-ovn
/override ci/prow/e2e-gcp
/override ci/prow/e2e-aws-ovn-upgrade
/override ci/prow/k8s-e2e-conformance-aws
/override ci/prow/e2e-aws-ovn-fips
/override ci/prow/k8s-e2e-aws-ovn-serial
/override ci/prow/e2e-azure-ovn-upgrade
/override ci/prow/e2e-aws-ovn-runc

**Comment by neisw** [comment]
/retitle OCPBUGS-42640: Revert #2089 "OCPBUGS-42167: Bump k8s api to 1.30.5"

**Pull request merged**
