### PR TITLE
OCPNODE-1892: UPSTREAM: 122643: Add a new neverTerminate job behavior just for upgrade

### PR DESCRIPTION
**Pull request by soltysh**
/assign @sairameshv 

/hold 
until upstream PR gets tagged

### CODE REVIEW

**Review by sairameshv — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
Upstream merged
/hold cancel

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-crun-wasm
not relevant, since this PR is changing upgrade jobs, only

**Pull request merged**
