### PR TITLE
Bug 2020644: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs

### PR DESCRIPTION
**Pull request by dmage**
#### What type of PR is this?

/kind bug
/kind regression

This is a cherry-pick of #1033.

#### What this PR does / why we need it:

After we merged https://github.com/openshift/apiserver-library-go/pull/50 we found that some objects are not known by the image policy admission plugin. This PR updates the plugin so that it can mutate these objects.

#### Which issue(s) this PR fixes:

Fixes BZ 2020644.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xiuwang** [comment]
@dmage @soltysh Could you help add backport-risk-assessed label, so qe can add cherry-pick-approved ?

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed
/label backports/validated-commits
/remove-label backports/unvalidated-commits

**Comment by xiuwang** [comment]
@wangke19 Could you help to add cherry-pick-approved label? Thanks

**Comment by wangke19** [comment]
> @wangke19 Could you help to add cherry-pick-approved label? Thanks

Done

**Pull request merged**
