### PR TITLE
OCPBUGS-15726: UPSTREAM: 118881: fix openapi/v3 non local apiservices aggregation

### PR DESCRIPTION
**Pull request by ardaguclu**
Carrying https://github.com/kubernetes/kubernetes/pull/118881

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by ardaguclu** [comment]
different failure;
/retest-required

**Comment by ardaguclu** [comment]
This aws-ovn-fips job https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1629/pull-ci-openshift-kubernetes-master-e2e-aws-ovn-fips/1679760031450402816 has passed to testing stage.
/hold cancel

**Pull request merged**
