### PR TITLE
 Bug 1945856: 99729:Only system-node-critical pods should be OOM Killed last

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
Backport of https://github.com/openshift/kubernetes/pull/641/commits/d201f2f905bc5785d377723f2000b798faec15ae which will go to master.

This will help in having appropriate priority classes for components like monitoring

cc @bparees @smarterclayton @rphillips

### CODE REVIEW

**Comment by bparees** [comment]
cc @simonpasquier

**Comment by ravisantoshgudimetla** [comment]
cc @openshift/openshift-team-monitoring

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
