### PR TITLE
OCPBUGS-31740: 4.15: UPSTREAM: 124048: Use the right feature gate when updating uncertain volumes

### PR DESCRIPTION
**Pull request by jsafrane**
This is cherry pick of https://github.com/openshift/kubernetes/pull/1919 into 4.15

@openshift/storage

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by duanwei33** [comment]
Verification passed with open PR, see verification way [here](https://issues.redhat.com/browse/OCPBUGS-30957?focusedId=24479385&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24479385 )

The pods came back in ~5 mins.
```
ss-storage-test-3                                   0/1     ContainerCreating   1          2m50s
ss-storage-test-9                                   0/1     ContainerCreating   1          107s
ss-storage-test-8                                   0/1     ContainerCreating   1          118s
ss-storage-test-9                                   1/1     Running             1          6m8s
ss-storage-test-2                                   1/1     Running             1          7m21s
ss-storage-test-1                                   1/1     Running             1          7m37s
```

**Pull request merged**
