### PR TITLE
revert 1.30

### PR DESCRIPTION
**Pull request by dgoodwin**
Trial revert to test some things.

- **Revert "Merge pull request #1983 from soltysh/bug_34593"**
- **Revert "Merge pull request #1982 from soltysh/skip_sleepaction"**
- **Revert "Merge pull request #1981 from soltysh/skip_storage"**
- **Revert "Merge pull request #1827 from tkashem/termination-events"**
- **Revert "Merge pull request #1979 from soltysh/bump-1.30.1"**
- **Revert "Merge pull request #1953 from dinhxuanvu/rebase-1.30.0-2"**

Regressions thought to be linked to the 1.30 rebase:

https://issues.redhat.com/browse/OCPBUGS-34666 etcd data not in correct location techpreview
~https://issues.redhat.com/browse/TRT-1684 various storage tests failing due to origin/kube mismatch~
~https://issues.redhat.com/browse/TRT-1685 hypershift featuregate permafail~
https://issues.redhat.com/browse/OCPBUGS-34593 kube scheduler divide by 0 panic

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview-serial

**Comment by dgoodwin** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance

**Comment by dinhxuanvu** [comment]
Let hold this PR until we resolve this [origin PR](https://github.com/openshift/origin/pull/28843). If it resolves the etcd data failure, then we won't need to revert the k8s 1.30.
/hold

**Comment by dgoodwin** [comment]
/close

Trying to fix forward for now as this cannot merge without work in origin.

**Pull request closed without merging**
