### PR TITLE
Bug 1999325: Backport 107821 and 107831

### PR DESCRIPTION
**Pull request by rphillips**
ref: https://github.com/kubernetes/kubernetes/pull/107821
and
ref: https://github.com/kubernetes/kubernetes/pull/107831

### CODE REVIEW

**Comment by ehashman** [comment]
/close

@rphillips I think we will need one more patch for this... opened https://github.com/openshift/kubernetes/pull/1236 on top of this branch

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
