### PR TITLE
UPSTREAM: <drop>: bump(openshift/client-go,library-go,apiserver-library-go)

### PR DESCRIPTION
**Pull request by soltysh**
/assign @bertinatto

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-fips
we're dealing with that in a separate PR

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-vsphere-ovn-csi

**Pull request merged**
