### PR TITLE
Bug 1948953: UPSTREAM: <carry>: Set informer for openstack

### PR DESCRIPTION
**Pull request by mandre**
Set informer for the openstack cloud provider to ensure it is properly
initialized when reading config from a secret.

Upstream https://github.com/kubernetes/kubernetes/pull/89885 was closed in favor of https://github.com/kubernetes/kubernetes/pull/96750.

Co-authored-by: Hemant Kumar <hekumar@redhat.com>

### CODE REVIEW

**Comment by mandre** [comment]
I'm fairly confident this fixes https://bugzilla.redhat.com/show_bug.cgi?id=1948953. Sadly we do not yet have the parallel test suite running in `e2e-openstack` to confirm this. I'm changing this with https://github.com/openshift/release/pull/17795.

Running the `[sig-storage] In-tree Volumes [Driver: cinder] [Testpattern: Pre-provisioned PV (default fs)] volumes should allow exec of files on the volume [Suite:openshift/conformance/parallel] [Suite:k8s]` test locally with this code, I don't see the failure anymore:
```
STEP: Creating a PVC followed by a PV
Apr 15 15:38:52.328: INFO: Waiting for PV cinder-btf6t to bind to PVC pvc-7x2qp
Apr 15 15:38:52.328: INFO: Waiting up to 3m0s for PersistentVolumeClaims [pvc-7x2qp] to have phase Bound
Apr 15 15:38:52.420: INFO: PersistentVolumeClaim pvc-7x2qp found but phase is Pending instead of Bound.
Apr 15 15:38:54.510: INFO: PersistentVolumeClaim pvc-7x2qp found and phase=Bound (2.181655411s)
Apr 15 15:38:54.510: INFO: Waiting up to 3m0s for PersistentVolume cinder-btf6t to have phase Bound
Apr 15 15:38:54.602: INFO: PersistentVolume cinder-btf6t found and phase=Bound (92.646545ms)
STEP: Creating pod exec-volume-test-preprovisionedpv-6wn5
STEP: Creating a pod to test exec-volume-test
Apr 15 15:38:54.889: INFO: Waiting up to 5m0s for pod "exec-volume-test-preprovisionedpv-6wn5" in namespace "e2e-volume-960" to be "Succeeded or Failed"
```

While it was [previously failing](https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-openstack-4.8/1382876399685079040) with:
```
STEP: Creating a PVC followed by a PV
[AfterEach] [Testpattern: Pre-provisioned PV (default fs)] volumes
  k8s.io/kubernetes@v1.20.0/test/e2e/framework/framework.go:175
STEP: Collecting events from namespace "e2e-volume-4438".
STEP: Found 2 events.
Apr 16 02:57:49.530: INFO: At 2021-04-16 02:57:46 +0000 UTC - event for e2e-volume-4438: {namespace-security-allocation-controller } CreatedSCCRanges: created SCC ranges
Apr 16 02:57:49.530: INFO: At 2021-04-16 02:57:49 +0000 UTC - event for pvc-b644t: {persistentvolume-controller } ProvisioningFailed: storageclass.storage.k8s.io "e2e-volume-4438" not found
Apr 16 02:57:49.561: INFO: POD  NODE  PHASE  GRACE  CONDITIONS
Apr 16 02:57:49.561: INFO: 
Apr 16 02:57:49.646: INFO: skipping dumping cluster info - cluster too large
STEP: Destroying namespace "e2e-volume-4438" for this suite.
fail [k8s.io/kubernetes@v1.20.0/test/e2e/storage/testsuites/base.go:421]: PVC, PV creation failed
Unexpected error:
    <*errors.errorString | 0xc001536440>: {
        s: "PV Create API error: persistentvolumes \"cinder-\" is forbidden: error querying Cinder volume cce1b69c-3e1b-47ab-bba4-ffd1a29b625a: unable to initialize cinder client for region: RegionOne, err: cloud provider is not initialized: secret lister is not initialized",
    }
    PV Create API error: persistentvolumes "cinder-" is forbidden: error querying Cinder volume cce1b69c-3e1b-47ab-bba4-ffd1a29b625a: unable to initialize cinder client for region: RegionOne, err: cloud provider is not initialized: secret lister is not initialized
occurred
```

**Comment by gnufied** [comment]
I have also manually verified that this patch fixes the problem.Until we can merge - https://github.com/kubernetes/kubernetes/pull/96750 we can carry this (kinda have to)

**Comment by gnufied** [comment]
lgtm

**Comment by jsafrane** [comment]
@mandre can you please fix the commit message? It must start with `UPSTREAM: <nr>: xxx`

**Comment by jsafrane** [comment]
/lgtm
It is what we want to fix the referenced bug. It fixes a carry patch we already have. I let the approvers judge if it's acceptable.

**Comment by EmilienM** [comment]
lgtm, Martin is on PTO, please ping me directly if any change is needed. We need this patch asap.
Thanks

**Comment by EmilienM** [comment]
`ci/prow/e2e-agnostic-cmd ` seems broken:
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-kubernetes-master-e2e-agnostic-cmd?buildId=

**Comment by EmilienM** [comment]
@jsafrane how can we get this one merged, please? Can you approve it?
Thanks

**Comment by EmilienM** [comment]
Like I said in a previous comment, `ci/prow/e2e-agnostic-cmd` seems broken. I wonder if it's a known issue.

**Comment by soltysh** [comment]
> Like I said in a previous comment, `ci/prow/e2e-agnostic-cmd` seems broken. I wonder if it's a known issue.

Yeah, fix https://github.com/openshift/origin/pull/26096

**Comment by EmilienM** [comment]
@soltysh could you please override the failing jobs which have nothing to do with that patch, thanks a lot

**Pull request merged**
