### PR TITLE
Bug 1929012: UPSTREAM: 96984: APF e2e: wait for steady state before proceeding

### PR DESCRIPTION
**Pull request by tkashem**
Pick both:
- https://github.com/kubernetes/kubernetes/pull/96984 
- https://github.com/kubernetes/kubernetes/pull/96966 

Which issue(s) this PR fixes:
Related to #96803 and #96893

### CODE REVIEW

**Comment by mfojtik** [comment]
The changes here are limited to e2e test and it is supposed to reduce flake rates.

**Comment by tkashem** [comment]
`TestSyncPodsDeletesWhenSourcesAreReadyPerQOS` keeps failing.

/retest

**Comment by mfojtik** [comment]
This is a flake fix that we get free with 1.21 rebase which will happen soon. There is no point to merge this into master just to be replaced with rebase. The risk of regression here is super low as this is a flaking test fix.

**Pull request merged**
