### PR TITLE
[release-4.12] OCPBUGS-37282: UPSTREAM: 126104: Add funcs in pkg/filesystem/util that can actually …

### PR DESCRIPTION
**Pull request by jrvaldes**
Upstream patch:

https://github.com/kubernetes/kubernetes/pull/126104

### CODE REVIEW

**Comment by sdodson** [comment]
@jrvaldes Ok, how far back have we revendored WMCO thus far?

**Comment by jrvaldes** [comment]
> @jrvaldes Ok, how far back have we revendored WMCO thus far?

4.14

**Comment by sdodson** [comment]
Ok, let me know once 4.13 is revendored and effectively ON_QA

**Comment by jrvaldes** [comment]
depends on 

- https://github.com/openshift/windows-machine-config-operator/pull/2345

**Comment by jrvaldes** [comment]
e2e-agnostic-ovn-cmd job is been failing for a while (since Apr 05), I don't feel is related to the proposed changes. 

https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-kubernetes-release-4.12-e2e-agnostic-ovn-cmd

**Comment by sdodson** [comment]
Ack, should be good to go now.

**Comment by jrvaldes** [comment]
Opened WMCO bump PR

- https://github.com/openshift/windows-machine-config-operator/pull/2369

**Pull request merged**
