### PR TITLE
Bug 2024995: Fix subpath source check

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2024995

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve

**Review by Phaow — COMMENTED** [review]
/lgtm
/label qe-approved

**Review by Phaow — COMMENTED** [review]
/lgtm

**Comment by Phaow** [comment]
retest e2e-azure-upgrade

**Pull request merged**
