### PR TITLE
Bug 1968520: update to k8s 1.21.2

### PR DESCRIPTION
**Pull request by soltysh**
/assign @sttts 

Only and expected problems were caused by https://github.com/openshift/kubernetes/pull/761. 
You can verify the conflicts in `UPSTREAM: <drop>: manually resolve conflicts in go.mod and go.sum files` commit. 
All the rest was clean.

### CODE REVIEW

**Comment by ehashman** [comment]
Note: https://github.com/kubernetes/kubernetes/issues/102676 was introduced in 1.21.2, we may want to wait for the fix in 1.21.3.

**Comment by soltysh** [comment]
Replaced with https://github.com/openshift/kubernetes/pull/888

**Pull request closed without merging**
