### PR TITLE
[release-4.12] OCPBUGS-3503: UPSTREAM: <drop>: Bump library-go.

### PR DESCRIPTION
**Pull request by benluddy**
Supersedes https://github.com/openshift/kubernetes/pull/1414, which was inert but inadvertently based on a release-4.13 commit.

### CODE REVIEW

**Comment by benluddy** [comment]
> The following commits could not be validated and must be approved by a top-level approver:
> ... lots of things ...

PR base branch was initially wrong, fixed https://github.com/openshift/kubernetes/pull/1423#event-7825869724.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Pull request merged**
