### PR TITLE
OCPBUGS-19666: kubelet/cm: use MkdirAll when creating cpuset to ignore file exists error

### PR DESCRIPTION
**Pull request by haircommander**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-fips
we're dealing with that in a separate PR

**Comment by rphillips** [comment]
Hmm. Flake.

/test unit

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-fips
this is being handled in a different PR
/test e2e-aws-ovn-serial

**Pull request merged**
