### PR TITLE
API-1783: Bump 1.30.2

### PR DESCRIPTION
**Pull request by dinhxuanvu**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@soltysh PTAL. Thanks

**Comment by rphillips** [comment]
I'm debugging a separate issue. I would like to see a few run of this payload.

/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn 3

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
