### PR TITLE
OCPBUGS-18287,OCPBUGS-19480: Update to Kubernetes 1.26.9

### PR DESCRIPTION
**Pull request by suleymanakbas91**

### CODE REVIEW

**Comment by sdodson** [comment]
/retitle OCPBUGS-18287,OCPBUGS-19480: Update to Kubernetes 1.26.9

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
this never passes on a k8s bump PR

**Comment by soltysh** [comment]
https://github.com/openshift/kubernetes/pull/1709 merged, so I'm overriding jira labels

/remove-label jira/invalid-bug
/label jira/valid-bug

/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Comment by soltysh** [comment]
/hold
it looks like the integration failure is real, I need to have a closer look at it

**Comment by soltysh** [comment]
We're missing a fix on that new events_test.go file, https://github.com/soltysh/kubernetes/commit/be80239150d151dae4334e2cf0fc48d378103670 which is similar to our carry https://github.com/openshift/kubernetes/commit/2f4c829d138981b9832627b963058ad3fe9e1d47

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
this never passes on a k8s bump PR

**Pull request merged**
