### PR TITLE
Bump 1.19 oc branch to GA

### PR DESCRIPTION
**Pull request by damemi**
1.19 GA bump for oc, following the changes from the rc.1 bump https://github.com/openshift/kubernetes/pull/169, minus https://github.com/openshift/kubernetes/pull/169/commits/84250a87e09e1abe6279493daaa9301b25767800

### CODE REVIEW

**Comment by damemi** [comment]
@soltysh I've tried disabling some more tests, one by one, but it seems like a lot of these have that same problem (`error: mkdir /.kube: permission denied`).

It's also tough to diagnose because they run on my system: 
```
[1.19.0-bump] ~/go/src/k8s.io/kubernetes$ go test ./vendor/k8s.io/kubectl/pkg/cmd/config/...
ok  	k8s.io/kubectl/pkg/cmd/config	0.475s
```

**Comment by damemi** [comment]
Updated to re add  https://github.com/openshift/kubernetes/pull/324/commits/6d497c0245ef53fb9c8cb54159b187be4dcbea0a

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
