### PR TITLE
UPSTREAM: 96856: e2e network policy enclose IPv6 destinations

### PR DESCRIPTION
**Pull request by stbenjam**
A variety of IPv6 e2e tests in OpenShift are failing with errors like this:

```
Last 100 log lines of client-can-connect-80-r9gjz:
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
UNKNOWN: address fd00:10:96::8198:80: too many colons in address
```

### CODE REVIEW

**Comment by stbenjam** [comment]
Are there instructions somewhere about how to carry this patch in OpenShift? I'm just mimicking the PR's that are here.

**Comment by smarterclayton** [comment]
This seem like it should just be an upstream change (if it's clearly connect for ipv6)?

**Comment by stbenjam** [comment]
@smarterclayton It is already in k8s 1.21, https://github.com/kubernetes/kubernetes/pull/96856.

Do you have a reference for what I need to do to have us carry it in openshift/kubernetes 1.20? Maybe I misunderstood what "UPSTREAM: <carry>" is supposed to mean.

**Comment by smarterclayton** [comment]
You would do `UPSTREAM: 96856: <title>` on your commit message

**Comment by smarterclayton** [comment]
/lgtm

Although rebase is coming soon

**Comment by stbenjam** [comment]
> Although rebase is coming soon

Right, but the network folks are keen to get more of the sig-network tests running.  I need to vendor this into origin to fix some of them on IPv6, and we probably need to backport this to at least 4.7, too.

**Review by soltysh — APPROVED** [review]
/approve

I don't object and I'm always happy to see fixes to test which will be important to be stable when landing the rebase itself. I've only started this Wednesday and still waiting for 1.21.rc0 on Monday, so I'll be re-doing parts.

**Pull request merged**
