### PR TITLE
UPSTREAM: 93508: add permissions required by endpoints controller for blockOwnerDeletion

### PR DESCRIPTION
**Pull request by deads2k**
https://github.com/kubernetes/kubernetes/pull/93508

fixes problems in upgrade test  https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25314/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1287993294235635712

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
gcp-e2e-kubernetes is completely red: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-kubernetes-master-gcp-e2e-kubernetes I see it's required for this PR, but will it actually pass?

**Comment by marun** [comment]
> gcp-e2e-kubernetes is completely red: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-kubernetes-master-gcp-e2e-kubernetes I see it's required for this PR, but will it actually pass?

:( this job is NOT supposed to be required. -1 for having generated jobs not have any way of being made optional.

**Comment by marun** [comment]
> gcp-e2e-kubernetes is completely red: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-kubernetes-master-gcp-e2e-kubernetes I see it's required for this PR, but will it actually pass?

It's supposed to be optional. When I renamed the job I missed the detail that I would need to manually set optional to true in the generated job. This seems like a footgun, and I'm left wondering why it's not possible to set all job fields from template config.

**Comment by kikisdeliveryservice** [comment]
@marun after make update youll have to go in manually and add optional: true manually:
https://github.com/openshift/release/blob/648db46225097349c8e2d239749efb9b8f66c057/ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml#L1018

**Comment by sttts** [comment]
/override ci/prow/gcp-e2e-kubernetes

This is supposed to be optional until we have walked through getting it everything to run on OpenShift.

**Comment by sttts** [comment]
Button merge to stop bleeding. Tests are green. Just skipping retest.

**Pull request merged**
