### PR TITLE
SDN-4123: Sdn 4.15 kubernetes 1.28.3

### PR DESCRIPTION
**Pull request by jluhrsen**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by danwinship** [comment]
Can you squash `Prefer local endpoint for cluster DNS service` and `Prefer local TCP endpoint for cluster DNS service` together? (They were separate commits in the previous branch because the UDP-only one was carried forward from the previous branch, while the TCP one was added later on. But they're part of the same feature so they should just be squashed together now.)

Likewise, can you squash the unit test fixes into the corresponding commits that originally introduced those unit tests?

**Comment by jluhrsen** [comment]
> Can you squash `Prefer local endpoint for cluster DNS service` and `Prefer local TCP endpoint for cluster DNS service` together? (They were separate commits in the previous branch because the UDP-only one was carried forward from the previous branch, while the TCP one was added later on. But they're part of the same feature so they should just be squashed together now.)
> 
> Likewise, can you squash the unit test fixes into the corresponding commits that originally introduced those unit tests?

@danwinship, I can squash these commits together and add the UT changes to one of them, but I'm having trouble figuring it out. I was trying to figure out which commits added the UT failures, but these four commits I have before
the UT fix don't seem healthy by themselves.

the first commit is fine (builds and tests pass)
starting at the 2nd commit doesn't build (problem with some unresolved reference to `utilpointer.StringPtr`.
from the 3rd and 4th commit, it builds but tests fail
the 5th is the UT fix.

What do you want me to do here?

**Comment by danwinship** [comment]
yeah, this looks right

**Pull request merged**
