### PR TITLE
OCPBUGS-28812: UPSTREAM: <carry>: kubelet/cm: fix bug where kubelet restarts from missing cpuset cgroup

### PR DESCRIPTION
**Pull request by haircommander**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rphillips** [comment]
lgtm

**Comment by haircommander** [comment]
https://github.com/kubernetes/kubernetes/pull/125923 merged, this should be ready

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
