### PR TITLE
OCPBUGS-29661: Bump to 1.28.7

### PR DESCRIPTION
**Pull request by bertinatto**
/assign @soltysh

### CODE REVIEW

**Comment by bertinatto** [comment]
/hold
This depends on https://github.com/openshift-eng/ocp-build-data/pull/4416.

**Comment by soltysh** [comment]
> This depends on [openshift-eng/ocp-build-data#4416](https://github.com/openshift-eng/ocp-build-data/pull/4416).

/hold cancel
this doesn't have to wait for it

although it needs to wait for 4.15 queue to re-open

**Comment by soltysh** [comment]
Manually overriding valid-bug since this is first in line.
/label jira/valid-bug
/label backport-risk-assessed

**Pull request merged**
