### PR TITLE
Allow priority classes to be updated

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Recently monitoring team created a highest user defined priority, now we want it's priority to be superceded by another priority class and we are not able to do so since highest user defined priority is hardcoded. This patch ensures we can unstuck for now. ~~Long term is to discuss with the community to see if there is a way to expose the hardcoded highest user defined priority via config.~~

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
cc @bparees @wking @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
cc @damemi @soltysh 

Folks let us see if we can bring this into community meeting for tomorrow.

**Comment by bparees** [comment]
@lilic @s-urbaniak this is a possible path forward.  Might be something to consider post 4.7.0 when you're ready to separate the UWM and CM prom priorities again.  Assuming the relevant kube teams are willing to carry this patch basically forever.

i'm guessing we won't get consensus on this approach in time for 4.7.0 itself.

**Comment by ravisantoshgudimetla** [comment]
Seems the community is leaning towards https://github.com/kubernetes/kubernetes/issues/99205

**Comment by sttts** [comment]
This must go upstream first.

**Comment by soltysh** [comment]
> Long term is to discuss with the community to see if there is a way to expose the hardcoded highest user defined priority via config.

That is the only way forward, we can't afford adding unnecessary patches which diverge our API from upstream. I agree with @sttts this can't land in this way.

**Comment by lilic** [comment]
We (monitoring team) are not that in a hurry to get this sorted urgently, so we can wait until next release of kube gets to OpenShift. From what I understood on slack is that "We're close to getting consensus on updating priority classes in kube upstream. " so if that lands in 1.21 we can get it in OpenShift 4.8?

The risk is another component getting scheduled before cluster monitoring Prometheus if this doesn't land as both components now share same class. There was talk of backporting this to 4.7 as well. cc @simonpasquier

**Comment by ravisantoshgudimetla** [comment]
> Note that this is a change against the API. We cannot take this as carry patch. Diversion for APIs is a nogo. Please sync with @soltysh of how to get this upstream.

Right. I don't want this to be taken as a carry patch. We have been trying to get some consensus upstream as I mentioned [earlier](https://github.com/openshift/kubernetes/pull/575#issuecomment-784751500) and @soltysh was kept in loop too on internal slack channels.

>  We're close to getting consensus on updating priority classes in kube upstream. " so if that lands in 1.21 we can get it in OpenShift 4.8?

 If it needs a KEP, I believe the boat for 1.21 has sailed for us. If we don't need KEP then perhaps there are chances of landing this patch in 1.21.

**Comment by soltysh** [comment]
> If it needs a KEP, I believe the boat for 1.21 has sailed for us. If we don't need KEP then perhaps there are chances of landing this patch in 1.21.

My understanding from recent discussions is this will require a KEP, so it's a 1.22 / OCP 4.9 at soonest.

**Comment by ravisantoshgudimetla** [comment]
@soltysh is right. Since this feature is out of scope for 1.21 @openshift/openshift-team-monitoring let us know if you want an alternative plan which is less non-intrusive or would it be ok to release as is in 4.8 without this patch?

**Pull request closed without merging**
