### PR TITLE
[release-4.8] Bug 1998391: UPSTREAM: 104530: [1.21] bump runc to 1.0.2

### PR DESCRIPTION
**Pull request by kolyshkin**
Manual port of https://github.com/kubernetes/kubernetes/pull/104530/ to release-4.8 branch. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1993980.

Same as https://github.com/openshift/kubernetes/pull/910 but for 4.8.

### CODE REVIEW

**Comment by kolyshkin** [comment]
> @kolyshkin: the contents of this pull request could not be automatically validated.
> 
> The following commits could not be validated and must be approved by a top-level approver:
> 
> * [18f2dfe|UPSTREAM: 104530: pkg/kubelet/cm: use SkipFreezeOnSet](https://github.com/openshift/kubernetes/commit/18f2dfef012cab45f9bad49b0e6f36ab100a7d49): the upstream PR [kubernetes/kubernetes#104530](https://github.com/kubernetes/kubernetes/pull/104530) has not yet merged
> * [bb12bee|UPSTREAM: 104530: Switch to non-deprecated timestamppb.Now()](https://github.com/openshift/kubernetes/commit/bb12beec83de118baba5d5a92fcbb045373942cd): the upstream PR [kubernetes/kubernetes#104530](https://github.com/kubernetes/kubernetes/pull/104530) has not yet merged
> * [f9c0794|UPSTREAM: 104530: [1.21] bump runc to 1.0.2](https://github.com/openshift/kubernetes/commit/f9c0794248af8656f2584ed9d331cf8ed1416d49): the upstream PR [kubernetes/kubernetes#104530](https://github.com/kubernetes/kubernetes/pull/104530) has not yet merged

This is now merged but I don't know how to ask the bot to re-validate it :-\

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

adding cherry-pick approved

**Pull request merged**
