### PR TITLE
OCPNODE-1892: UPSTREAM: <carry>: update test rules

### PR DESCRIPTION
**Pull request by soltysh**
/assign @sairameshv

### CODE REVIEW

**Review by sairameshv — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
/override ci/prow/k8s-e2e-gcp-ovn
unrelated failure

**Comment by soltysh** [comment]
/override ci/prow/e2e-gcp-ovn-upgrade
not related with this PR

**Comment by soltysh** [comment]
/override ci/prow/k8s-e2e-gcp-ovn
unrelated failure

**Pull request merged**
