### PR TITLE
Origin 3.11 kubernetes 1.11.0 picks

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by liggitt** [comment]
* `a50e9d81a14 UPSTREAM: <carry>: fix fifo resync, remove after FIFO is dead` is still needed
* any changes needed to `cf56f058d1188cd45e2ed43ef0443f5f122c7fed UPSTREAM: <drop>: generated` because of dropping the create namespaced objects?
* squash two `UPSTREAM: <carry>: rewrite unstructured objects on the CLI to avoid oapi` commits?

looking at ugorji now

**Comment by deads2k** [comment]
> any changes needed to cf56f058d1188cd45e2ed43ef0443f5f122c7fed UPSTREAM: <drop>: generated because of dropping the create namespaced objects?

nothing obvious.



> a50e9d81a14 UPSTREAM: <carry>: fix fifo resync, remove after FIFO is dead is still needed

repicked



> squash two UPSTREAM: <carry>: rewrite unstructured objects on the CLI to avoid oapi commits?

ok

**Comment by liggitt** [comment]
ugorji decodes `"finalizers":{"c.io/foo":"d.io/foo"}` as `"finalizers": ["c.io/foo","d.io/foo"]`

as much as it pains me, I think json-iter is a better choice now. let's drop the ugorji carries.

**Comment by deads2k** [comment]
here we go

**Pull request merged**
