### PR TITLE
brings kubernetes 1.17.0 rc.2

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**: applies our carry patches into kube 1.17-rc.2 release

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
requires https://github.com/openshift/release/pull/6297

**Comment by p0lyn0mial** [comment]
as it wants a newer version of golang
```
Detected go version: go version go1.13.1 linux/amd64.
Kubernetes requires go1.13.4 or greater.
Please install go1.13.4 or later.
```

**Comment by p0lyn0mial** [comment]
I opened a [PR](https://github.com/openshift/kubernetes/pull/104) with an unmodified version of Kube (1.17.rc2) just to compare the test failures[2]. They seem to align with this PR[1]. Additionally, I tried to run some of the broken tests on my local machine in a docker with `centos:7` (it has the same version of the bash as our `CI`)  image and they passed. The test failures seem to be related to infra/tooling.

[1] - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes/102/pull-ci-openshift-kubernetes-origin-4.4-kubernetes-1.17.0-rc.2-unit/9

[2] - https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes/104/pull-ci-openshift-kubernetes-origin-4.4-kubernetes-1.17.0-rc.2-unit/18

**Comment by p0lyn0mial** [comment]
The current status for the `unit` is 22598 tests, 24 skipped, 54 failures, 22513 passed (don't try to add the numbers)

**Comment by p0lyn0mial** [comment]
The `verify` step suffers from a variety of reasons: `group_dirnames[@]: unbound variable`, `Can't find 'docker' in PATH, please fix and retry.`, `can't load package: package k8s.io/kubernetes/vendor/golang.org/x/lint/golint` but at least it runs. 

Initially, it failed on `unbound variable` error too, simply adding a default value for a variable gave me a hot loop in a script because it had different assumptions.

Some unit tests failed due to `local: -n: invalid option` which seems to be caused by an outdated bash (`4.2`) in our `CI` https://github.com/kubernetes/kubernetes/issues/82605, similarly to `unbound variable` error.

I think we could start by upgrading and aligning our tooling with upstream first as patching and changing the scripts is a bumpy road.

**Comment by tnozicka** [comment]
> I think we could start by upgrading and aligning our tooling with upstream first as patching and changing the scripts is a bumpy road.

I think this will be more about fixing upstream script and creating alternative paths or fixing assumptions there. Like people don't have docker and you don't run nested containers. Fixing bash to be compatible with 4.2 is gonna be mostly cosmetic. Making sure upstream scripts run bash with `-euo pipefail` should likely help prevent some of the further issues.

I don't think our tooling can do more then potentially bump to centos:8 to get newer bash, but there will always be a skew.

**Pull request merged**
