### PR TITLE
UPSTREAM: <drop>: Bump golang.org/x/net to v0.23.0

### PR DESCRIPTION
**Pull request by flavianmissi**
./hack/pin-dependency.sh golang.org/x/net v0.23.0
./hack/update-vendor.sh

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by flavianmissi** [comment]
test failures seem unrelated to the changes in this PR.
/retest

**Comment by soltysh** [comment]
/hold 
for https://github.com/openshift/kubernetes/pull/1930 to merge first

**Review by soltysh — APPROVED** [review]
/hold cancel

/remove-label backports/unvalidated-commits
/label backports/validated-commits

/lgtm
/approve
/label backport-risk-assessed

**Comment by soltysh** [comment]
/remove-label backports/unvalidated-commits
/label backports/validated-commits
/lgtm

Manually overriding the valid-bug jira, since that is just updating to use the officially released version.
/label jira/valid-bug

**Pull request merged**
