### PR TITLE
Bump to k8s 1.25.2

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
it won't pass on a k8s bump PR

**Review by sanchezl — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
/override ci/prow/4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade
this is optional job

**Comment by soltysh** [comment]
We got [green upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1380/pull-ci-openshift-kubernetes-master-e2e-aws-upgrade/1578406456569368576) run before and also in the [payload](https://pr-payload-tests.ci.openshift.org/runs/ci/bc11c730-4ad3-11ed-8177-da1146281cc0-0)
/override ci/prow/e2e-aws-upgrade

**Comment by soltysh** [comment]
We already got [green azure-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1380/pull-ci-openshift-kubernetes-master-e2e-azure-upgrade/1578406456686809088) 
/override ci/prow/e2e-azure-upgrade

**Comment by soltysh** [comment]
/override ci/prow/verify-commits 
that never passes in CI

**Comment by soltysh** [comment]
We already got [green e2e-aws-ovn-fips](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1380/pull-ci-openshift-kubernetes-master-e2e-aws-ovn-fips/1580561826272251904)
/override ci/prow/e2e-aws-ovn-fips

**Comment by soltysh** [comment]
Infra failed and we got previous [green e2e-aws-serial](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1380/pull-ci-openshift-kubernetes-master-e2e-aws-serial/1580561826322583552)
/override ci/prow/e2e-aws-serial

**Comment by soltysh** [comment]
we got previous [green e2e-aws-ovn-cgroupsv2](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1380/pull-ci-openshift-kubernetes-master-e2e-aws-ovn-cgroupsv2/1580561825924124672)
/override ci/prow/e2e-aws-ovn-cgroupsv2

**Pull request merged**
