### PR TITLE
Bug 1986504: UPSTREAM 107682: Fix printing control character in kubectl explain

### PR DESCRIPTION
**Pull request by slaskawi**
https://bugzilla.redhat.com/show_bug.cgi?id=1986504

Backport of https://github.com/kubernetes/kubernetes/pull/107682

### CODE REVIEW

**Comment by s-urbaniak** [comment]
/retitle Bug 1986504: UPSTREAM 107682: Fix printing control character in kubectl explain

**Comment by slaskawi** [comment]
Closed in favor of https://github.com/openshift/kubernetes-kubectl/pull/45

**Pull request closed without merging**
