### PR TITLE
Bug 2033751: Kube 1.23.0 rebase

### PR DESCRIPTION
**Pull request by damemi**
Tracking spreadsheet: https://docs.google.com/spreadsheets/d/10KYptJkDB1z8_RYCQVBYDjdTlRfyoXILMa0Fg8tnNlY/edit#gid=396349140

Cleans up https://github.com/openshift/kubernetes/pull/1086

### CODE REVIEW

**Comment by damemi** [comment]
still seeing go 1.17 errors in ci
```
Detected go version: go version go1.16.6 linux/amd64.
Kubernetes requires go1.17.0 or greater.
Please install go1.17.0 or later.
```

do we need to update openshift/release?

**Comment by petr-muller** [comment]
== Triggered 10 `ci-4.10:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-aws-ovn-upgrade
Aggregation ID: `f530c454-61b7-11ec-9df3-74d435fb2dc0`

== Triggered 10 `ci-4.10:e2e-gcp-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-gcp-upgrade
Aggregation ID: `0e382ac8-61b8-11ec-8ad2-74d435fb2dc0`

== Triggered 10 `ci-4.10:e2e-azure-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-azure-ovn-upgrade
Aggregation ID: `23e5963a-61b8-11ec-8365-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade
Aggregation ID: `59f2d2e2-61b8-11ec-948f-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-azure-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade
Aggregation ID: `70ed77c2-61b8-11ec-92aa-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-gcp-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-gcp-ovn-upgrade
Aggregation ID: `86d940ca-61b8-11ec-a46a-74d435fb2dc0`

== Triggered 10 `nightly-4.10:e2e-aws-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-nightly-4.10-e2e-aws-upgrade
Aggregation ID: `bbe40980-61b8-11ec-ab9b-74d435fb2dc0`

**Comment by deads2k** [comment]
aggregated results in https://drive.google.com/drive/folders/1Hg8CiBBcfGkkNDOhO7O2lxe6WK9h6Mc5

not bad considering.

**Comment by mffiedler** [comment]
Tracker bz:  https://bugzilla.redhat.com/show_bug.cgi?id=2034467

**Comment by deads2k** [comment]
1. gcp 4.9 to 4.10 cluster didn't upgrade reliably (historical is 100%, this set was 80%)
2. on several platforms, loki is having trouble with its readiness probe.  In master, this appears to only hit 18% of the time.  You're hitting it more often. You're also seeing high numbers of failures to start the network operator on fresh 4.10 installs
3. aws ovn 4.9 to 4.10 - burn budget again
 
 a few combinations are looking ok.

https://drive.google.com/drive/folders/1molZXo9bMw6S-OgsVEvqQjo1TPOKXmh4

**Comment by wking** [comment]
Retesting once openshift/oc#1003 lands should fix the must-gather and audit-log gather failures we see in this most recent round of `k8s-e2e-*` presubmits.

**Comment by soltysh** [comment]
/override ci/prow/verify-commits 
which is not required to pass during k8s bump since it can't pass due to upstream commits we're bringing
/retest-required

**Comment by wking** [comment]
[Postsubmit][1] just completed, pushing artifacts after openshift/oc#1003 landed.  So I dunno if the running round of presubmits will have picked that up or not, but we can always retest if the retests were launched too soon.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-oc-master-images/1474089465973575680

**Comment by wking** [comment]
Prow seems to have [accepted the override][1], but in GitHub's display, `verify-commits` is still failed.  Looks like [this run][2] launched right around the same time.  Maybe Prow accepted the override for [the previous run][3], but the simultaneous `/retest-required` got [the new run][2] going, and now Prow and GitHub are both upset that that new run failed.  An `/override ci/prow/verify-commits` that's far enough from things that might trigger a new run would probably do it, but also possibly worth waiting until we get the `lgtm` and `approved` labels we'll need to land this.

[1]: https://github.com/openshift/kubernetes/pull/1087#issuecomment-1000474727
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-verify-commits/1474089947127353344
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-verify-commits/1473733804387471360

**Comment by wking** [comment]
[k8s-e2e-gcp][1] failed to install, with one etcd member having trouble:

```
EtcdMembersDegraded: 3 of 4 members are available, ci-op-3884ckgf-a2fce-lblf8-master-0 is unhealthy
level=error msg=StaticPodsDegraded: pod/etcd-ci-op-3884ckgf-a2fce-lblf8-master-2 container "etcd-health-monitor" is waiting: CrashLoopBackOff: back-off 5m0s restarting failed container=etcd-health-monitor pod=etcd-ci-op-3884ckgf-a2fce-lblf8-master-2_openshift-etcd(9c0306c5775fb874111b48c79db0fccd)
```

[CI-search][2] shows it to be somewhat common over the past two days, and not specific to this PR, so try again:

/test k8s-e2e-gcp

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-k8s-e2e-gcp/1474089947056050176
[2]: https://search.ci.openshift.org/?maxAge=48h&type=build-log&search=EtcdMembersDegraded:+3+of+4+members+are+available

**Comment by wking** [comment]
[k8s-e2e-conformance-aws][1] and [k8s-e2e-gcp-serial][2] failed on the must-gather steps again.  Confirming the older `oc`:

```console
oc $ git --no-pager log --oneline --first-parent -2 origin/master
b7970db36 (origin/release-4.11, origin/release-4.10, origin/master, origin/HEAD) Merge pull request #1003 from soltysh/revert_tolerations
0cabd30ee Merge pull request #1002 from wking/fix-ocurred-typo
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-k8s-e2e-conformance-aws/1474089947022495744/artifacts/release/artifacts/release-payload-latest/image-references | jq -r '.spec.tags[] | select(.name == "cli").annotations["io.openshift.build.commit.id"]'
0cabd30eed17bdff46fd270d5c858e3f7970b012
```

So yeah, that's the commit before openshift/oc#1003 landed, because these runs launched before [the `oc` postsubmit completed][3].  Kick off retests:

/test k8s-e2e-conformance-aws
/test k8s-e2e-gcp-serial

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-k8s-e2e-conformance-aws/1474089947022495744
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1087/pull-ci-openshift-kubernetes-master-k8s-e2e-gcp-serial/1474089947093798912
[3]: https://github.com/openshift/kubernetes/pull/1087#issuecomment-1000484795

**Comment by ravisantoshgudimetla** [comment]
Serial tests now passed :)

`: Timed out waiting for the following pods to schedule
Dec 23 23:23:20.007: INFO: openshift-authentication/oauth-openshift-5dfb585cdb-skslx` on aws-conformance. 


https://github.com/kubernetes/kubernetes/blob/0fc6edeb1da8e3975be0cf5fc1b3f6467188de63/test/e2e/scheduling/framework.go#L51

**Comment by petr-muller** [comment]
== Triggered 10 `ci-4.10:e2e-azure-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-azure-ovn-upgrade
Aggregation ID: `54afcbbc-6d81-11ec-bc6c-74d435fb2dc0`

== Triggered 10 `ci-4.10:e2e-gcp-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-gcp-upgrade
Aggregation ID: `3e4bcdb2-6d81-11ec-99a7-74d435fb2dc0`

== Triggered 10 `ci-4.10:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-aws-ovn-upgrade
Aggregation ID: `2718b39e-6d81-11ec-93c5-74d435fb2dc0`

== Triggered 10 `nightly-4.10:e2e-aws-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-nightly-4.10-e2e-aws-upgrade
Aggregation ID: `f8ab0b00-6d81-11ec-9b1b-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-gcp-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-gcp-ovn-upgrade
Aggregation ID: `681a21e2-6d82-11ec-9a01-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-azure-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade
Aggregation ID: `50ced014-6d82-11ec-8d5d-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade
Aggregation ID: `385b1db2-6d82-11ec-94cf-74d435fb2dc0`

**Comment by deads2k** [comment]
the first attempt at aggregation is in https://drive.google.com/drive/folders/1clZ7cqzfl4khFKRuCOwD3RhH4_pMNHrD

however, we're in the process of trying to find a reasonable history to use since we didn't get nightlies produced (not run attempts) from 12/24 to 1/1.  This means we need to re-write the expectations to include the time period when we had results.  https://github.com/openshift/ci-tools/pull/2589 is a likely possibility.  If we extend the window back to 12/17 or so, then I can re-run these.

**Comment by deads2k** [comment]
and https://pr-payload-tests.ci.openshift.org/runs/ci/103ef700-6c78-11ec-8d6b-a78ab7b7b561-3 suggests that there is a vsphere problem.

**Comment by deads2k** [comment]
aws disruption looked weird to me, with blips during the kube-apiserver update

**Comment by deads2k** [comment]
Before the kube update is merged, it must demonstrate
1. at least one successful installation on every variant combination we attempt (gcp, rt, fips, gcp-single-node, metal-ovn, metal-ipv6, etc).  Note that this is not the same as a job run pass and duplicates like metal-serial and metal-e2e-parallel only need to have one successful install between the two of them.
2. at least one successful update for every variant we attempt.  We don't attempt upgrades for every combination, so you only have to confirms the ones we do.  Again, this is not a job run pass.  Just a successful upgrade.
3. passing aggregation (not quite there yet)
4. failed test runs explained as either not failures with PRs to fix the test (the wardle server alert as an example) or as matching historical precedent for a give job (should show up in [testgrid](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.10-informing)).

the "slash payload" commands produce many jobs, but it's still only double digits and the checks requested here ought to only take a few minutes each and it's a "past the post" requirement, so the list gets smaller over time.

Merging before we meet these criteria is a false economy, because we know that we are not going to ship a product that doesn't install or doesn't upgrade or has a clear regression, so if we merge without seeing success we're simply blocking testing for other features on those platform/configuration combinations in master instead of working them out here.

**Comment by petr-muller** [comment]
== Triggered 10 `nightly-4.10:e2e-aws-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-nightly-4.10-e2e-aws-upgrade
Aggregation ID: `5ec1ebe6-6ee7-11ec-baee-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade
Aggregation ID: `783fe19a-6ee7-11ec-916d-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-azure-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade
Aggregation ID: `900da97e-6ee7-11ec-abb5-74d435fb2dc0`

== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-gcp-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-gcp-ovn-upgrade
Aggregation ID: `a5c6f52c-6ee7-11ec-a941-74d435fb2dc0`

== Triggered 10 `ci-4.10:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-aws-ovn-upgrade
Aggregation ID: `c274825c-6ee7-11ec-a8af-74d435fb2dc0`

== Triggered 10 `ci-4.10:e2e-gcp-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-gcp-upgrade
Aggregation ID: `d7b42938-6ee7-11ec-9e41-74d435fb2dc0`

== Triggered 10 `ci-4.10:e2e-azure-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-azure-ovn-upgrade
Aggregation ID: `ecaffc54-6ee7-11ec-916c-74d435fb2dc0`

**Comment by deads2k** [comment]
aggregation summary files are https://drive.google.com/drive/folders/10JJ45kD0YhvwNE6GhE-kGyAM8CN2x4cE

the good news
1. periodic-ci-openshift-release-master-ci-4.10-e2e-aws-ovn-upgrade -- pass
2. periodic-ci-openshift-release-master-ci-4.10-e2e-gcp-upgrade -- pass
3. periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-gcp-ovn-upgrade -- pass
4. periodic-ci-openshift-release-master-nightly-4.10-e2e-aws-upgrade -- pass enough.  disruption is in enough flux that I'd rather attempt to fix it as a blocker bug

the bad news
1. periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade -- kube-api-burn-budget -- pass rate in master 55%, pass rate in PR 0% (not a typo)
2. periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade - kube-api-burn-budget -- pass rate in master 75%, pass rate in PR 11%
3. periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade -- two storage tests -- pass rate in master 100%, pass rate in PR 70%

I suggest re-running `periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade` 10 times to see if you got unlucky with cloud provider access, but I suspect it will be chronic one we merge.

The kube-api-burn-budget looks chronic.  I think it's consistent from before the break.  It's a lot worse after updating to 1.23

**Comment by deads2k** [comment]
Current failures as of 1/7, 1:43PM eastern

**Most notable**
1. periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade -- **kube-api-burn-budget* -- pass rate in master 55%, pass rate in PR 0% (not a typo)**
2. periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade - **kube-api-burn-budget* -- pass rate in master 75%, pass rate in PR 11%**
3. realtime (used by telco) no longer installs -- **pass rate in master 94.7%, pass rate in PR 0% (not a typo)**



**Failing, but less notable**
1. periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade -- two storage tests -- pass rate in master 100%, pass rate in PR 70%
2. new failure mode for single-node serial tests
3. multiple novel failures for azure single node
3. vsphere jobs re-running with a chance of completing install now.  We have no history either way.
3. metal upgrades ovn have not successfully run and no one has diagnosed.  To my eye it appears to fail before the upgrade starts.


* For those who don't know, kube-api-burn-budget measures error rates and excessive latency from the kube-apiserver.  The failures are novel to 1.23.  The failures have not been diagnosed.

**Comment by damemi** [comment]
Just pushed an additional commit https://github.com/jsafrane/kubernetes/commit/3d8da9973804eb3f5752845e93e1967b3148904f which should help with Azure issues

**Comment by wallylewis** [comment]
Current issue summary here - https://coreos.slack.com/archives/C02NZBANL3G/p1641861767193900

**Comment by petr-muller** [comment]
Running 10 iterations: ..........
== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade
Aggregation ID: `01fe5d06-7313-11ec-9789-74d435fb2dc0`

Running 10 iterations: ..........
== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-azure-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade
Aggregation ID: `176301ec-7313-11ec-a625-74d435fb2dc0`

Running 10 iterations: ..........
== Triggered 10 `ci-4.10-upgrade-from-stable-4.9:e2e-gcp-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-upgrade-from-stable-4.9-e2e-gcp-ovn-upgrade
Aggregation ID: `2c80508e-7313-11ec-9e42-74d435fb2dc0`

Running 10 iterations: ..........
== Triggered 10 `ci-4.10:e2e-aws-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-aws-ovn-upgrade
Aggregation ID: `b1fc3a94-7312-11ec-bbd1-74d435fb2dc0`

Running 10 iterations: ..........
== Triggered 10 `ci-4.10:e2e-gcp-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-gcp-upgrade
Aggregation ID: `c6dcc47e-7312-11ec-a079-74d435fb2dc0`

Running 10 iterations: ..........
== Triggered 10 `ci-4.10:e2e-azure-ovn-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-ci-4.10-e2e-azure-ovn-upgrade
Aggregation ID: `dbdaae68-7312-11ec-839c-74d435fb2dc0`

Running 10 iterations: ..........
== Triggered 10 `nightly-4.10:e2e-aws-upgrade` iterations
URL:             https://prow.ci.openshift.org/?job=kubernetes-1087-nightly-4.10-e2e-aws-upgrade
Aggregation ID: `2ac7e8b6-7312-11ec-8a5d-74d435fb2dc0`

**Comment by soltysh** [comment]
/override ci/prow/verify-commits 
this is never going to pass on a rebase PR
/remove-label backports/unvalidated-commits
/label backports/validated-commits

/lgtm
/approve

**Comment by soltysh** [comment]
/override ci/prow/e2e-gcp 
There seems to be a problem with building machine-os-content image which is only relevant in this repository, because all the rest relies on the image provided by the release team. I'm working on fixing this problem in https://github.com/openshift/kubernetes/pull/1109

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-downgrade
it's optional job and we have proof of past successes run

**Pull request merged**
