### PR TITLE
Bug 1952917: UPSTREAM: 100228: For LoadBalancer Service type don't create a HNS policy for empty or invalid external loadbalancer IP

### PR DESCRIPTION
**Pull request by aravindhp**

### CODE REVIEW

**Comment by aravindhp** [comment]
/retitle Bug 1952917: UPSTREAM: 100228: For LoadBalancer Service type don't create a HNS policy for empty or invalid external loadbalancer IP

**Comment by sttts** [comment]
Upstream merged.

/approve

**Pull request merged**
