### PR TITLE
UPSTREAM: 96984: APF e2e: wait for steady state before proceeding

### PR DESCRIPTION
**Pull request by tkashem**
Pick both:
- https://github.com/kubernetes/kubernetes/pull/96984 
- https://github.com/kubernetes/kubernetes/pull/96966 

Which issue(s) this PR fixes:
Related to #96803 and #96893

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Noticing a lot of failures in our CI 

https://search.ci.openshift.org/?search=API+priority+and+fairness+should+ensure+that+requests+can+be+classified+by+testing+flow-schemas%2Fpriority-levels&maxAge=48h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job

I think it is worth merging in master unless we think it makes 1.21 rebase hard later.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
