### PR TITLE
OCPBUGS-18285,OCPBUGS-19479: Update to Kubernetes 1.27.6

### PR DESCRIPTION
**Pull request by bertinatto**
/assign @soltysh

### CODE REVIEW

**Comment by soltysh** [comment]
This mostly lgtm, there's a question for @damdo about https://github.com/openshift/kubernetes/pull/1709/commits/3f029a204265a44248f65428ea8162ec80fb31e8#diff-c94e623481fb506d90b33e51830aabc3e8829a308a70dc9e4ebd0f31d436edc1L860 this patch resolution and we're waiting for payload results.

**Comment by soltysh** [comment]
Confirmed with both @JoelSpeed and @damdo this can be safely dropped.

**Comment by sdodson** [comment]
/retitle OCPBUGS-18285, OCPBUGS-14605: Update to Kubernetes 1.27.6

**Comment by sdodson** [comment]
/retitle OCPBUGS-18285,OCPBUGS-19479: Update to Kubernetes 1.27.6

**Review by soltysh — APPROVED** [review]
Both CI and nightly paylaod are green except for metal, which looking at release status is a wider problem. 
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
this never passes on k8s bump

**Comment by soltysh** [comment]
The 504 Gateway issue is a known problem tracked in https://issues.redhat.com/browse/OCPBUGS-18999 and we also got a green azure-ovn-upgrade in https://pr-payload-tests.ci.openshift.org/runs/ci/2fa51ea0-5798-11ee-8dd2-90e5dbb2a705-1 so I'm confident this is not broken.
/override ci/prow/e2e-azure-ovn-upgrade

**Pull request merged**
