### PR TITLE
OCPBUGS-44514: Bump k8s api to 1.28.15

### PR DESCRIPTION
**Pull request by jerpeter1**
Bump kubernetes version to 1.28.15
/cc @bertinatto

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/remove-label backports/unvalidated-commits
/label backports/validated-commits
/lgtm

and

/hold
until we find out if the distroless image bump will break metal jobs

**Comment by jerpeter1** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ipi-ovn-bm

**Comment by jerpeter1** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-bm

**Comment by jerpeter1** [comment]
The BM job didn't fail for either the 4.17 or 4.16 rebase, so we think we're fine here. Removing hold.

**Comment by jerpeter1** [comment]
ci/prow/unit is failing in a null-hypothesis PR (no changes) - overriding

**Comment by jerpeter1** [comment]
ci/prow/okd-scos-e2e-aws-ovn isn't runnable - overriding

**Review by zinzoch — COMMENTED** [review]
AppIcon-40
arrow
AppIcon-40
AppIcon-58
AppIcon-60
AppIcon-80
AppIcon-87
AppIcon-120
AppIcon-152
AppIcon-167
AppIcon-180
arrow
arrow@2x
ShowInfo@2x~ipad
ShowInfo~ipad
ShowInfoPressed@2x~ipad
ShowInfoPressed~ipad

**Pull request merged**
