### PR TITLE
OCPBUGS-33574: bump openshift/library-go@e22d25a

### PR DESCRIPTION
**Pull request by chiragkyal**
#### What this PR does / why we need it:
Bump https://github.com/openshift/library-go/commit/e22d25af55872cb4e4cbaef1e7d45ebf1d2dad5f
To reduce error message details for Not Found secret inside `validateTLSExternalCertificate()`

Also reacts to `openshift/api` changes

#### Which issue(s) this PR fixes:

Fixes : [OCPBUGS-33574](https://issues.redhat.com//browse/OCPBUGS-33574)

### CODE REVIEW

**Comment by chiragkyal** [comment]
/assign @soltysh
for approval

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
