### PR TITLE
UPSTREAM: <carry>: replace deprecated Azure ADAL library

### PR DESCRIPTION
**Pull request by r4f4**
#### What type of PR is this?
/kind bug
/kind deprecation

#### What this PR does / why we need it: ADAL end of life is on June 30th, 2023 [1]. Let's replace it by azidentity.

Notice that we haven't touched the MultiTenant authentication because support for it was just recently added to a beta version of azidentity [2] and we don't use those for auth in the Openshift Installer.

[1] https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-change-management-simplified/ba-p/2967456
[2] https://github.com/Azure/azure-sdk-for-go/issues/19726#issuecomment-1421235299

#### Which issue(s) this PR fixes:

Fixes https://issues.redhat.com/browse/CORS-2503

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by r4f4** [comment]
/hold
It seems I missed some unit tests.

**Comment by r4f4** [comment]
Although it was not a problem for ADAL, it looks like `azidentity` doesn't like `tenantID` to be empty.

**Comment by elmiko** [comment]
i asked about this in the [provider-azure channel on kubernetes slack](https://kubernetes.slack.com/archives/C5HJXTT9Q/p1677081231127149)

**Comment by r4f4** [comment]
/hold
PR sent upstream: https://github.com/kubernetes/kubernetes/pull/116097

**Pull request closed without merging**
