### PR TITLE
[4.14] OCPBUGS-15531: UPSTREAM: 120786: change rolling update logic to exclude sunsetting nodes

### PR DESCRIPTION
**Pull request by atiratree**

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by atiratree** [comment]
```
levee: test/integration/daemonset/daemonset_test.go:1229:17: undefined: intstr.FromInt32
```

changed the test to reference an older `intstr.FromInt` instead

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-fips
this is being worked on in parallel

**Pull request merged**
