### PR TITLE
OCPBUGS-34373: Bump library-go to fix routes/custom-host permission for externalCertificate

### PR DESCRIPTION
**Pull request by chiragkyal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Bumps openshift/library-go@0064ad7 and fixes the routes/custom-host permission for `externalCertificate`

#### Which issue(s) this PR fixes:

Fixes # https://issues.redhat.com/browse/OCPBUGS-34373

### CODE REVIEW

**Comment by Miciah** [comment]
Thanks!
/approve
/lgtm

**Review by bertinatto — COMMENTED** [review]
/remove-label backports/unvalidated-commits
/label backports/validated-commits
/approve

**Pull request merged**
