### PR TITLE
BUG 1868634: UPSTREAM: 93189: Fix a bug whereby reusable CPUs and devices were not being honored

### PR DESCRIPTION
**Pull request by cynepco3hahue**
xref https://bugzilla.redhat.com/show_bug.cgi?id=1868634
xref kubernetes#93189

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@derekwaynecarr @sjenning

**Comment by sjenning** [comment]
This went into upstream 1.19-rc3 and we'll get it when we do the final 4.6 rebase on the now released kube 1.19

**Pull request closed without merging**
