### PR TITLE
Bug 1841119: UPSTREAM: <carry>: kube-controller-manager: allow running bare kube-controller-manager

### PR DESCRIPTION
**Pull request by soltysh**
Needs https://github.com/openshift/cluster-kube-controller-manager-operator/pull/471 first. 
/hold

### CODE REVIEW

**Comment by soltysh** [comment]
/assign @deads2k @tnozicka
for review
although this will fail until we land https://github.com/openshift/cluster-kube-controller-manager-operator/pull/471

**Comment by soltysh** [comment]
This is waiting for https://github.com/openshift/cluster-kube-controller-manager-operator/pull/492 to merge

**Review by tnozicka — COMMENTED** [review]
nit, lgtm otherwise

**Review by tnozicka — COMMENTED** [review]
/lgtm

**Comment by soltysh** [comment]
Usual flakes
/retest

**Pull request merged**
