### PR TITLE
Bug 1887748: [4.6] UPSTREAM: 95245: Mask Ceph RBD adminSecrets in logs when logLevel >= 4

### PR DESCRIPTION
**Pull request by jsafrane**
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1887292
https://github.com/kubernetes/kubernetes/pull/95245
@openshift/storage 

/hold
for 4.6.z to open

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by sdodson** [comment]
Putting a temporary hold on things to prioritize items that fix test flakes while we're hitting AWS quota limits. I'll clear this later today.
/hold

**Comment by sdodson** [comment]
@jsafrane PTAL, I know the vsphere job is failing on infra issues, I've filed a bug for the monitoring crashlooping pods but I haven't looked into the others
https://bugzilla.redhat.com/show_bug.cgi?id=1905109

**Pull request merged**
