### PR TITLE
Bug 2040793: Fix ordering issues with snapshot e2e

### PR DESCRIPTION
**Pull request by gnufied**
Fix snapshot e2e failures

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2040793

### CODE REVIEW

**Comment by dobsonj** [comment]
/lgtm
/bugzilla refresh

/assign @mfojtik
for approval

**Comment by gnufied** [comment]
One upstream PR is already backported - https://github.com/kubernetes/kubernetes/pull/107341 and other one is pending https://github.com/kubernetes/kubernetes/pull/107566

**Review by soltysh — APPROVED** [review]
/approve
/retest

**Comment by gnufied** [comment]
The failure in serial tests have nothing to do with change as far as I can tell. 

For instance:

```
E0121 17:14:30.598203      75 portforward.go:340] error creating error stream for port 3100 -> 3100: Timeout occured
{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 10m0s timeout","severity":"error","time":"2022-01-21T17:23:55Z"}
{"component":"entrypoint","error":"os: process already finished","file":"prow/entrypoint/run.go:243","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not interrupt process after timeout","severity":"error","time":"2022-01-21T17:23:55Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2022-01-21T17:24:10Z"}
{"component":"entrypoint","error":"os: process already finished","file":"prow/entrypoint/run.go:257","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Could not kill process after grace period","severity":"error","time":"2022-01-21T17:24:10Z"}
{"component":"entrypoint","error":"process timed out","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-01-21T17:24:10Z"}
error: failed to execute wrapped command: exit status 127
```

And the second one is scheduler e2e failure. Both failures can not be caused by snapshot ordering changes proposed here. These are just e2e change which are reordering snapshot, restore and check file content to ensure we have a valid snapshot.

**Pull request merged**
