### PR TITLE
UPSTREAM: 89885: revert: allow to read openstack cloud provider config from a secret

### PR DESCRIPTION
**Pull request by mandre**
This reverts commit 452539b3055b90b3824bfc92268ca256e4532278 as it is no longer needed after OCP 4.12, where the OpenStack platform switched to the out-of-tree cloud provider.

This patch brings back the downstream changes that were introduced to allow reading openstack cloud provider config from a secret. They are available in release-4.4, but were reverted in master with https://github.com/openshift/origin/pull/24719

This change includes:

- Ability to read metadata values for kubelet. Since the service does not have access to the secret to read the configuration, but it needs data to download (e.g. hostname or flavor), we are trying to get it from the metadata server.

- Deprecation of kubeConfig parameter. Now we read the file that was provided with --kubeconfig option.

Origin-commit: f95edc26155a29769b3c5b80c03755a01a87b5fc

UPSTREAM: 89885: legacy-cloud-provider/openstack: include / prefix in instance ID output

When we want to read an instance ID from the metadata service, cloud provider doesn't include "/" prefix, which is required for successful parsing of provider the ID later.
This commit adds the missing "/" prefix to the output.

UPSTREAM: 89885: SQUASH: Fix Cinder provisioning crashing on nil cloud provider

OpenStack cloud provider must not use nil when provisioning a Cinder volume.

UPSTREAM: 89885: SQUASH: Report OpenStack cloud initialization errors

openshift-rebase(v1.24):source=dbe70e455ee

UPSTREAM: <carry>: Set informer for openstack

Set informer for the openstack cloud provider to ensure it is properly initialized when reading config from a secret.

Upstream 89885 was closed in favor of 96750.

Co-authored-by: Hemant Kumar <hekumar@redhat.com>

openshift-rebase(v1.24):source=d7ecbd903e2

UPSTREAM: 89885: SQUASH: Retry fetching clouds.conf

The OpenStack secret is not guaranteed to be present at the time kube-controller-manager is initialised.

Co-authored-by: Martin André <m.andre@redhat.com>
Co-authored-by: Pierre Prinetti <pierreprinetti@redhat.com>

openshift-rebase(v1.24):source=8bc9dd29ef0

UPSTREAM: 89885: Fix panic in openstack.InstanceExistsByProviderID()

... when provider is uninitialised.

This is a fix to downstream-only code which was originally proposed upstream as https://github.com/kubernetes/kubernetes/pull/89885 but did not merge. It is therefore not relevant upstream. Given that we will replace the openstack legacy cloud provider in 4.12 we will not re-propose #89885 or this fix to it.

Causes all openstack.Instances() methods which require more than the local metadata service to return NotImplemented instead of crashing if the provider is not initialised.

### CODE REVIEW

**Comment by mandre** [comment]
/hold

This might be too soon to revert the carry patch. [KCM enters a crash loop](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1389/pull-ci-openshift-kubernetes-master-e2e-openstack/1580800049804218368/artifacts/e2e-openstack/gather-extra/artifacts/pods.json):
```
I1014 08:47:40.838002       1 openstack.go:266] Creating kubernetes API client.
W1014 08:47:40.838022       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1014 08:47:40.838056       1 client_config.go:622] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
F1014 08:47:40.838266       1 controllermanager.go:245] error building controller context: cloud provider could not be initialized: could not init cloud provider \"openstack\": failed to get kubernetes client: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable",
```

**Comment by mandre** [comment]
We need https://github.com/openshift/library-go/pull/1443 that we'll revendor in KCMO.

**Comment by JoelSpeed** [comment]
Do we need to fix the vendor verify before this will pass the E2E?

**Comment by mandre** [comment]
/close
This is no longer needed since the 1.26 rebase.

**Pull request closed without merging**
