### PR TITLE
Bug 1942630: UPSTREAM: 96789: Choosing the right source VIP for local endpoints

### PR DESCRIPTION
**Pull request by sebsoto**
This fixes an issue where LoadBalancers would stop directing traffic to Windows pods, when multiple pods were behind the LoadBalancer.

### CODE REVIEW

**Comment by sttts** [comment]
/hold

this branch is not intended for kube-proxy.

**Comment by sttts** [comment]
As agreed on Slack, WMCO will move away in 4.8 from vendoring the master and release branches of this repository. They are not meant to be consumed by other components and might break at any time for their use-case.

For 4.6, we will accept this carry to keep the builds working.

/hold cancel

**Comment by deads2k** [comment]
Jira story here: https://issues.redhat.com/browse/WINC-593

**Pull request merged**
