### PR TITLE
kube-proxy: clear conntrack entries after rules are in place

### PR DESCRIPTION
**Pull request by smarterclayton**
Clear conntrack entries for UDP NodePorts,
this has to be done AFTER the iptables rules are programmed.
It can happen that traffic to the NodePort hits the host before
the iptables rules are programmed this will create an stale entry
in conntrack that will blackhole the traffic, so we need to
clear it ONLY when the service has endpoints.

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by smarterclayton** [comment]
To run network stress you'll need to hit the bot up

**Comment by aojea** [comment]
> To run network stress you'll need to hit the bot up

:+1: I was able to use the bot, 2/2 ok so far

**Comment by aojea** [comment]
by the way, upstream already merged https://github.com/kubernetes/kubernetes/pull/98305

**Comment by aojea** [comment]
backported the upstream fix to 1.20 https://github.com/kubernetes/kubernetes/pull/99017
Do we need it in previous "upstream" releases?
Is this going to be picked automatically in openshift soon or do I need to submit the backports here too?

**Pull request closed without merging**
