### PR TITLE
OCPBUGS-2774: UPSTREAM: 112807 Fix Load balancer services with xTP local

### PR DESCRIPTION
**Pull request by JoelSpeed**
This is a blocker bug that was introduced by the K8s 1.25 rebase. The bug is present in all Kube versions upstream 1.25.0 <= x < 1.25.3. Since we are currently based on 1.25.2 this has not been included yet.

The result of this bug is that, for any LoadBalancer service (such as that used by the default router), that has an `externalTrafficPolicy: local`, the load balancer node membership is never updated after the service is created. As MachineSets scale up and down, this would result in a loss of ingress.

Links to the upstream issue in the bug.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by JoelSpeed** [comment]
I've manually verified this by building a cluster from this PR and scaling up and down machinesets a few times, I can see the new machines and old machines being added and removed as expected

**Pull request merged**
