### PR TITLE
Bug 1900630: 4.6: Update from Kubernetes 1.19.0 to 1.19.4

### PR DESCRIPTION
**Pull request by sttts**
This PR updates the base Kubernetes version from 1.19.0 to 1.19.4.

### CODE REVIEW

**Review by tnozicka — APPROVED** [review]

**Comment by tnozicka** [comment]
needs bumping kube version in the dockerfile 
https://github.com/openshift/kubernetes/blob/9f84db336d1a77cba52684ecb51bfb197e9b4533/openshift-hack/images/hyperkube/Dockerfile.rhel#L16
(this triggers additional upgrade tests

**Comment by mfojtik** [comment]
/lgtm
/approve
/override ci/prow/verify-commits

Manually overrode the valid-bug as it does not make sense in minor rebase bump.

**Comment by ecordell** [comment]
This is just waiting for a BZ, otherwise good to go

**Comment by sdodson** [comment]
Lets wait until we've referenced a bug in the title before we override bugzilla/valid-bug.

**Comment by sdodson** [comment]
/hold
These do not look like flakes, at least verify-commits seems persistent but feel free to clear the hold if I'm wrong.

**Comment by tnozicka** [comment]
> These do not look like flakes, at least verify-commits seems persistent but feel free to clear the hold if I'm wrong.
rebase will never pass verify-commits by nature
/override verify-commits

**Comment by mfojtik** [comment]
/hold cancel

overriding valid-bug as this is minor kubernetes update that won't have equivalent in master branch. this is described in patch manager doc as exception.

**Comment by sdodson** [comment]
Discussed on slack that we'd remove `cherry-pick-approved` until the merge window opens.

**Comment by mfojtik** [comment]
/override ci/prow/e2e-aws-ovn

This won't pass without quay.io and it was green before. The test is very flaky and OVN team will be notified to de-flake it. The kube bump certainly does not cause this flakiness.

**Pull request merged**
