### PR TITLE
SDN-5457: Add Dockerfile for standalone kube-proxy image

### PR DESCRIPTION
**Pull request by danwinship**
OpenShift ships a `kube-proxy` image in the release payload for use by third-party CNI plugins (eg, Calico). In the past, this was built out of `openshift/sdn`, but since openshift-sdn is no longer part of OpenShift as of 4.17, this no longer makes a lot of sense.

In the future we do not expect to ever have any carry patches against kube-proxy, so @deads2k agreed it makes sense to just build our kube-proxy images out of `openshift/kubernetes` along with the other upstream stuff.

This adds a Dockerfile for that; the top half of the Dockerfile is a simplified version of the hyperkube Dockerfile, and the bottom half comes from [the existing kube-proxy Dockerfile in openshift-sdn](https://github.com/openshift/sdn/blob/release-4.17/images/kube-proxy/Dockerfile.rhel). (The OWNERS file is from cluster-network-operator, since sdn's OWNERS file had gotten out-of-date.)

AFAIK, there's no way to test this PR until after we also update `openshift/release`, right? Though, related, `openshift-hack/lib/constants.sh` has `OS_ALL_IMAGES` and `os::build::images()` with "all images in this repo", but I couldn't find anything that actually _uses_ them? (So I didn't add the kube-proxy image to those. Should I?)

Also, the hyperkube Dockerfile adds a `io.openshift.build.versions="kubernetes=1.30.3"` label to the image, and according to `REBASE.openshift.md`, the label is "among other things, used by ART to inject appropriate version of kubernetes during build process"... I wasn't sure if I should have a label on the kube-proxy image too (for the "other things"?). For now I didn't add it.

----

The last bit is CI... So, up until 4.16, we did not explicitly CI (or QE) this image, but the kube-proxy image was built from the same source tree as the openshift-sdn image, so we kinda sorta almost did? In 4.17 currently we do not have CI for the kube-proxy image and also aren't testing openshift-sdn...

Doing "proper" e2e testing of the kube-proxy image within OCP is not really possible, because the image is only used in non-RH-supported configurations; we would have to write a CI workflow to install an OCP cluster with Calico or flannel or something (and maintain it forever).

However, we know that the kube-proxy image must at least _almost_ work, since it's based on working upstream code, and we aren't applying any kube-proxy-specific patches, and `ci/prow/unit` would have failed if the kube-proxy unit tests failed. So if we just test that the `kube-proxy` binary in the image is able to start up without crashing, and eventually reports itself healthy, and has written out some vaguely-plausible-looking iptables/nftables rules when it does, then that seems good enough to be confident that it works. The `test-kube-proxy.sh` script in this PR does just that; I [tested it against the sdn kube-proxy build](https://github.com/openshift/release/pull/57995) to make sure it works. After this PR merges, I will file a PR against openshift/release to add another step to the `openshift-kubernetes-e2e-test` workflow used by `k8s-e2e-gcp-ovn` to run this test as well. (And to build and promote the `kube-proxy` image out of kubernetes rather than sdn.)

### CODE REVIEW

**Comment by danwinship** [comment]
Update: grumble grumble. Apparently some customers were depending on one of our local patches even when using standalone kube-proxy (OCPBUGS-43764) so I've pulled that in. Long term, this should be able to go away because `TrafficDistribution` should eventually support node-local topology...

**Comment by martinkennelly** [comment]
code looks good to me

**Comment by danwinship** [comment]
(jinx! I saw that it needed jira/valid-reference and so created an epic for it.)

**Pull request merged**
