### PR TITLE
OCPBUGS-20097: Migrate tools image to RHEL9

### PR DESCRIPTION
**Pull request by soltysh**
/assign @ardaguclu

### CODE REVIEW

**Comment by ardaguclu** [comment]
/lgtm
/hold
Until CI is green

**Comment by soltysh** [comment]
With https://github.com/openshift/release/pull/51253 in
/retest

**Comment by soltysh** [comment]
We got sufficient signal, that this change is legit, so I'm dropping the hold.
/hold cancel

**Pull request merged**
