### PR TITLE
UPSTREAM: <carry>: (squash) Add detail to rebase doc

### PR DESCRIPTION
**Pull request by marun**
- Add new section 'Maintaining this document'
- Move checklist above the instructions to emphasize their importance
- Add new section 'Reacting to new commits'
- Mention that generated changes in carries should be dropped

### CODE REVIEW

**Comment by soltysh** [comment]
/assign @tnozicka 
Since he just when through the hassle so he has it fresh in his head

**Comment by marun** [comment]
This change was a checklist item on the rebase, but it didn't get added before merge.

**Pull request merged**
