### PR TITLE
Bug 1908389: UPSTREAM: <drop>: Revert Azure provider 1.20 breaking changes

### PR DESCRIPTION
**Pull request by sgreene570**
This commit reverts all commits in `staging/src/k8s.io/legacy-cloud-provider/azure` up to and including https://github.com/openshift/kubernetes/commit/7964e302b0273e737a06e49633df18f4a4e0a1f9#diff-40b419248aa82dcd4e2c80408a5352ed0d92210ef962ebc43b9079a959e61b52, skipping https://github.com/openshift/kubernetes/commit/819ff9b0870506b889e156adc5e66e314f8d148e#diff-40b419248aa82dcd4e2c80408a5352ed0d92210ef962ebc43b9079a959e61b52.

See https://github.com/openshift/kubernetes/commits/master?before=87544c5b79d20e7ea1f973dec6910870d2c2a08a+35&branch=master&path%5B%5D=staging&path%5B%5D=src&path%5B%5D=k8s.io&path%5B%5D=legacy-cloud-providers&path%5B%5D=azure.

Full list of reverted (and squashed) commits:
```
ae1e452e7d6d48c07becceac1bb5d894be515044
0d38026687cb3f5dbed87563804f0bb0bcee8ad0
2e7dd8d850cf97eef3664848ba7d335939557dec
b33715711ed4d77f540bb031cc004d6694a8a361
5077ff79d978cc9b4bddbb5d856ec4d4230ec16b
7c4ae183e0bfa07a1f172d9b90e0d0986c903019
d17621bee697074b1ee33d03cf9343d4518ab5f7
09112ed1f423f5666a82e7102685ac550d6e672d
667b2be621de91a4254af6499ce742332c981b76
b192630522f4167302748409f4e9f710202fe98c
e88be95471d0813a9bee8f391d85f8edbf9d4e39
6c7132b2846d609d0c9ef4937f411bbf2150a0d7
ecdc1ba57cc87c38ee0c7f6d79f2ccefb7628dfa
87a4805ba47524b5a283f222f2333ce12dae75c6
46593daf2276dd42a6fadab70aa6268e970804ac
748ae54ec01c8a1588d85cfb0444dcdc9d1b6ae3
ede9d8ce12f059ab2f6d0453fd0925c3dae1296c
7964e302b0273e737a06e49633df18f4a4e0a1f9
```

### CODE REVIEW

**Comment by wking** [comment]
Calling in the [`always_run: false` job][1]:

/test e2e-azure

[1]: https://github.com/openshift/release/blob/3d47c526c2ea332d1bbdb6e77897d5b159471ab4/ci-operator/jobs/openshift/kubernetes/openshift-kubernetes-master-presubmits.yaml#L849-L863

**Comment by sgreene570** [comment]
`error: error creating buildah builder: Error initializing ....openshift.org/v2/": dial tcp 3.220.81.240:443: i/o timeout`
/test e2e-azure

**Review by wking — APPROVED** [review]
[Passed][1].

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/496/pull-ci-openshift-kubernetes-master-e2e-azure/1340052595581915136

**Comment by deads2k** [comment]
/hold

I do not think this is an appropriate solution.  Reverting 18 upstream commits, with impacts across multiple cloud providers isn't the correct way to handle this situation.  Let's find and fix the narrow problem we have, not revert from the reality of the code that is present.

**Comment by deads2k** [comment]
> /hold
> 
> I do not think this is an appropriate solution. Reverting 18 upstream commits, with impacts across multiple cloud providers isn't the correct way to handle this situation. Let's find and fix the narrow problem we have, not revert from the reality of the code that is present.

https://github.com/openshift/kubernetes/pull/498 demonstrates a possibility.

/close

**Pull request closed without merging**
