### PR TITLE
UPSTREAM: 97295: Fix staticcheck in test/integration/{examples,framework}

### PR DESCRIPTION
**Pull request by cynepco3hahue**
(cherry picked from commit 101cdbf932c9728ce164995b637fac84b5618e1b)

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by mfojtik** [comment]
@mrunalp @rphillips @cynepco3hahue this PR is going to be reverted because it conflicts with the rebase.

Next time please consult with the API team (#forum-apiserver) before manually adding the approved label in this repo.

**Comment by soltysh** [comment]
@mrunalp @rphillips this is minor PR addressing problem which will be brought with newer k8s bump. None of DOWNSTREAM_OWNERS approved this PR which is unacceptable. Please make sure in the future this does not happen and the necessary people

**Comment by cynepco3hahue** [comment]
@mfojtik @soltysh Sorry for the mess, I wasn't aware of the soon rebase on top of 1.21 and we had a lot of PRs that failed because of the verify job.
Another question, how can we prevent the merge via prow-bot without manually checking DOWNSTREAM_OWNERS?

**Comment by soltysh** [comment]
w/o manual label from @mrunalp this wouldn't merge, so if you follow the process and allow merges only based on manual tags everything will work just fine.

**Comment by soltysh** [comment]
Also, if in doubt always feel free to reach out to folks mentioned in DOWNSTREAM_OWNERS directly on slack.

**Comment by cynepco3hahue** [comment]
@soltysh I see, a lot of thanks for the clarification, and indeed next time I will reach `#forum-apiserver` first.

**Pull request merged**
