### PR TITLE
UPSTREAM: 117349: OCPBUGS-19431: Bump lumberjack.v2 v2.0.0 -> v2.2.1

### PR DESCRIPTION
**Pull request by vrutkovs**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Update lumberjack.v2 dependency. In upstream its a regular dep bump, but it fixes an Openshift bug - termination log file would be created with 0600 permission and stay persistent, as we use `lumberjack` in `cmd/watch-termination`.

#### Which issue(s) this PR fixes:

Fixes OCPBUGS-11856

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by dgrisonnet — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve
/label acknowledge-critical-fixes-only

**Comment by soltysh** [comment]
/hold 
we're pick this up in the main k8s bump

**Comment by soltysh** [comment]
https://github.com/openshift/kubernetes/pull/1646 for reference

**Comment by vrutkovs** [comment]
ah, I created this to make it land in 4.14, long before branching.

I can retarget to 4.14 once bug for 4.15 is merged and verified

**Comment by wangke19** [comment]
Pre-merge verified the PR, got the expected results, detail see https://issues.redhat.com/browse/OCPBUGS-19431?focusedId=23119052&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23119052
 /label qe-approved

**Comment by p0lyn0mial** [comment]
@vrutkovs is this behaviour of lumberjack library documented somewhere ? Since the version of lumberjack differs from upstream how can we ensure that on the "next" bump the version will be increased ? does this pr fix also already existing clusters ?

**Comment by p0lyn0mial** [comment]
@vrutkovs in more recent releases of the fork we maintain a [patch](https://github.com/openshift/kubernetes/commit/2a308bde5da782bb4e1d977b6c3d2047bd09f08f) that addresses the issue. If the behaviour of the library is documented and can be trusted then It seems [that releases that have the correct version](https://github.com/openshift/kubernetes/blob/master/go.mod#L98C3-L98C41) of lumberjack could remove the patch. WDYT?

**Comment by vrutkovs** [comment]
>is this behaviour of lumberjack library documented somewhere ?

Yes - https://github.com/natefinch/lumberjack/issues/120. Oddly enough its not closed upstream

> Since the version of lumberjack differs from upstream how can we ensure that on the "next" bump the version will be increased ?

Not sure I understand the question - how can we ensure that micro bump won't overwrite lumberjack version? That should be taken care of during rebase

>does this pr fix also already existing clusters ?

Yes, files will be updated on rotation.

>It seems [that releases that have the correct version](https://github.com/openshift/kubernetes/blob/master/go.mod?rgh-link-date=2024-01-04T07%3A35%3A59Z#L98C3-L98C41) of lumberjack could remove the patch

Yes, I think that needs to be done too

**Comment by p0lyn0mial** [comment]
>> Since the version of lumberjack differs from upstream how can we ensure that on the "next" bump the version will be increased ?

>Not sure I understand the question - how can we ensure that micro bump won't overwrite lumberjack version? That should be taken care of during rebase

Yeah, I think it depends on how we handle minor bumps. If the process is to take the upstream branch and apply our patches, then we can easily skip this PR.

>> It seems [that releases that have the correct version](https://github.com/openshift/kubernetes/blob/master/go.mod?rgh-link-date=2024-01-04T07%3A35%3A59Z#L98C3-L98C41) of lumberjack could remove the patch

> Yes, I think that needs to be done too

Would you be open to addressing this issue ?

**Comment by vrutkovs** [comment]
> If the process is to take the upstream branch and apply our patches, then we can easily skip this PR.

I think we're safe on that - a merge commit is created - https://github.com/openshift/kubernetes/blob/master/REBASE.openshift.md#updating-with-git-merge, so a revert would be noticed.

Created https://github.com/openshift/kubernetes/pull/1841 to revert the carry in 4.15+

**Comment by p0lyn0mial** [comment]
>> is this behaviour of lumberjack library documented somewhere ?

>Yes - https://github.com/natefinch/lumberjack/issues/120. Oddly enough its not closed upstream

Also there are no references to PR(s) that changed the behaviour. Do we want to take changes ? I would feel better if this behaviour is documented and tested. How did you arrive at this solution ?

**Comment by p0lyn0mial** [comment]
@wangke19 hey, did you test the fix on an already existing cluster ? I'm asking because the issue Vadim referenced is still open and it is not clear whether it works. Thanks.

**Comment by vrutkovs** [comment]
This was fixed in https://github.com/natefinch/lumberjack/pull/83, previous attempt was to merge this in https://github.com/openshift/cluster-kube-apiserver-operator/pull/385

**Pull request merged**
