### PR TITLE
NO-JIRA: UPSTREAM:<drop>: bump openshift/library-go@4d55b6d

### PR DESCRIPTION
**Pull request by sohankunkerkar**
To fix the safe sysctls list in OCP.

#### Which issue(s) this PR fixes:

Addresses: https://issues.redhat.com/browse/OCPBUGS-38149

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
Please use `hack/pin-dependency.sh` and `hack/update-vendor.sh` instead. This will update a few more files. Also, please amend your commit message to make it a `<drop>` instead.

Finally, a small nit: please update the title with the correct dependency.

**Comment by sohankunkerkar** [comment]
> Please use `hack/pin-dependency.sh` and `hack/update-vendor.sh` instead. This will update a few more files. Also, please amend your commit message to make it a `<drop>` instead.
> 
> Finally, a small nit: please update the title with the correct dependency.

Thanks!
I have addressed your comments in the latest push.
@p0lyn0mial @bertinatto PTAL

**Comment by p0lyn0mial** [comment]
LGTM

I will defer to @bertinatto for tagging it.

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
