### PR TITLE
OCPBUGS-32934: UPSTREAM: 124795: e2e: DaemonSet maxSurge test should account for terminated pods

### PR DESCRIPTION
**Pull request by atiratree**
that are terminated by the test

### CODE REVIEW

**Comment by atiratree** [comment]
serial tests did not show failure or flakiness of `Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate`

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
