### PR TITLE
k8s 1.25.0

### PR DESCRIPTION
**Pull request by soltysh**
Picks: https://docs.google.com/spreadsheets/d/10KYptJkDB1z8_RYCQVBYDjdTlRfyoXILMa0Fg8tnNlY/edit#gid=1852049954
Test tracker: https://docs.google.com/spreadsheets/d/1KuC8QAmQd2LiCMk0EVBxss97V0-UNtFM8vVEqPYWCqs/edit#gid=1312057609

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
running payload tests were cancelled bc of repush so guess I should kick these off again?
/payload 4.12 ci blocking
/payload 4.12 ci informing
/payload 4.12 nightly blocking
/payload 4.12 nightly informing

**Comment by kikisdeliveryservice** [comment]
retrying conformance

/test k8s-e2e-conformance-aws

**Comment by kikisdeliveryservice** [comment]
ok I'm rerunning payload tests we got the `e2e-azure-sdn-techpreview` test fixed and hopefully some of the invalid test runs that had ci problems work out.

here goes nothing! :crossed_fingers: 

/payload 4.12 ci blocking
/payload 4.12 ci informing
/payload 4.12 nightly blocking
/payload 4.12 nightly informing

**Comment by kikisdeliveryservice** [comment]
Overall this is a weird set of runs some failures but some didn't even make it to install. I know aws had issues today but also saw in gcp etc.. Will do another set of runs tomorrow.

**Comment by kikisdeliveryservice** [comment]
aws/gcp upgrades passed! azure upgrade failed due to an already report azure infra issu.

**Comment by kikisdeliveryservice** [comment]
we have a fix now [merged](https://github.com/openshift/installer/pull/6311) that might fix the azure ci issues. so let's give it a try here.

/test e2e-azure-upgrade

**Comment by kikisdeliveryservice** [comment]
let's try these again:
/test e2e-aws-upgrade
/test e2e-gcp-upgrade
/test e2e-azure-upgrade

**Comment by kikisdeliveryservice** [comment]
That didn't seem to work... trying again
/payload 4.12 nightly informing

**Comment by kikisdeliveryservice** [comment]
> level=error msg=Error: error creating EC2 NAT Gateway: InvalidElasticIpID.NotFound: The elasticIp ID 'eipalloc-01ee12a6e0fb64b2d' does not exist
> level=error msg=	status code: 400, request id: 52052c44-752f-4a8a-ae89-8c4e4a41fbb3 

/test e2e-aws-serial

**Comment by kikisdeliveryservice** [comment]
payload 4.12 nightly informing

**Comment by kikisdeliveryservice** [comment]
`could not create snapshot imagestream ocp/4.12 for release latest: etcdserver: request timed out`
/test images

**Comment by kikisdeliveryservice** [comment]
holding off on testing nightlies until I see if the pending one passes and is promoted:
/payload 4.12 ci blocking
/payload 4.12 ci informing

**Comment by kikisdeliveryservice** [comment]
infra issue:
```level=error msg=Virtual Network Link Name: "ci-op-c8n7kvrv-fc795-929x6-network-link"): performing CreateOrUpdate: virtualnetworklinks.VirtualNetworkLinksClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'ci-op-c8n7kvrv-fc795.ci.azure.devcluster.openshift.com' not found."
level=error
```
/test e2e-agnostic-cmd

**Comment by kikisdeliveryservice** [comment]
No new nightly from today (so itll be from 9.14), but going to retrigger those payload tests anyway

/payload 4.12 nightly blocking
/payload 4.12 nightly informing

**Comment by kikisdeliveryservice** [comment]
k8s-e2e-conformance-aws failed:
`ListenerNotFound: Listener 'arn:aws:elasticloadbalancing:us-east-2`

/test k8s-e2e-conformance-aws

**Comment by kikisdeliveryservice** [comment]
CI looking good, going to wait a little longer to kick the payload jobs off.

**Comment by kikisdeliveryservice** [comment]
e2e-aws-serial has failure:
```event happened 22 times, something is wrong: ns/openshift-etcd-operator deployment/etcd-operator - reason/UnhealthyEtcdMember unhealthy members: ip-10-0-177-155.us-east-2.compute.internal```

I'll rerun this and also look deeper into it tomorrow.

/test e2e-aws-serial

**Comment by kikisdeliveryservice** [comment]
Lots of rpm failures, testing blocking jobs again first, then will kick off informing. (also nightly informing aren't finished yet)
/payload 4.12 ci blocking
/payload 4.12 nightly blocking

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-sdn-upgrade

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-aws-ovn-upgrade

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-gcp-sdn-upgrade

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-aws-sdn-techpreview periodic-ci-openshift-release-master-ci-4.12-e2e-aws-sdn-techpreview-serial

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-sdn-upgrade periodic-ci-openshift-release-master-nightly-4.12-upgrade-from-stable-4.11-e2e-aws-sdn-upgrade

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-gcp-ovn-csi

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-single-node periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-single-node-seria

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-single-node-serial

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-driver-toolkit

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-azure-sdn-upgrade

/test e2e-aws-serial

**Comment by kikisdeliveryservice** [comment]
/payload-test periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-ovn-ipv6

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-console-aws periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-ovn-ipv6

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-sdn-bm periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-sdn-bm-upgrade

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-serial-ovn-ipv6 periodic-ci-openshift-release-master-nightly-4.12-upgrade-from-stable-4.11-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn

**Comment by kikisdeliveryservice** [comment]
`unable to upload the new image manifest: received unexpected HTTP status: 503 Service Unavailable`
this job seems to be [failling across PRs](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-kubernetes-master-e2e-aws-serial?buildId=)
/test e2e-aws-serial

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-proxy

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-gcp-sdn-upgrade periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-single-node-serial periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-single-node

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-azure-upgrade-ovn-single-node

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-ovn-techpreview periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-ovn-techpreview-serial

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-e2e-azure-sdn-techpreview periodic-ci-openshift-release-master-ci-4.12-e2e-azure-sdn-techpreview-serial

**Comment by kikisdeliveryservice** [comment]
somehow i missed this one :sweat_smile: 
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-ovn-serial

**Comment by kikisdeliveryservice** [comment]
> @kikisdeliveryservice: trigger 1 job(s) for the /payload-(job|aggregate) command
> 
>     * periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-ovn-serial
> 
> 
> See details on https://pr-payload-tests.ci.openshift.org/runs/ci/38a8f790-3a22-11ed-9a32-401bfc11b585-0

@soltysh all of the test runs are in the sheet except for the very last one above: periodic-ci-openshift-release-master-nightly-4.12-e2e-vsphere-ovn-serial

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-console-aws periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-single-node periodic-ci-openshift-release-master-nightly-4.12-e2e-aws-ovn-proxy periodic-ci-openshift-release-master-nightly-4.12-e2e-azure-deploy-cnv periodic-ci-openshift-release-master-ci-4.12-e2e-azure-sdn-techpreview

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade periodic-ci-openshift-release-master-ci-4.12-e2e-gcp-sdn-upgrade periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-azure-sdn-upgrade

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-gcp-ovn-upgrade periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-azure-sdn-upgrade periodic-ci-openshift-release-master-nightly-4.12-upgrade-from-stable-4.11-e2e-metal-ipi-upgrade-ovn-ipv6

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-serial-ovn-dualstack periodic-ci-openshift-release-master-ci-4.12-e2e-azure-upgrade-ovn-single-node periodic-ci-openshift-release-master-nightly-4.12-e2e-azure-sdn

**Comment by kikisdeliveryservice** [comment]
We have 2 passing aws-serial runs: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1360-nightly-4.12-e2e-aws-sdn-serial/1573020226411302912  and https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1360-ci-4.12-e2e-aws-sdn-serial/1573020195818049536

So rerunning here:
/test e2e-aws-serial

**Comment by cgwalters** [comment]
Any overall status update on this so far?  Are the bugs being investigated?  This is holding up https://github.com/openshift/machine-config-operator/pull/3317 so if I or anyone else can be of help...

At a brief glance at the payload tests, something seems confused in "Passed 3 times, failed 0 times, skipped 0 times: we require at least 6 attempts to have a chance at success" - something changed to cause the tests to only run 3 instead of 6 times?

**Comment by dgoodwin** [comment]
https://issues.redhat.com/browse/DPTP-3154

https://github.com/openshift/ci-tools/pull/3034

https://coreos.slack.com/archives/C03TCGG429J/p1663888194909339

We're lacking signal on azure and metal, and the ci infra to get the signal is broken.

**Comment by kikisdeliveryservice** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-sdn-bm

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-sdn-bm

**Comment by soltysh** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-sdn-bm

**Comment by kikisdeliveryservice** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade 10

**Comment by soltysh** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade 10

**Comment by soltysh** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade 10

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-upgrade-from-stable-4.11-e2e-metal-ipi-bm-upgrade

**Comment by soltysh** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade 15

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.12-upgrade-from-stable-4.11-e2e-metal-ipi-bm-upgrade
we've gotten passed the ci infrastructure problems, last attempt failed on tests

**Comment by kikisdeliveryservice** [comment]
> @kikisdeliveryservice: trigger 1 job(s) for the /payload-(job|aggregate) command
> 
>     * periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade
> 
> 
> See details on https://pr-payload-tests.ci.openshift.org/runs/ci/a1b544d0-3e84-11ed-8228-92815873b89f-0

hmm i thought we were giving more time but it still ends at 4.5hr. :shrug: 

Interestingly we got 4:11 success but 4 unfinished.  I have a morbid curiosity so just running with 10.

/payload-aggregate periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade 10

**Pull request merged**
