### PR TITLE
Bug 1948311: Handle 429 errors from watch requests in reflector

### PR DESCRIPTION
**Pull request by tkashem**

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

this isn't the fix we're looking for.

**Comment by deads2k** [comment]
We want https://github.com/kubernetes/kubernetes/pull/100959

We can take this later, but let's get the big money first.  We want that PR picked into o/k, o/o, and probably our operator repos.  It's bad.

**Comment by p0lyn0mial** [comment]
I think we still want this PR.

We have seen cases where `kube-scheduler-recovery-controller` was crash looping because it received 429 from the server and wasn't able to deal with it. See https://coreos.slack.com/archives/CB48XQ4KZ/p1620338344384200 for more details.

**Review by soltysh — APPROVED** [review]
/approve

**Comment by deads2k** [comment]
Plan to remove this hold once we are within a week of final freeze.  To be clear about what this doing.
1. currently, reflectors will *always* restart
2. this PR optimizes 429 to re-watch instead of relist
3. this PR doesn't matter for small watchers
4. the core problem we have is too many watches being established.  Retrying here will not help address that problem
5. After apiservers have been up for 20 minutes, there is no limit at the CI issues we're finding and fixing will auto-fix.

**Comment by deads2k** [comment]
Recent audit logs from e2e tests show that we've squashed offenders issuing too many short watches.  


/hold cancel

**Comment by p0lyn0mial** [comment]
/retitle Bug 1948311: Handle 429 errors from watch requests in reflector

**Pull request merged**
