### PR TITLE
OCPBUGS-42167: Bump k8s api to 1.30.5

### PR DESCRIPTION
**Pull request by jerpeter1**
Bump kubernetes version to 1.30.5
/cc @bertinatto

### CODE REVIEW

**Review by dinhxuanvu — CHANGES_REQUESTED** [review]
Looking good.
Would you mind updating the k8s version to 1.30.5 in the hyperkube Dockerfile?
Thanks

**Comment by jerpeter1** [comment]
> Would you mind updating the k8s version to 1.30.5 in the hyperkube Dockerfile?

There was a bug in the automation script's sed expression - thanks for catching this!

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Pull request merged**
