### PR TITLE
Bug 1875046: Undiagnosed panic detected in pod: openshift-kube-apiserver_kube-apiserver: runtime.go:76: invalid memory address or nil pointer dereference 

### PR DESCRIPTION
**Pull request by p0lyn0mial**
clean pick.

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/cc @marun

re rebase: just let me know if you are going to pick it up.

**Comment by marun** [comment]
@p0lyn0mial The rebase was just tagged for merge, so this should probably go in on top of it to avoid having to resubmit and retest the rebase PR.

**Comment by p0lyn0mial** [comment]
@marun ok, I will re-pick tomorrow.

**Pull request merged**
