### PR TITLE
[WIP] WRKLDS-1449: Rebase 1.31.0

### PR DESCRIPTION
**Pull request by atiratree**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by soltysh** [comment]
serial will be fixed when https://github.com/openshift/origin/pull/29023 merges

**Comment by soltysh** [comment]
/test e2e-aws-ovn-serial
this should pass now with https://github.com/openshift/origin/pull/29023 in

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-osde2e-main-nightly-4.18-osd-aws
/payload-job periodic-ci-openshift-osde2e-main-nightly-4.18-osd-gcp
/payload-job periodic-ci-openshift-osde2e-main-nightly-4.18-rosa-classic-sts
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-vsphere-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-agent-compact-ipv4-conformance
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ovn-assisted
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-ovn-upgrade

**Comment by atiratree** [comment]
update to latest changes

**Comment by atiratree** [comment]
failures seem network related
/test e2e-aws-ovn-upgrade
/test k8s-e2e-gcp-ovn

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-serial-virtualmedia
/payload-job periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-metal-ovn-single-node-recert-cluster-rename

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-serial-virtualmedia
/payload-job periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-metal-ovn-single-node-recert-cluster-rename

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-ovn-kube-apiserver-rollout
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-azure-csi

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-bm-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-serial-ipv4
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-serial-virtualmedia
/payload-job periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-ovn-upgrade
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-serial-ovn-dualstack
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-upgrade-ovn-ipv6
/payload-job periodic-ci-openshift-release-master-nightly-4.18-metal-ovn-single-node-recert-cluster-rename

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-ipv6-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-metal-ipi-ovn-dualstack-techpreview

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-gcp-ovn-techpreview-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview-serial

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial

**Comment by atiratree** [comment]
testing a revert of https://github.com/kubernetes/kubernetes/pull/124736

/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-serial

**Comment by atiratree** [comment]
testing reverts of APIServingWithRoutine feature

/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-serial
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-single-node-techpreview
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-seria

**Comment by atiratree** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-azure-ovn-techpreview-serial

**Comment by atiratree** [comment]
closing in favor of https://github.com/openshift/kubernetes/pull/2092

**Pull request closed without merging**
