### PR TITLE
see if GC QPS matters

### PR DESCRIPTION
**Pull request by deads2k**
I wonder.

### CODE REVIEW

**Comment by deads2k** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-upgrade-ovn-single-node

**Comment by deads2k** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-upgrade-ovn-single-node 10

**Comment by deads2k** [comment]
Sigh. That payload doesn't make sense because it's installing the old level. We'll need to find another job

**Comment by vrutkovs** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-azure-ovn-kube-apiserver-rollout

**Comment by vrutkovs** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.17-e2e-azure-ovn-kube-apiserver-rollout 10

**Comment by deads2k** [comment]
it didn't fix it.  may have helped, but didnt' fix.

**Pull request closed without merging**
