### PR TITLE
WIP Revert "UPSTREAM: <carry>: bump cadvisor version to fix missing netwo…

### PR DESCRIPTION
**Pull request by haircommander**
…rk stats"

This reverts commit 5d26230d8f24be93fe99a2b1fa4b7b9c3d986942.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by haircommander** [comment]
/payload-job periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.18-nightly-x86-payload-control-plane-6nodes

**Comment by smg247** [comment]
/payload-job pull-ci-openshift-kubernetes-master-perfscale-control-plane-6nodes

**Comment by smg247** [comment]
/payload-job pull-ci-openshift-kubernetes-master-perfscale-control-plane-6nodes

**Comment by haircommander** [comment]
okay so we identified this as the issue, but we cannot revert now. Investigating other approaches in https://github.com/openshift/kubernetes/pull/2085

**Pull request closed without merging**
