### PR TITLE
[4.10] OCPBUGS-8735: UPSTREAM: <drop>: bump apiserver-library-go

### PR DESCRIPTION
**Pull request by stlaz**
backport of https://github.com/openshift/kubernetes/pull/1627

/assign @s-urbaniak

### CODE REVIEW

**Comment by stlaz** [comment]
/test integration
timeouts?

**Comment by stlaz** [comment]
/retest-required
The errors we see don't seem to be related. If they keep reappearing, we may need to check with node team to see if this is a known issue.

**Comment by stlaz** [comment]
looks like the same job fails irregardless of these fixes - https://github.com/openshift/kubernetes/pull/1648

**Comment by mfojtik** [comment]
/override ci/prow/k8s-e2e-gcp

this job fails regardless of this change, it will be reported to node team in jira issue, but it should not delay a CVE fix.

**Pull request merged**
