### PR TITLE
AUTH-336: UPSTREAM: <carry>: PSa metrics: unset ocp_namespace on non-platform n…

### PR DESCRIPTION
**Pull request by stlaz**
…amespaces

/cc @deads2k @openshift/openshift-team-auth

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
/lgtm

**Comment by deads2k** [comment]
/approve

This came out of a comment on the previous impl

**Comment by soltysh** [comment]
/override ci/prow/e2e-aws-ovn-cgroupsv2 
the failure is a known issue being tracked in https://issues.redhat.com/browse/OCPBUGS-8092

**Pull request merged**
