### PR TITLE
OCPBUGS-16080: UPSTREAM: <carry>: watch-termination: termination.log file

### PR DESCRIPTION
**Pull request by mfojtik**
xref: https://issues.redhat.com/browse/OCPBUGS-15783

Does this commit seem to be lost during rebase(s) ?

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
matches the original commit at https://github.com/openshift/kubernetes/commit/ccce86c

/lgtm

**Comment by tkashem** [comment]
/retitle OCPBUGS-16080: UPSTREAM: <carry>: watch-termination: termination.log file

**Comment by wangke19** [comment]
per-merge verifed for the bug, got the expected test results, detail see: 
https://issues.redhat.com/browse/OCPBUGS-16080?focusedId=22785520&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22785520

**Comment by dgrisonnet** [comment]
Retrying.

/unhold
/retest

**Comment by dgrisonnet** [comment]
@soltysh do you know anything about this unit test failure? It seems completely unrelated to this PR.

**Comment by p0lyn0mial** [comment]
> @soltysh do you know anything about this unit test failure? It seems completely unrelated to this PR.

In general, it looks like the `unit` job is very unstable. See https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-kubernetes-master-unit

Your recent run failed on:
```
=== FAIL: pkg/util/hash  (0.00s)
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x426680]

goroutine 1 [running, locked to thread]:
runtime.throw({0x610c32?, 0xc0000ab960?})
	/usr/lib/golang/src/runtime/panic.go:1047 +0x5d fp=0xc0000ab918 sp=0xc0000ab8e8 pc=0x44b2dd
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:851 +0x28a fp=0xc0000ab978 sp=0xc0000ab918 pc=0x461aaa
runtime.mapassign_fast64(0x5ea1c0, 0xc0000ae210, 0x3d)
	/usr/lib/golang/src/runtime/map_fast64.go:118 +0x160 fp=0xc0000ab9b8 sp=0xc0000ab978 pc=0x426680
go/parser.init()
	/usr/lib/golang/src/go/parser/parser.go:396 +0x65 fp=0xc0000abac0 sp=0xc0000ab9b8 pc=0x515d65
runtime.doInit(0x929300)
	/usr/lib/golang/src/runtime/proc.go:6506 +0x126 fp=0xc0000abbf0 sp=0xc0000abac0 pc=0x45b666
runtime.doInit(0x92a420)
	/usr/lib/golang/src/runtime/proc.go:6483 +0x71 fp=0xc0000abd20 sp=0xc0000abbf0 pc=0x45b5b1
runtime.doInit(0x929380)
	/usr/lib/golang/src/runtime/proc.go:6483 +0x71 fp=0xc0000abe50 sp=0xc0000abd20 pc=0x45b5b1
runtime.doInit(0x9278c0)
	/usr/lib/golang/src/runtime/proc.go:6483 +0x71 fp=0xc0000abf80 sp=0xc0000abe50 pc=0x45b5b1
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:233 +0x1c6 fp=0xc0000abfe0 sp=0xc0000abf80 pc=0x44db86
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000abfe8 sp=0xc0000abfe0 pc=0x47f441
```

which looks like an issue with the language itself. 

I have found a few other runs that failed with `segmentation fault` (not exactly the same error as you hit):
- https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_kubernetes/1552/pull-ci-openshift-kubernetes-master-unit/1699411982098108416/build-log.txt
- https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_kubernetes/1552/pull-ci-openshift-kubernetes-master-unit/1699392604015169536/build-log.txt
- I'm pretty sure I could give you more examples but prow has just stopped working :(

I think we could engage our internal golang team to help us nail the issue (feel free to open a new issue). Until then, if you would like to merge it, just keep re-trying.

**Pull request merged**
