### PR TITLE
rebase kube picks: branch

### PR DESCRIPTION
**Pull request by deads2k**
@liggitt @soltysh @pweil- let the review begin!

### CODE REVIEW

**Comment by soltysh** [comment]
I'll leave that for tomorrow morning :dancer:

**Comment by soltysh** [comment]
@deads2k first question that pops into my head is how are you planning to handle updating k8s, is it going to happen only once before the rebase work or rather it'll be a moving process?

**Comment by soltysh** [comment]
Any particular reason you drop https://github.com/openshift/origin/commit/6f8293d8dbd86ab2a715e59871e279367f48e240 ?

**Comment by soltysh** [comment]
We should note down somewhere these two commits from previous rebase, which will be needed when bumping emicklei/go-restful (https://github.com/openshift/origin/commit/e9c182c) or coreos/etcd (https://github.com/openshift/origin/commit/9797766) so I'll put it here, as a side note.

**Comment by deads2k** [comment]
> Any particular reason you drop openshift/origin@6f8293d ?

We don't seem to need it.

**Comment by deads2k** [comment]
> We should note down somewhere these two commits from previous rebase, which will be needed when bumping emicklei/go-restful (openshift/origin@e9c182c) or coreos/etcd (openshift/origin@9797766) so I'll put it here, as a side note.

picked those back up in origin.  Not sure if we'll do transitive work here.

**Comment by soltysh** [comment]
@deads2k since https://github.com/openshift/origin/pull/6947 got merged we should merge this one as well :)

**Comment by liggitt** [comment]
I actually am not sure I would merge this to master. I think I'd expect a branch per rebase, with master tracking upstream

**Comment by soltysh** [comment]
Fair, I'm just saying we need to have the track of the changes in this repo.

**Comment by deads2k** [comment]
Merged into the stable-<date> branch. https://github.com/openshift/kubernetes/pull/4

**Pull request closed without merging**
