### PR TITLE
UPSTREAM: <carry>: remove hack/update-codecgen from hack/update-all.sh

### PR DESCRIPTION
**Pull request by pmorie**
@pweil- @liggitt cc @smarterclayton

### CODE REVIEW

**Comment by liggitt** [comment]
related to https://github.com/openshift/origin/issues/6848

**Comment by liggitt** [comment]
I'm really hesitant to start customizing the hack scripts in this repo

**Comment by pmorie** [comment]
Apparently more hesitant than you were about customizing the codec behavior of the repo :)

**Comment by liggitt** [comment]
yup

**Pull request closed without merging**
