### PR TITLE
UPSTREAM: <carry>: cloud-providers: aws: support WebIdentityTokenProvider credentials

### PR DESCRIPTION
**Pull request by sjenning**
@JoelSpeed @csrwng @derekwaynecarr @deads2k 

This PR allows the KCM to use the new service account token format against the AWS API.

Ideally, I'd just like to have the KCM use the default credential chain vs the custom one with the cloud provider config file, but not sure if that can be done in a backward compatible way.

### CODE REVIEW

**Comment by enxebre** [comment]
Related PR for outr of tree provider https://github.com/kubernetes/cloud-provider-aws/pull/238

**Comment by deads2k** [comment]
I'd like to see this work move in a direction that is consistent with upstream.  My understanding is that the legacy cloud providers are not expected to gain any additional features and are still planned for removal.  I'd like to ensure this feature has a future before considering what may need to be done to meet a delivery window.

I suggest starting with a PR to the out-of-tree cloud provider so that we're sure to have a migration path.  Then open the possibility of parity upstream.  Once there is a path to the preferred mechanism, we should work out how far away we are from using it.

/hold

**Comment by enxebre** [comment]
If @sjenning confirms this kubernetes/cloud-provider-aws#238 satisfies our needs we should just bring this changes here

**Comment by sjenning** [comment]
Closing in favor of trying upstream with an already accepted fix in the external provider https://github.com/kubernetes/kubernetes/pull/104314

**Pull request closed without merging**
