### PR TITLE
Bug 1878163: Build with golang 1.15

### PR DESCRIPTION
**Pull request by marun**

### CODE REVIEW

**Comment by marun** [comment]
Timed submitting this to coincide with dptp secret rotation, so all jobs are likely to fail d'oh!

**Comment by marun** [comment]
This branch is now building with golang 1.15 so ci should be capable of passing.

**Comment by yselkowitz** [comment]
FYI there is no golang-1.15 for RHEL 7 yet, only for RHEL 8.  As the RPM is built for both, this needs to be kept in mind.

**Comment by marun** [comment]
Updated to ensure the same version of protoc is installed as is present in the upstream image created for dockerized update/verify. The previous centos image didn't have protoc installed at all, but the rhel8 base image appears to use version 3.6.x.

**Comment by marun** [comment]
Unit tests are chronically racey.

**Comment by marun** [comment]
I can't replicate the verify failure locally, ocp wins again. Given that this was working up until this week, maybe the ci migration from 3.x to 4.x is to blame?

**Pull request merged**
