### PR TITLE
UPSTREAM: <drop>: resurrect extensions/v1beta1.HPA

### PR DESCRIPTION
**Pull request by sttts**
Reintroduce extensions/hpa for 3.6, to be dropped for 3.7.

Counter part PR to https://github.com/openshift/origin/pull/14021.

### CODE REVIEW

**Comment by ncdc** [comment]
@sttts why not just wait for us to move multiple UPSTREAMs from origin to here in a batch?

**Comment by sttts** [comment]
would also be fine. who does the bulk moves usually? during the next (small) rebase?

**Comment by ncdc** [comment]
We do bulk moves whenever it seems like a good time, or during the next rebase. I'm not sure it's really worth doing it now.

**Comment by ncdc** [comment]
I'm closing this as #29 will bring it in.

**Pull request closed without merging**
