### PR TITLE
Bug 1873043: Rebase 1.19.0

### PR DESCRIPTION
**Pull request by marun**
- The `verify-commits` job will need to be overridden to merge due to the presence of un-prefixed commits in the base kube branch.
- This repo has been configured to permit merge despite the presence of the `do-not-merge/invalid-owners-file` label, which is applied due to the presence of upstream kube contributors in OWNERS files that do not belong to the openshift org.
- [Tracking spreadsheet](https://docs.google.com/spreadsheets/d/10KYptJkDB1z8_RYCQVBYDjdTlRfyoXILMa0Fg8tnNlY/edit#gid=382288197)

### CODE REVIEW

**Comment by sttts** [comment]
How much of the red is expected?

**Comment by sttts** [comment]
Did a rebase detect which commits were already merged?

**Comment by marun** [comment]
> How much of the red is expected?

- Cluster deployment appears to be broken by the bump, as evidenced by the e2e jobs all having the same failure mode. 
- The unit test failure only reproduces in CI, it passes locally. 
- As per the PR description, `verify-comments` is expected to fail.

**Comment by marun** [comment]
> Did a rebase detect which commits were already merged?

I followed the usual procedure in checking carried commits referencing PRs with the status of those PRs, as per the linked spreadsheet. Blinding picking sometimes fails (ideally) if the upstream PR was exactly the same as the carried commit, but can succeed just as easily when the commits differ even if only in non-functional formatting.

**Comment by marun** [comment]
Back to a fake bump until https://github.com/openshift/library-go/pull/875 merges.

**Comment by soltysh** [comment]
A few comments, I'd encourage to squash similar/correlating commits together to minimize the effort, where possible: 
- `UPSTREAM: <carry>: force dumping events on upgrade failure` - is coming from https://github.com/openshift/origin/pull/22809 and was used to debug a particular failure, I'm inclined to drop it
- `UPSTREAM: <carry>: add pod logs dump to e2e` - similar situation to above (https://github.com/openshift/origin/pull/24032), I'd drop too, or squash them both
- `UPSTREAM: <carry>: Remove excessive logging during e2e upgrade test` and `UPSTREAM: <carry>: Remove a redundant output in the tests` could probably be squashed together - they serve the same purpose
- `UPSTREAM: <carry>: eliminate unnecessary closure in openshift configuration wiring` - have you considered squashing that with the ones that introduce these changes?
- `UPSTREAM: <carry>: oauth-token-authn: switch to sha256~ prefix` and `UPSTREAM: <carry>: oauth-token-authn: add sha256~ support to bootstrap authenticator` could be squashed into one

**Comment by marun** [comment]
> A few comments, I'd encourage to squash similar/correlating commits together to minimize the effort, where possible:
> 
> * `UPSTREAM: <carry>: force dumping events on upgrade failure` - is coming from [openshift/origin#22809](https://github.com/openshift/origin/pull/22809) and was used to debug a particular failure, I'm inclined to drop it

Dropped

> * `UPSTREAM: <carry>: add pod logs dump to e2e` - similar situation to above ([openshift/origin#24032](https://github.com/openshift/origin/pull/24032)), I'd drop too, or squash them both

Dropped

> * `UPSTREAM: <carry>: Remove excessive logging during e2e upgrade test` and `UPSTREAM: <carry>: Remove a redundant output in the tests` could probably be squashed together - they serve the same purpose

Squashed

> * `UPSTREAM: <carry>: eliminate unnecessary closure in openshift configuration wiring` - have you considered squashing that with the ones that introduce these changes?

Attempting to squash doesn't apply cleanly, the code it's modifying is spread in the history. While reification is probably possible with more work I'm skipping for now.

> * `UPSTREAM: <carry>: oauth-token-authn: switch to sha256~ prefix` and `UPSTREAM: <carry>: oauth-token-authn: add sha256~ support to bootstrap authenticator` could be squashed into one

Squashed

**Comment by soltysh** [comment]
> Attempting to squash doesn't apply cleanly, the code it's modifying is spread in the history. While reification is probably possible with more work I'm skipping for now.

yeah, I imagine that might require a bit more time which we don't have nowadays, but :+1: for the rest, thx!

**Comment by marun** [comment]
Bump is no longer fake. Updated to include carries for:

 - https://github.com/openshift/kubernetes/pull/330
 - https://github.com/openshift/kubernetes/pull/323

**Comment by marun** [comment]
Fixed kube e2e dockerfile to use recent ocp cli image, previous reference was to a 4.2 image that has apparently been removed.

**Comment by marun** [comment]
Unit test failures are largely due to including https://github.com/openshift/kubernetes/pull/330 before it was ready. Will push with that commit removed once the e2e jobs return results.

**Comment by marun** [comment]
Unit test failure should now be fixed. e2e-aws-serial passed on a previous run, so I'm guessing just a flake.

**Comment by marun** [comment]
/hold 

Need to pick up some recently merged carries.

**Comment by marun** [comment]
/retest 

The k8s-e2e-gcp run appears to be due to an unrelated issue. The upgrade test may be legit

**Comment by marun** [comment]
Updated to include carry for https://github.com/openshift/kubernetes/pull/330

**Comment by marun** [comment]
Despite the e2e-gcp-upgrade job passing, upgrade jobs initiated for both aws and gcp are failing:

- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1301705238985576448
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp/1301705217280053248

I'm investigating whether the disparity between ci or cluster-bot initiated jobs is due to variance in job configuration (timeout being the most likely culprit) or changes in this PR.

**Comment by sttts** [comment]
Verify script does not like `UPSTREAM: revert: 12345: A kube revert`

**Comment by marun** [comment]
> Verify script does not like `UPSTREAM: revert: 12345: A kube revert`

I'm afraid you're misreading the output of the `verify-commits` job. Those errors are being reported on commits from upstream (i.e. the 1.19.0 base) not on the carries that are layered on top of it. That is why I noted in the PR's initial comment that the `verify-commits` job will need to be overridden, and this will be true for all rebase PRs until we decide it's worth the effort to ignore the commits prior to the new base commit.

**Comment by marun** [comment]
Updated to include recent carries.

**Comment by sttts** [comment]
/override ci/prow/verify-commits 

The commit verifier is known to fail on this one because commits are checked that come from upstream (they are considered to be part of this PR).

**Comment by marun** [comment]
Picked https://github.com/openshift/kubernetes/pull/338 since its merge forced a retest and stripped the override for verify-commits.

**Pull request merged**
