### PR TITLE
Bug 2077933: Don't fail when OpenStack config contains unknown directives

### PR DESCRIPTION
**Pull request by mdbooth**
#### What type of PR is this?
/kind bug

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mandre** [comment]
@sttts @soltysh: this PR fixes a pretty important issue for the in-tree cloud provider on OpenStack that would cause KCM to crash if the user sets an option (for Cinder CSI, or external CCM) that in-tree cloud provider doesn't know about. It's important for us to have it in 4.11 as Cinder CSI becomes the default volume provisioner. Would you be able to take a look before the code freeze?

Matt explains the issue in details in the (merged) [upstream PR](https://github.com/kubernetes/kubernetes/pull/109709).

**Comment by MaysaMacedo** [comment]
This [fix](https://github.com/openshift/kubernetes/commit/e5a565b093ba504ed2056b2f7ddf7d9be120c5ae) has landed with the 1.25 rebase. Probably this PR can be closed?

**Comment by mandre** [comment]
> This [fix](https://github.com/openshift/kubernetes/commit/e5a565b093ba504ed2056b2f7ddf7d9be120c5ae) has landed with the 1.25 rebase. Probably this PR can be closed?

Too bad we weren't able to merge this PR, this would have make it easier to backport to 4.11.
/close

**Comment by MaysaMacedo** [comment]
> > This [fix](https://github.com/openshift/kubernetes/commit/e5a565b093ba504ed2056b2f7ddf7d9be120c5ae) has landed with the 1.25 rebase. Probably this PR can be closed?
> 
> Too bad we weren't able to merge this PR, this would have make it easier to backport to 4.11. /close

@mdbooth As we started discussing offline, it seems this fix is needed on 4.11 as mentioned by @mandre [here](https://github.com/openshift/kubernetes/pull/1250#issuecomment-1156306860).  Let us know if you think otherwise

**Pull request closed without merging**
