### PR TITLE
Pick down release 1.2 stable 20160411

### PR DESCRIPTION
**Pull request by mfojtik**
Result of `TARGET_BRANCH=rebase ./hack/move-upstream.sh master...4d3cc39`

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k @pweil- PTAL

**Comment by deads2k** [comment]
lgtm

**Comment by deads2k** [comment]
Also, naughty @bparees "fix godeps"

**Comment by soltysh** [comment]
How did that went through @ironcladlou 's verify upstream commits script?

**Comment by pweil-** [comment]
> How did that went through @ironcladlou 's verify upstream commits script?

good question

**Comment by bparees** [comment]
i swear i remember doing that as an UPSTREAM because i explicitly asked someone how i should phrase the commit....not sure what happened, sorry.

**Pull request merged**
