### PR TITLE
Bug 2081194: UPSTREAM: <carry>: update list of deprecated apis

### PR DESCRIPTION
**Pull request by sanchezl**
Update the list of deprecated APIs marked for removal base on the latest [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide).

### CODE REVIEW

**Review by soltysh — COMMENTED** [review]
/hold 
this should be picked manually for #1087

**Comment by harche** [comment]
Please ignore the noise, just looking for a sample PR to launched just merged crun based job https://github.com/openshift/release/pull/23609

**Pull request merged**
