### PR TITLE
1.12.2 rebase

### PR DESCRIPTION
**Pull request by soltysh**
The following commit I dropped and need careful examination:
* 03bd77122cd `UPSTREAM: <carry>: patch in a non-standard location for apiservices` @deads2k
* 3587ab47a9a `UPSTREAM: <drop>: make RootFsInfo error non-fatal on start` @sjenning 

Additionally, do we still need these commits:
* bc693d96e169e2748d6bafa9ad0afb76f00ca1f3 `UPSTREAM: <drop>: hack to "fix" period problem.` @sjenning @deads2k 
* 6fcadb380847955d3576af9383ea756176195388 `UPSTREAM: <carry>: coerce string->int, empty object -> slice for backwards compatibility` @deads2k 

The full pick list: https://docs.google.com/spreadsheets/d/1xi5SNL96wqBlIpuIB7d4vRlhBNawhoe2-MWDZMbL6Ig/edit?usp=sharing

@openshift/sig-master 
@deads2k 
@smarterclayton for c8921588f8068ca61e9703da7782fd5b95452080

### CODE REVIEW

**Comment by sjenning** [comment]
Yes, `3587ab4 UPSTREAM: <drop>: make RootFsInfo error non-fatal on start` is handled in a better way in 1.12 now https://github.com/kubernetes/kubernetes/pull/65595.  It is safe to drop.

Looking at the other one...

**Comment by deads2k** [comment]
After we land the rebase, we should consider reverting:

```
46436f61b81 UPSTREAM: emicklei/go-restful-swagger12: <carry>: NEEDED TO BUILD shim to allow multiple containers to union for swagger
b31964afb61 UPSTREAM: <carry>: disambiguate operation names for legacy discovery
5110907b83d UPSTREAM: <carry>: allow a filter function on admission registration
d7691b19531 UPSTREAM: <carry>: allow multiple containers to union for swagger
b2597d11d9c UPSTREAM: <carry>: make wiring in kubeproxy easy until we sort out config
d9c1a0d12cc UPSTREAM: <carry>: hack out the oapi for restmapping resources when more than one is present
7e9a8b01f19 UPSTREAM: 49312: allow the /version endpoint to pass through
8af966e0e06 UPSTREAM: <carry>: fix fifo resync, remove after FIFO is dead

```

**Comment by deads2k** [comment]
lgtm

**Comment by sjenning** [comment]
And https://github.com/openshift/origin/pull/20158 removed the need for `bc693d9 UPSTREAM: <drop>: hack to "fix" period problem.`

**Comment by soltysh** [comment]
> After we land the rebase, we should consider reverting:

SGTM

I've fixed unit tests, so this currently is green in units. I'll leave it open until I get a reasonable proof it's working as it should in origin.

**Pull request merged**
