### PR TITLE
Bug 1949050: UPSTREAM: 101287: Fail fast when image is specified w/o tag

### PR DESCRIPTION
**Pull request by soltysh**
/assign @mfojtik

### CODE REVIEW

**Comment by soltysh** [comment]
/override ci/prow/e2e-agnostic-cmd
this is not relevant and the test is failing, with fix in the queue

**Comment by mfojtik** [comment]
/override ci/prow/e2e-gcp-upgrade

This job is failing on unrelated bugs.

**Comment by soltysh** [comment]
ci/prow/e2e-aws-fips/test e2e-aws-fips

**Comment by soltysh** [comment]
/override ci/prow/e2e-gcp
this is not involving tests and this will actually lead to tests stabilization in the long run

**Pull request merged**
