### PR TITLE
Enable gcp-e2e-kubernetes job

### PR DESCRIPTION
**Pull request by marun**
This PR copies origin's test annotation capability to support building a k8s-e2e.test binary whose execution can be limited to openshift-compatible tests. This enables an e2e job that validates the current state of the repo with its own tests in advance of those tests being vendored into origin for incorporation into openshift-tests. 

Once this PR has merged, origin can be bumped to reuse the test annotation code defined in this repo to ensure it is maintained in only one place:

https://github.com/openshift/origin/pull/25382

### CODE REVIEW

**Comment by marun** [comment]
/cc @smarterclayton 

Given that you're the author of the test annotation mechanism, I'm guessing you should be involved in its relocation.

**Comment by marun** [comment]
The latest push switches to using ginkgo to run the tests. I learned the hard way that parallel test execution requires that the tests be run with ginkgo vs direct invocation of the test binary.

**Comment by marun** [comment]
Some CI jobs are broken by the CI switch to golang 1.14, which will be fixed by https://github.com/openshift/kubernetes/pull/297.

**Comment by mfojtik** [comment]
/override ci/prow/e2e-aws-fips

FIPS is broken and being fixed by newer RHCOS (PR is still pending)

**Comment by mfojtik** [comment]
merging with button, so we don't have to wait for the FIPS fix to land

**Pull request merged**
