### PR TITLE
Fix networking-related test exclusions

### PR DESCRIPTION
**Pull request by danwinship**
The networking-related test skips got broken in the 1.19 rebase. We have logic set up to let us to distinguish "tests that don't pass when using openshift-sdn" and "tests that don't pass when using ovn-kubernetes", but a bunch of tests just got marked as "tests that OpenShift can't pass no matter what" in the 1.19 rebase (and so specifically, we are now skipping tests in the ovn-kubernetes jobs that should not be getting skipped, because ovn-kubernetes does implement those features, and we want to test that).

Also, for some reason, the network-plugin-specific annotations were left in origin even though they only apply to upstream k8s tests. I have moved them to openshift/kubernetes in this PR, assuming that the comments in openshift/origin are correct, and that we are supposed to have all k8s skips here and all origin skips in origin. Once this merges I'll submit another PR to remove the redundant skips in origin.

### CODE REVIEW

**Comment by danwinship** [comment]
I guess this repo probably doesn't have the magic to revendor itself into origin and run CI with that? So maybe I should submit a WIP PR there...

**Comment by danwinship** [comment]
/hold
(waiting for debugging on the origin PR)

**Comment by dcbw** [comment]
@danwinship hmm, are the regexes failing or something? k8s-e2e-gcp fails on the network tests that you're moving around here.

**Comment by danwinship** [comment]
oh
the logic for, eg `[Skipped:Network/OpenShiftSDN]` is in openshift-tests, so it doesn't get used here

I guess we could just have the `ci/prow/k8s-e2e-gcp` job hardcode `-ginkgo.skip "\[Skipped:Network/OpenShiftSDN\]"` or something... @marun? (Explained more above, but basically openshift/kubernetes is forcing `openshift-tests` to skip any job that openshift-sdn can't pass, even in CI jobs that aren't using openshift-sdn.)

**Comment by marun** [comment]
LGTM

**Comment by marun** [comment]
@danwinship You'll need to run `make update` to update the generated annotations.

**Comment by danwinship** [comment]
> @danwinship You'll need to run `make update` to update the generated annotations.

oh, no, I had done that (well, I did `./openshift-hack/update-test-annotations.sh`). But it drops the `[Suite:k8s]` from every test when I do that because my working directory is `.../openshift/kubernetes/...` not `.../k8s.io/kubernetes/...`. Anyway, fixed now.

**Comment by danwinship** [comment]
/retest
the tests here seem to be pretty flaky, but I think this is ready to go

**Pull request merged**
