### PR TITLE
Bug 1908389: UPSTREAM: 97455: Use network.Interface.VirtualMachine.ID to get the binded VM

### PR DESCRIPTION
**Pull request by Miciah**
**What type of PR is this?**

/kind bug
/kind failing-test
/kind regression

**What this PR does / why we need it**:

It fixes configuring service load balancers on Azure.  

**Which issue(s) this PR fixes**:
Fixes [BZ#1908389](http://bugzilla.redhat.com/show_bug.cgi?id=1908389).

**Special notes for your reviewer**:

None.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
Picking https://github.com/kubernetes/kubernetes/pull/97455 seems reasonable.  If it works, be sure to comment on the original and backport it to kube 1.20.

**Comment by wking** [comment]
[verify-commits][1] wants the `UPSTREAM: 97455:` prefix on the commit message too, and 91eef645d2f doesn't have it at the moment.  Probably not worth addressing until [the Azure job][2] wraps up.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/497/pull-ci-openshift-kubernetes-master-verify-commits/1341454784204378112
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/497/pull-ci-openshift-kubernetes-master-e2e-azure/1341455508401295360

**Comment by Miciah** [comment]
/close
Superseded by #500.

**Pull request closed without merging**
