### PR TITLE
Bug 1876918: Move deferred taint cleanup call to ensure all are removed

### PR DESCRIPTION
**Pull request by damemi**
Pulls changes from https://github.com/kubernetes/kubernetes/pull/97819

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @ingvagabund @deads2k

**Comment by ingvagabund** [comment]
Abdullah dropped comments in the upstream PR Let's wait until those are resolved.

**Comment by damemi** [comment]
/hold
for upstream review

**Comment by damemi** [comment]
This is still waiting for final approval in the upstream PR

**Comment by damemi** [comment]
Upstream PR merged, rebased with changes

**Comment by damemi** [comment]
`Node \"ci-op-ccy6m1mi-576d3-dndts-worker-b-gszwz\" is invalid: metadata.taints[0].key: Invalid value: \"kubernetes.io/scheduling-priorities-e2e-taint-key-144cebbc-f462-48d1-83bd-0799daede850\": name part must be no more than 63 characters` uh oh

**Comment by damemi** [comment]
/hold cancel
new CI key is in place

**Comment by damemi** [comment]
/hold
this is weird, because the upstream test does not complain about the taint length and the limit should be 253 characters anyway based on the documentation (https://github.com/kubernetes/kubernetes/pull/97819/files#r558629979)

looking more into this

**Comment by damemi** [comment]
Cherry-picked upstream fix, looks like this was failing (just not blocking)

**Pull request merged**
