### PR TITLE
Bug 1937299: Fix mounting partitions on NVMe devices

### PR DESCRIPTION
**Pull request by jsafrane**
Cherry pick of https://github.com/kubernetes/kubernetes/pull/100500 into OCP 4.8 to fix https://bugzilla.redhat.com/show_bug.cgi?id=1937299

cc @openshift/storage

### CODE REVIEW

**Comment by Elbehery** [comment]
\lgtm

**Comment by Elbehery** [comment]
@jsafrane  I found this on the failed test log 
```
1/24 Tests Failed. | expand_less
: Run multi-stage test e2e-agnostic-cmd expand_less | 2h0m0s 
**failed to acquire lease: resources not found**
```

Isn't the test provisioned to test environment ?

**Comment by jsafrane** [comment]
We run only certain nr. of test jobs per cloud, i.e. each job waits for a lease during busy hours. And this one timed out.
Check https://docs.ci.openshift.org/docs/architecture/quota-and-leases/

/retest

**Pull request merged**
