### PR TITLE
OCPBUGS-3501: UPSTREAM: <carry>: Add host assignment plugin for CRD-based routes.

### PR DESCRIPTION
**Pull request by benluddy**

### CODE REVIEW

**Comment by benluddy** [comment]
/retitle OCPBUGS-3501: UPSTREAM: <carry>: Add host assignment plugin for CRD-based routes.

**Comment by tkashem** [comment]
/lgtm

Thanks

**Review by soltysh — APPROVED** [review]
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Pull request merged**
