### PR TITLE
[release-4.12] OCPBUGS-3878: UPSTREAM: <drop>: Bump openshift/api.

### PR DESCRIPTION
**Pull request by benluddy**

### CODE REVIEW

**Comment by benluddy** [comment]
/retitle [release-4.12] OCPBUGS-3878: UPSTREAM: <drop>: Bump openshift/api.

**Review by soltysh — APPROVED** [review]
/remove-label backports/unvalidated-commits
/label backports/validated-commits
/lgtm
/approve

**Pull request merged**
