### PR TITLE
Bug 1981187: Fix dangling volumes vsphere

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1981187

cc @openshift/sig-storage 

Note to reviewers - this issue is already fixed in 4.7 onwards and hence does not require backports to those versions.

Pending backports in upstream:

https://github.com/kubernetes/kubernetes/pull/104912 (against 1.19)
https://github.com/kubernetes/kubernetes/pull/104910 (against 1.20)

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
/lgtm
I also checked that all the code is in 4.7 and 4.8.

**Comment by deads2k** [comment]
I don't see the 1.19 cherrypicks for these upstream.

1. https://github.com/kubernetes/kubernetes/pull/96689
2. https://github.com/kubernetes/kubernetes/pull/96224
3. https://github.com/kubernetes/kubernetes/pull/102892
4. https://github.com/kubernetes/kubernetes/pull/95447

Comment https://github.com/kubernetes/kubernetes/pull/96534#issuecomment-768492110 suggests a willingness to merge the upstream if they can be made to function in 1.19.

**Comment by deads2k** [comment]
I now see https://github.com/kubernetes/kubernetes/pull/104485 and https://github.com/kubernetes/kubernetes/pull/104485 just waiting on the patchmanager.  You often have better luck getting them on slack.

Looks like just two more:  https://github.com/kubernetes/kubernetes/pull/96224 and https://github.com/kubernetes/kubernetes/pull/96689

**Comment by gnufied** [comment]
@deads2k yep. though they are dependent PRs, so I will have to wait for https://github.com/kubernetes/kubernetes/pull/104485 before I can open another set of cherry-picks.

**Comment by gnufied** [comment]
@deads2k so looks like https://github.com/kubernetes/kubernetes/pull/104485 got merged. Since there are PR dependencies I have opened https://github.com/kubernetes/kubernetes/pull/104910 against 1.20 and then I will have to open another PR against 1.19

**Comment by gnufied** [comment]
Also backport for 1.19 - https://github.com/kubernetes/kubernetes/pull/104912

**Comment by soltysh** [comment]
@damemi fyi, since you're doing 4.6 bump

**Comment by soltysh** [comment]
> @soltysh FYI this is stil not merged and available in latest OCP-4.6.

it'll be part of the next rounds of k8s bumps, iirc

**Pull request closed without merging**
