### PR TITLE
DNM: test commit

### PR DESCRIPTION
**Pull request by smg247**
Testing the payload command.
/cc noone
/hold DNM

### CODE REVIEW

**Comment by jmguzik** [comment]
/cc @jmguzik 
subscribing to get notifications :)

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 2

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-cilium 2

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 2

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 5
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-cilium 2

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview 3

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 2

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-serial 2

**Comment by smg247** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-cilium 2

**Comment by smg247** [comment]
/payload periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-cilium

**Comment by smg247** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-cilium

**Comment by smg247** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-cilium

**Comment by smg247** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.13-e2e-gcp-cilium

**Pull request closed without merging**
