### PR TITLE
Bug 1912564: UPSTREAM: 97206: clean up executing request on panic

### PR DESCRIPTION
**Pull request by tkashem**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
clean up executing request on panic

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

but you need to be green
/hold

holding until green.

**Comment by ashcrow** [comment]
https://github.com/openshift/kubernetes/pull/509

**Pull request merged**
