### PR TITLE
Bug 1915085: UPSTREAM: 98424: register all pending pod deletions and check for kill

### PR DESCRIPTION
**Pull request by rphillips**
Backports upstream https://github.com/kubernetes/kubernetes/pull/98424 to fix pod races on delete.

### CODE REVIEW

**Comment by rphillips** [comment]
Added a Lock() and Unlock() to the unit test to fix the race detector:

https://github.com/kubernetes/kubernetes/pull/98424/files#diff-ab8f7cf0865da30dc5a3c29c539591dff7fd7d8d9202df58206b7d70b37fae2aR460

**Review by ehashman — COMMENTED** [review]
/refresh
/lgtm

**Pull request merged**
