### PR TITLE
Bug 1963263: UPSTREAM: 102000: Ref counting is only applicable to Remote endpoints

### PR DESCRIPTION
**Pull request by aravindhp**
Backport of #762

### CODE REVIEW

**Comment by aravindhp** [comment]
/retitle Bug 1963263: UPSTREAM: 102000: Ref counting is only applicable to Remote endpoints

**Comment by aravindhp** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/1242 and https://github.com/openshift/machine-config-operator/pull/2580 needs to merge for the `metal-ipi` tests to pass

**Comment by aravindhp** [comment]
For fixing the failing `metal-ipi-*` tests,  according to @stbenjam:
>We either need to backport https://github.com/openshift/origin/pull/25994 and https://github.com/openshift/origin/pull/26007 to 4.7 (and likely 4.6, too) or [don't specify the provider on < 4.8](https://github.com/openshift/release/blob/master/ci-operator/step-registry/baremetalds/e2e/test/baremetalds-e2e-test-commands.sh#L54-L59)

Tracked by [BZ 1964203](https://bugzilla.redhat.com/show_bug.cgi?id=1963263)

**Comment by aravindhp** [comment]
Waiting on @soltysh wrt #772

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
