### PR TITLE
OCPBUGS-7267: More fixes to SCC PSa extractor

### PR DESCRIPTION
**Pull request by stlaz**
/cc @openshift/openshift-team-auth  @deads2k 

It seems that there are still some issues as outlined in the linked BZ. I see that for some reason, I hardcoded a specific seccompProfile to the tested Deployment in the e2e test. I have no idea why. However, that is the very spot that's failing at this moment.

Adding some more logging to help me figure out what's going on.

### CODE REVIEW

**Comment by stlaz** [comment]
/hold
It seems that there are still some issues as outlined in the linked BZ. I see that for some reason, I hardcoded a specific seccompProfile to the tested Deployment in the e2e test. I have no idea why. However, that is the very spot that's failing at this moment.

**Comment by stlaz** [comment]
tested and this PR works with the reproducer from the BZ

**Comment by stlaz** [comment]
The last force-push only updated the commit message to match the repository expectations

**Review by soltysh — APPROVED** [review]
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Pull request merged**
