### PR TITLE
OCPBUGS-16760: permanently disable NodeLogQuery e2e test

### PR DESCRIPTION
**Pull request by aravindhp**
Fixes OCPBUGS-16760

### CODE REVIEW

**Review by soltysh — CHANGES_REQUESTED** [review]
As pointed out in slack, but posting here for visibility:
1. I see additional changes here that need to be upstreamed first.
2. That SSH bastion seems quite expensive to just compare the output of the test. I propose to verify the correctness of output (ie. for `sinceTime` check the output time isn't earlier). It might be harder for `boot`, but I'm inclined to just drop that particular test. 
3. That SSH bastion solution you provided here is limited only to GCP, and we need to make sure this works across all platforms (AWS, Azure, bare metal, etc). So having more generic solution (see 2 above) will be more beneficial.

**Comment by aravindhp** [comment]
To follow up the Slack conversation:
- Upstream PR has merged. I opened this before it merged for testing purposes. Should I drop the commit from the is PR?
   - https://github.com/kubernetes/kubernetes/pull/121707
- I did consider not using the bastion and verifying correctness of the output but felt that approach is not authoritative enough. It is safe to compare the actual `journalctl` output.
- I see the SSH bastion being used in other places in the release repo. [Example](https://github.com/openshift/release/blob/da7b5773b86f645bb7a44ba523964a6d10c3cec8/ci-operator/step-registry/openshift/e2e/test/openshift-e2e-test-commands.sh#L68)

**Comment by aravindhp** [comment]
/retitle OCPBUGS-16760: permanently disable NodeLogQuery e2e test

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Pull request merged**
