### PR TITLE
Bug 2101326: bump to k8s 1.23.12

### PR DESCRIPTION
**Pull request by soltysh**
Supersedes https://github.com/openshift/kubernetes/pull/1353

### CODE REVIEW

**Comment by soltysh** [comment]
/override ci/prow-verify-commits
this will never pass on a k8s bump bringing in upstream commits not following our commit naming rules

**Comment by soltysh** [comment]
/remove-label backports/unvalidated-commits
/label backports/validated-commits
/remove-label bugzilla/invalid-bug
/label bugzilla/valid-bug
we're merging all at once, so we have to manually force valid-bug on it

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
this will never pass on a k8s bump bringing in upstream commits not following our commit naming rules

**Comment by tkashem** [comment]
/lgtm
Thanks!

**Pull request merged**
