### PR TITLE
Bug 2040533: UPSTREAM: 107900: Pods that have terminated before starting should not block startup

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by wking** [comment]
I expect openshift/machine-config-operator#2944 cleaned up the `too many open files` error mode.

/retest

**Comment by deads2k** [comment]
watch issues seem to have come back.  But I'm comfortable saying this PR is on balance better than not having this PR.  

/override ci/prow/e2e-gcp-upgrade 
/override ci/prow/e2e-gcp

**Pull request merged**
