### PR TITLE
Bug 1957133: do not throw error when we can't get canonical path

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1957133

cc @openshift/sig-storage

### CODE REVIEW

**Comment by sdodson** [comment]
/hold
Please work with TRT to figure out why these tests fail persistently and then unhold this once we've gotten that fixed.

**Comment by sdodson** [comment]
Re-validating bugzilla status after prow config updates.
/bugzilla refresh

**Comment by gnufied** [comment]
Based on discussion in slack, I am cancelling the hold. Failing test is not a blocker and unrelated to this PR.

/hold cancel

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.80

picked

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.80

picked

**Comment by sdodson** [comment]
/override ci/prow/e2e-aws-disruptive
/override ci/prow/configmap-scale
Both of these are failing consistently across many PRs.

**Pull request merged**
