### PR TITLE
Bug 1942141: fixes cinder PV labelling

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1942141

reverts https://github.com/openshift/origin/pull/23578/commits

### CODE REVIEW

**Comment by gnufied** [comment]
cc @openshift/sig-storage

**Comment by mandre** [comment]
Could you also include commit from https://github.com/openshift/kubernetes/pull/662 in this PR?

**Comment by gnufied** [comment]
@mandre done!

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
