### PR TITLE
OCPBUGS-13392: UPSTREAM: 118915: remove legacy NetworkPolicy tests

### PR DESCRIPTION
**Pull request by npinaeva**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Disable legacy tests that started failing because of the timeout change https://github.com/kubernetes/kubernetes/pull/112923

#### Which issue(s) this PR fixes:

Fixes #https://issues.redhat.com/browse/OCPBUGS-13392

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
 Upstream PR https://github.com/kubernetes/kubernetes/pull/118915

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Comment by npinaeva** [comment]
gcp failure looks like https://issues.redhat.com/browse/OCPBUGS-15804

**Pull request merged**
