### PR TITLE
[4.13] OCPBUGS-8738: bump apiserver-lib-go

### PR DESCRIPTION
**Pull request by stlaz**
/assign @s-urbaniak

### CODE REVIEW

**Comment by stlaz** [comment]
/retest-required
infra
Some weird errors though, PROW appears to have failed to perform CSRF checks properly while communicating to GCP?

**Comment by soltysh** [comment]
Closing in favor of https://github.com/openshift/kubernetes/pull/1610

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
