### PR TITLE
Bug 2003027: Rebase 1.20.10

### PR DESCRIPTION
**Pull request by soltysh**
Alternative approach to https://github.com/openshift/kubernetes/pull/765 and https://github.com/openshift/kubernetes/pull/772 following the full procedure from https://github.com/openshift/kubernetes/blob/master/REBASE.openshift.md

Tracking sheet https://docs.google.com/spreadsheets/d/10KYptJkDB1z8_RYCQVBYDjdTlRfyoXILMa0Fg8tnNlY/edit#gid=1237742563

/assign @sttts @mfojtik @damemi 
/cc @DhritiShikhar

### CODE REVIEW

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
that will never pass on a k8s update.

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
that will never pass on a k8s update.

**Comment by soltysh** [comment]
Manually adding valid-bug label, based on discussion in control plane arch call.

**Comment by soltysh** [comment]
> /bugzilla refresh

@sdodson the BZ will never be in the correct state, we've agreed during control plane arch call from Sep 7th, that for k8s updates we'll be manually setting that label

**Comment by sdodson** [comment]
@soltysh why would the bug never become valid? We should at the very least make sure that we merge these bumps in descending order from 4.8 toward 4.6. I don't see why QE couldn't verify these bugs.

**Comment by hardys** [comment]
> @soltysh why would the bug never become valid? We should at the very least make sure that we merge these bumps in descending order from 4.8 toward 4.6. I don't see why QE couldn't verify these bugs.

@sdodson  Ok I'm trying to understand how to proceed here - should we approve https://github.com/openshift/kubernetes/pull/888, remove the manual bugzilla/valid-bug then make this bz depend on https://bugzilla.redhat.com/show_bug.cgi?id=1994457 so we can land this when that 4.8 bump is verified?

**Comment by soltysh** [comment]
Based on discussion I'm removing valid-label from this PR, until we merge #888.

**Comment by soltysh** [comment]
Based on our discussion from yesterday and #888 merged, I'm adding valid-bug label to be able to merge this one in.

fyi @hardys

**Comment by hardys** [comment]
[patch-manager] Approving for cherry-pick with a score of 1.00 - based on discussion yesterday we wanted to wait for #888 to land, but not necessarily block on verification of that since the fixes per-branch are not necessarily the same

**Pull request merged**
