### PR TITLE
WRKLDS-1449: Update to Kubernetes v1.31.3

### PR DESCRIPTION
**Pull request by bertinatto**
/assign @atiratree 
/hold
should we merge after branch cut

### CODE REVIEW

**Comment by atiratree** [comment]
Thanks for the update @bertinatto 
/lgtm

branching has just been completed
/hold cancel

**Comment by bertinatto** [comment]
/test integration
```
{Failed;Failed;  I1126 04:57:14.405950   48876 factory.go:193] Registered Plugin "containerd"
I1126 04:57:14.412289   48876 etcd.go:71] etcd already running at http://127.0.0.1:2379
panic: test timed out after 10m0s
running tests:
	TestKMSv2Healthz (3m9s)

goroutine 171746 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/golang/src/testing/testing.go:2366 +0x385
created by time.goFunc
	/usr/lib/golang/src/time/sleep.go:177 +0x2d

goroutine 1 [chan receive, 3 minutes]:
testing.(*T).Run(0xc000afa1a0, {0x3f0f09f?, 0x0?}, 0x416feb0)
	/usr/lib/golang/src/testing/testing.go:1750 +0x3ab
testing.runTests.func1(0xc000afa1a0)
	/usr/lib/golang/src/testing/testing.go:2161 +0x37
testing.tRunner(0xc000afa1a0, 0xc000947b38)
	/usr/lib/golang/src/testing/testing.go:1689 +0xfb
testing.runTests(0xc000900bb8, {0x6a166c0, 0x11, 0x11}, {0x3e48e20?, 0xc000947bb8?, 0x6b6cf80?})
	/usr/lib/golang/src/testing/testing.go:2159 +0x445
testing.(*M).Run(0xc0003e1040)
	/usr/lib/golang/src/testing/testing.go:2027 +0x68b
k8s.io/kubernetes/test/integration/framework.EtcdMain(0xc000947f30)
	/go/src/k8s.io/kubernetes/test/integration/framework/etcd.go:224 +0x388
k8s.io/kubernetes/test/integration/controlplane/transformation.TestMain(...)
	/go/src/k8s.io/kubernetes/test/integration/controlplane/transformation/main_test.go:28
main.main()
	_testmain.go:93 +0x1be
```

**Pull request merged**
