### PR TITLE
Revert "UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain"

### PR DESCRIPTION
**Pull request by tssurya**
This reverts commit b73d7e52585ee1da0d8edff6f3380847f3e8f1c0.

The commit was not supposed to go into master but into the specific sdn-branch.
(Did not know that origin builds only tests)

### CODE REVIEW

**Comment by danwinship** [comment]
I think the commit message has to start "UPSTREAM: 95252:", and then you can put the "revert" afterward? Or maybe use "UPSTREAM: <drop>:" instead? Not sure...
/assign @deads2k

**Comment by tssurya** [comment]
> I think the commit message has to start "UPSTREAM: 95252:", and then you can put the "revert" afterward? Or maybe use "UPSTREAM: :" instead? Not sure...

yea I had to add the [revert] label for the`ci/prow/verify-commits`  to pass, but I am not sure if that is the right one since in the description adding revert means picking a revert from upstream, whereas this patch is not exactly reverted from upstream

UPSTREAM commits are validated against the following regular expression:
  ^UPSTREAM: (revert: )?(([\w\.-]+\/[\w-\.-]+)?: )?(\d+:|<carry>:|<drop>:)

UPSTREAM commit summaries should look like:

  UPSTREAM: <PR number|carry|drop>: description

UPSTREAM commits which revert previous UPSTREAM commits should look like:

  UPSTREAM: revert: <normal upstream format>

Examples of valid summaries:

  UPSTREAM: 12345: A kube fix
  UPSTREAM: <carry>: A carried kube change
  UPSTREAM: <drop>: A dropped kube change
  UPSTREAM: revert: 12345: A kube revert

**Comment by deads2k** [comment]
/lgtm
/approve

thanks for tidying up.

**Comment by tssurya** [comment]
hmm this is strange, why is CI retesting on already passed tests?

**Pull request merged**
