### PR TITLE
UPSTREAM: <drop>: remove creation of openshift-infra ns and recycler SA

### PR DESCRIPTION
**Pull request by atiratree**
#### What this PR does / why we need it:

This change will allow us to simplify the following commit:

UPSTREAM: <carry>: kube-controller-manager: allow running bare kube-controller-manager (https://github.com/openshift/kubernetes/commit/84bab16f21b)

The logic is moved to https://github.com/openshift/cluster-kube-controller-manager-operator/pull/570

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by atiratree** [comment]
/hold
do not merge until openshift/cluster-kube-controller-manager-operator#570 is in

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backports/validated-commits
/remove-label backports/invalidate-commits

**Pull request merged**
