### PR TITLE
UPSTREAM: <carry>: Force using host go always and use host libriaries

### PR DESCRIPTION
**Pull request by aravindhp**
3d22841 introduced a build [failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1756/pull-ci-openshift-windows-machine-config-operator-release-4.11-images/1697673254124130304) of the Windows kubelet: 
```
[1/2] STEP 29/53: RUN make kubelet
KUBE_GIT_VERSION=v1.24.16+7aa7ea9 KUBE_BUILD_PLATFORMS=windows/amd64 make -C kubelet WHAT=cmd/kubelet
make[1]: Entering directory `/build/windows-machine-config-operator/kubelet'
make[2]: Entering directory `/build/windows-machine-config-operator/kubelet'
Makefile.generated_files:61: .make/go-pkgdeps.mk: No such file or directory
+++ [0905 19:33:37] Building go targets for linux/amd64
/build/windows-machine-config-operator/kubelet/hack/lib/golang.sh: line 351: KUBE_STATIC_LIBRARIES[@]: unbound variable
!!! [0905 19:33:37] Call tree:
!!! [0905 19:33:37]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0905 19:33:37] Call tree:
!!! [0905 19:33:37]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[2]: *** [.make/go-pkgdeps.mk] Error 1
make[2]: Leaving directory `/build/windows-machine-config-operator/kubelet'
make[1]: *** [generated_files] Error 2
make[1]: Leaving directory `/build/windows-machine-config-operator/kubelet'
make: *** [kubelet] Error 2
Error: building at STEP "RUN make kubelet": while running runtime: exit status 2
```

This PR fixes the build failure by checking the array before traversing it.

### CODE REVIEW

**Review by soltysh — COMMENTED** [review]
The PR looks good to me, but can you match the commit message with the one from https://github.com/openshift/kubernetes/commit/3d22841739a62a69e7960a3fd7194eb2f3f8f956 this will tell us to squash both together.

**Comment by aravindhp** [comment]
/retitle UPSTREAM: <carry>: Force using host go always and use host libriaries

**Comment by aravindhp** [comment]
/retitle UPSTREAM: <carry>: Force using host go always and use host libriaries

**Comment by aravindhp** [comment]
/retitle "UPSTREAM: <carry>: Force using host go always and use host libriaries"

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Comment by aravindhp** [comment]
/hold

Trying to figure out if the fix needs to be introduced into master first.

**Comment by aravindhp** [comment]
/close

Will be easier to open a new PR

**Pull request closed without merging**
