### PR TITLE
stable 20160411

### PR DESCRIPTION
**Pull request by deads2k**
rebased fork.

### CODE REVIEW

**Comment by soltysh** [comment]
@miminar @legionus @sgallagher this is the other part of the rebase

**Comment by soltysh** [comment]
@deads2k or rather @liggitt  did we try to upstream [Allow overriding default generators for run](https://github.com/openshift/kubernetes/pull/15/commits/bd89afe471cc98b805455838ba14b7dd3ac90540)? I can't seem to find any PR as such.

**Comment by soltysh** [comment]
LGTM

**Comment by deads2k** [comment]
Origin pull merged

**Pull request closed without merging**
