### PR TITLE
Stable 20160211

### PR DESCRIPTION
**Pull request by pweil-**
Branch is in a stable state.  

Some specific changes to pay attention to:

*  Tests are passing so long as you comment out https://github.com/openshift/kubernetes/blob/e4d9fb6906dbef5a069e5f45ee64a49d20418c2e/pkg/api/ref_test.go#L42-42 which is necessary for running tests in vendored kube
*  I had to update two event validation tests: https://github.com/openshift/kubernetes/commit/75ffc1216caacd4347dac8fa979b915b1c10d251
*  please take a look at the final version of conversions/deep copies to make sure I didn't mess anything up with the carries we have for "back and forth" to maintain the MetadataVolumeSource

Other items of note:

*  Fixed all gofmt issues
*  Fixed all boilerplate issues
*  Regenerated codegen, swagger docs, api docs in the final commit
*  Squashed new SCC commits and v1beta3 commits into the existing ones

Final state of `hack/verify-all.sh`

```
$ hack/verify-all.sh 
Running in the silent mode, run with -v if you want to see script logs.
Skipping hack/../hack/verify-all.sh
Verifying hack/../hack/verify-api-reference-docs.sh
SUCCESS
Verifying hack/../hack/verify-boilerplate.sh
SUCCESS
Verifying hack/../hack/verify-codecgen.sh
FAILED
Verifying hack/../hack/verify-codegen.sh
SUCCESS
Verifying hack/../hack/verify-description.sh
FAILED
Verifying hack/../hack/verify-generated-conversions.sh
FAILED
Verifying hack/../hack/verify-generated-deep-copies.sh
SUCCESS
Verifying hack/../hack/verify-generated-docs.sh
SUCCESS
Skipping hack/../hack/verify-generated-protobuf.sh
Verifying hack/../hack/verify-generated-swagger-docs.sh
SUCCESS
Skipping hack/../hack/verify-godep-licenses.sh
Skipping hack/../hack/verify-godeps.sh
Verifying hack/../hack/verify-gofmt.sh
SUCCESS
Verifying hack/../hack/verify-import-boss.sh
SUCCESS
Skipping hack/../hack/verify-linkcheck.sh
Verifying hack/../hack/verify-swagger-spec.sh
SUCCESS
Verifying hack/../hack/verify-symbols.sh
SUCCESS
Verifying hack/../hack/verify-flags-underscore.py
SUCCESS
```

@deads2k @liggitt @soltysh @miminar @kargakis

### CODE REVIEW

**Comment by pweil-** [comment]
I'm guessing the easiest thing to do here is to copy over what I have in origin to update this PR since there were a couple of more upstreams that were added.

**Comment by kargakis** [comment]
@pweil- please document any additional steps that rebasers need to do when working with the fork.

**Comment by pweil-** [comment]
> @pweil- please document any additional steps that rebasers need to do when working with the fork.

1.  say prayers
2.  light candles
3.  ...
4.  hope @deads2k is on IRC

But seriously, I have some decent notes and will write them up.

**Comment by soltysh** [comment]
> 1. say prayers
> 2. light candles

lol, will this work always?

**Pull request merged**
