### PR TITLE
Bug 1952224: UPSTREAM: 102344: Keep pod worker running until pod is truly complete

### PR DESCRIPTION
**Pull request by rphillips**
Backports pod lifecycle fixes

ref: [103668](https://github.com/kubernetes/kubernetes/pull/103668) and [102344](https://github.com/kubernetes/kubernetes/pull/102344)

### CODE REVIEW

**Comment by ehashman** [comment]
> nodes/ip-10-0-141-219.us-east-2.compute.internal/journal.gz:Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: E0709 21:04:26.513873    1600 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

We should look into that if possible.

**Comment by ehashman** [comment]
Full panic:

```
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: E0709 21:04:26.513873    1600 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: goroutine 207643 [running]:
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x4221200, 0x761c740)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: panic(0x4221200, 0x761c740)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /usr/lib/golang/src/runtime/panic.go:965 +0x1b9
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).convertStatusToAPIStatus(0xc0008e8000, 0xc0026d2c00, 0x0, 0xc0092435a0)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:1436 +0x5a
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).generateAPIPodStatus(0xc0008e8000, 0xc0026d2c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:1371 +0x1d1
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncTerminatedPod(0xc0008e8000, 0x52569b0, 0xc002953700, 0xc0026d2c00, 0x0, 0x0, 0x0)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1820 +0x426
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0xc003423ee0, 0xc000b79c20, 0xc0026d2c00, 0xc003423db8, 0xc0052f0120, 0x15)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:713 +0x386
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0xc000b79c20, 0xc004bb85a0)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:730 +0x35e
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1(0xc000b79c20, 0xc004bb85a0)
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:610 +0x6d
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]:         /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.21.1/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:608 +0xe58
```

**Comment by ehashman** [comment]
https://github.com/openshift/kubernetes/blob/bb28addd3045e1d160728de86d58db7ad5a16139/pkg/kubelet/kubelet_pods.go#L1436

Was podStatus nil then?

**Comment by ehashman** [comment]
`Jul 09 21:04:26.516585 ip-10-0-141-219.us-east-2.compute.internal hyperkube[1600]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncTerminatedPod(0xc0008e8000, 0x52569b0, 0xc002953700, 0xc0026d2c00, 0x0, 0x0, 0x0)`

`syncTerminatedPod` was called with a nil podStatus, here: https://github.com/openshift/kubernetes/blob/bb28addd3045e1d160728de86d58db7ad5a16139/pkg/kubelet/pod_workers.go#L710-L713

We hit this case when `update.Options.RunningPod != nil` and `update.WorkType == TerminatedPodWork`.

Let me see if I can find an instance of this in upstream CI and I'll file a bug.

**Comment by smarterclayton** [comment]
Can you add a temporary commit here bumping the minimum klog level to 4 in the kubelet (that we'll remove once we have a few runs with it)?   

Running pods should terminate and then stop, not move to terminated.  So something is getting into "terminated but should never be in any other work type than terminating.

**Comment by ehashman** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/851/pull-ci-openshift-kubernetes-master-e2e-aws-fips/1414584954561499136

The AWS FIPS run is the one that's reproing this.

**Comment by smarterclayton** [comment]
Going to open a test PR for the medium fix against origin and if it works will take it upstream.

**Comment by rphillips** [comment]
Not seeing fips crashes anymore

**Comment by rphillips** [comment]
Upstream reported test failure: https://github.com/kubernetes/kubernetes/issues/103623#issuecomment-881449350

**Pull request closed without merging**
