### PR TITLE
UPSTREAM: <carry>: fix machine-os-content image build

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Comment by rphillips** [comment]
@soltysh I think we should pick your readme change into https://github.com/openshift/kubernetes/pull/1106 so we fix this all in one merge

**Comment by soltysh** [comment]
> @soltysh I think we should pick your readme change into #1106 so we fix this all in one merge

@rphillips that's fine as well, if you can update your PR and pick that rebase doc update from mine, double check the FROM are picked from this as well, if you get it green by tomorrow when I'm back online I'll tag it

I'm still not sure if we need `machine-config-daemon` b/c from what I was checking we're running that as any other operator through an image and not directly, only crio and kubelet are required, but I might be wrong

**Comment by soltysh** [comment]
This currently builds on top of #1106 which should merge first.

**Pull request closed without merging**
