### PR TITLE
Rebase 3.11 beta2

### PR DESCRIPTION
**Pull request by deads2k**
Messy.  Here's the picklist: https://docs.google.com/spreadsheets/d/1LJMgJfVTcV8uWAcEqvBf7JWpu_0pLNq_8LwLvXH1sO8/edit#gid=0

Highlights.

 1.  Resolved, no longer needed.  62c8b9711da `UPSTREAM: <carry>: Tolerate node ExternalID changes with no cloud provider` DOES NOT APPLY.  @DirectXMan12   I'm going to try to continue without it, but it's likely a blocker/regression for the rebase!
 2. 7d109af47e2 `UPSTREAM: <carry>: disable local storage isolation feature gate` DOES NOT APPLY,  @sjenning I'm going to try to continue without it, but it's likely a blocker/regression for the rebase!
 3. f526af8a087 `UPSTREAM: <carry>: allow oc kubeconfig loading to have our flags and errors` dropped and will be reimplemented in origin during the next phase.
 4. ef132e27c5c `UPSTREAM: <carry>: add RawConfig to factory for commands modifying raw kubeconfig files` dropped and should not be needed again, but may be reimplemented
 5. Resolved, picked because we can't drop yet.  c5ff3ff1737 `UPSTREAM: <drop>: make RootFsInfo error non-fatal on start` dropped per commit comment.  @liggitt 
 6. 530c2883e8e `UPSTREAM: <drop>: stop wrapping --sort-by value in {}` dropped per commit comment. @juanvallejo
 7. e4c60d60dbe `UPSTREAM: <carry>: keep set working on internal types` dropped.  may need re-implemenation. @soltysh 
 8. Resolved, picked for comment below.  5b29722154a `UPSTREAM: <carry>: add kubelet timeouts` dropped.  This looked really weird/useless.  @soltysh 
 9. 6b97a4272c2 `UPSTREAM: <carry>: patch scheduler to apply defaults. drop once we run separate scheduler` Looks like defaults are set on the options struct now.  @aveshagarwal  to confirm

Worthy of re-review due to conflicts:
 - [ ] 622e3371663 `UPSTREAM: <carry>: Allow overriding default generators for run` @soltysh 
 - [ ] 94d4fb68a6f `UPSTREAM: <carry>: add flag for running bare kube-controller-manager` @sttts 
 - [ ] f84a2980eb2 `UPSTREAM: <carry>: hack in working autoscale reference for oc autoscale` @DirectXMan12 
 - [ ] c5e40756c8b `UPSTREAM: <carry>: Short-circuit HPA oapi/v1.DC` @DirectXMan12 
 - [ ] 1b9976d6175 `UPSTREAM: <carry>: filter daemonset nodes by namespace node selectors` @mfojtik 
 - [ ] d27f1195837 `UPSTREAM: <carry>: inject new parameter for image resolution into kubectl set image` @mfojtik 
 - [ ] 7b3c6315923 `UPSTREAM: <carry>: rewrite unstructured objects on the CLI to avoid oapi` @soltysh

### CODE REVIEW

**Comment by liggitt** [comment]
> 62c8b97 `UPSTREAM: <carry>: Tolerate node ExternalID changes with no cloud provider`

kubelet dropped its self-deletion behavior in 1.11. I think we can drop this now

> c5ff3ff `UPSTREAM: <drop>: make RootFsInfo error non-fatal on start`

this will keep our CI from running in our env where we put the kubelet root dir on a bindmounted location. @sjenning @derekwaynecarr need to determine what to do with this in https://github.com/openshift/origin/issues/19948

> 5b29722 `UPSTREAM: <carry>: add kubelet timeouts`

that was a backstop to keep the kubelet from permanently leaking connections on hung exec/attach/portforward types of calls

**Comment by deads2k** [comment]
@aveshagarwal  commit in the description to consider.

**Comment by deads2k** [comment]
@liggitt yeah hack/local-up-cluster.sh runs

**Comment by deads2k** [comment]
Starting here.  I will take post-merge comments, fix the up in commits marked for squash, then squash them up in the next 1.11 rebase closer to kube GA.

**Comment by soltysh** [comment]
> Resolved, picked for comment below. 5b29722 UPSTREAM: <carry>: add kubelet timeouts dropped. This looked really weird/useless. @soltysh

Drop it, and we'll see what happens. I'll add a note at the back of my head about it, if some weird timeouts starts happening.

**Comment by soltysh** [comment]
> 622e337 UPSTREAM: <carry>: Allow overriding default generators for run @soltysh

LGTM

**Comment by soltysh** [comment]
> d27f119 UPSTREAM: <carry>: inject new parameter for image resolution into kubectl set image @mfojtik

I wonder if we could just implement our own version of the `set image` command wrapping around the k8s version. This approach would save us one patch in favor of just having the command baked into openshift.

**Comment by soltysh** [comment]
> 7b3c631 UPSTREAM: <carry>: rewrite unstructured objects on the CLI to avoid oapi @soltysh

LGTM

**Comment by DirectXMan12** [comment]
For posterity:

> Resolved, no longer needed. 62c8b97 UPSTREAM: <carry>: Tolerate node ExternalID changes with no cloud provider DOES NOT APPLY. @DirectXMan12 I'm going to try to continue without it, but it's likely a blocker/regression for the rebase!

Original PR here: https://github.com/openshift/origin/pull/6310

I think this was a hack to support upgrading when we changed the way baremetal nodes were identified.  ExternalID is deprecated and apparently unused in 1.11 anyway, as per https://github.com/kubernetes/kubernetes/pull/61877

**Comment by soltysh** [comment]
> 530c288 UPSTREAM: <drop>: stop wrapping --sort-by value in {} dropped per commit comment. @juanvallejo

LGTM

**Comment by mfojtik** [comment]
>  1b9976d UPSTREAM: <carry>: filter daemonset nodes by namespace node selectors @mfojtik

LGTM

> 1b9976d UPSTREAM: <carry>: filter daemonset nodes by namespace node selectors @mfojtik

LGTM

**Comment by sjenning** [comment]
> 7d109af UPSTREAM: <carry>: disable local storage isolation feature gate DOES NOT APPLY, @sjenning I'm going to try to continue without it, but it's likely a blocker/regression for the rebase!

https://github.com/openshift/kubernetes/pull/61 rebase this carry for 1.11

**Pull request merged**
