### PR TITLE
terminate long-running requests on server's termination

### PR DESCRIPTION
**Pull request by p0lyn0mial**
It turns out that closing the server always takes `ShutdownTimeout`. In our case, it is always 60 seconds. 

termination-always-60s

However, it wasn’t always like that. Back in the old days the http server didn’t wait for in-flight requests at all and close them ungracefully. The issue was fixed in go 1.16. Now it waits until all pending requests are finished. It turns out that’s exactly what holds the server for `ShutdownTimeout`. The long-running requests like for example the `WATCH` requests which are not hijacked must be torn down by the server.

It also turns out that closing the long-running requests is not that easy. They might be blocked on various things like `io.Read`. So, instead of trying to identify all current and future issues, we provide a filter that ensures termination of long-running requests.

The new filter runs two additional goroutines. One for running the request and the second one for intercepting the termination signal and propagating it to the requests. If the request is not terminated within 5 seconds it will be forcefully killed.

TODO: 
 - move it upstream

### CODE REVIEW

**Comment by smarterclayton** [comment]
For a large number of long running requests, closing the stream coming from the kube side (the watch, the kubelet log stream, the exec session stream, the portforward downstream) should be enough to terminate the long running request.  Why would we not handle this via the request context and context cancellation, and the various behaviors of the loops deep in the kubelet?  I guess this isn't the design I expected to see, and would like to know what alternatives were considered and what their drawbacks were?

**Comment by p0lyn0mial** [comment]
> Why would we not handle this via the request context and context cancellation

@smarterclayton this is exactly what this PR does. The new filter closes the request's context after receiving the signal. The filter will only terminate requests that didn't complete within 5 seconds. It turns out that the long-running request might actually deadlock in various places.

**Comment by p0lyn0mial** [comment]
It looks like the fix [is real](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/799/pull-ci-openshift-kubernetes-master-e2e-gcp-upgrade/1402628222096510976), now it takes `6s` vs `60s`:

Screenshot 2021-06-10 at 09 55 21

**Pull request closed without merging**
