### PR TITLE
Bug 2026380: Image policy should mutate DeploymentConfigs, StatefulSets, and new CronJobs

### PR DESCRIPTION
**Pull request by dmage**
#### What type of PR is this?

/kind bug
/kind regression

This is a cherry-pick of #1073.

#### What this PR does / why we need it:

After we merged https://github.com/openshift/apiserver-library-go/pull/50 we found that some objects are not known by the image policy admission plugin. This PR updates the plugin so that it can mutate these objects.

#### Which issue(s) this PR fixes:

Fixes BZ 2026380.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xiuwang** [comment]
Test passed on 4.6.0-0.ci.test-2022-01-14-062049-ci-ln-riv684k-latest

/lgtm
/label qe-approved

**Review by soltysh — APPROVED** [review]
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Comment by xiuwang** [comment]
@wangke19 Could you please help add cherry-pick-approved label? Thanks

**Pull request merged**
