### PR TITLE
Bug 1978528: UPSTREAM: <carry>: bump cadvisor for 2957, 2999 and 2979 upstream patches

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=1978528, https://bugzilla.redhat.com/show_bug.cgi?id=2016175

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by harche** [comment]
cc @swghosh @sairameshv

**Comment by rphillips** [comment]
this should be a <carry> since we are backporting it.

**Comment by harche** [comment]
> this should be a `<carry>` since we are backporting it.

Done. Thanks.

**Pull request merged**
