### PR TITLE
UPSTREAM: 118662: Set the node-ips annotation correctly with CloudDualStackNodeIPs

### PR DESCRIPTION
**Pull request by mkowalski**
Contributes-to: [OPNET-230](https://issues.redhat.com//browse/OPNET-230)
Contributes-to: [OPNET-323](https://issues.redhat.com//browse/OPNET-323)

### CODE REVIEW

**Comment by mkowalski** [comment]
/retitle UPSTREAM: 118662: Set the node-ips annotation correctly with CloudDualStackNodeIPs

**Comment by MaysaMacedo** [comment]
Contributes-to: [OSASINFRA-1938](https://issues.redhat.com/browse/OSASINFRA-1938)

LGTM

**Pull request closed without merging**
