### PR TITLE
OCPBUGS-7555: UPSTREAM: <carry>: add default kubelet sysctls within rpm

### PR DESCRIPTION
**Pull request by rphillips**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR adds sysctls to the operating system via the RPM to default some options for the Kubelet. This will allow us to enable protectKernelDefaults by default via https://github.com/openshift/machine-config-operator/pull/3556.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rphillips** [comment]
I changed the sysctl run level to 50- instead of 75-. Correlates better with what is installed.

**Review by soltysh — COMMENTED** [review]
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Review by soltysh — APPROVED** [review]
/retest-required

**Pull request merged**
