### PR TITLE
Bug 1950010: UPSTREAM: <carry>: apirequestcount: smear out CR updates over interval

### PR DESCRIPTION
**Pull request by sttts**
To avoid CPU spikes every interval.

### CODE REVIEW

**Comment by deads2k** [comment]
sure, why not
/lgtm

**Comment by sttts** [comment]
/override ci/prow/e2e-aws-serial 

This has been green before and flakes.

**Comment by sttts** [comment]
/override ci/prow/k8s-e2e-conformance-aw

AWS has quota issues, and we have seen enough test jobs green to be sure this works. Kube conformance is also run through origin and is green. No need for double confirmation.

**Pull request merged**
