### PR TITLE
[release-4.8] bug 1981633: UPSTREAM: <carry>: prevent the kubecontrollermanager service-ca from getting less secure

### PR DESCRIPTION
**Pull request by deads2k**
manually picked to ensure that the openshift/api was pulled from release-4.8, not master.

### CODE REVIEW

**Comment by deads2k** [comment]
clean pick from master.  applying label.

**Comment by yaoli-redhat** [comment]
/lgtm /qe-approved 
https://bugzilla.redhat.com/show_bug.cgi?id=1981633#c2

**Comment by deads2k** [comment]
/override ci/prow/e2e-gcp-upgrade

upgrade is failing on a widespread, known problem

**Comment by sdodson** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1983200 on etcd failing to restore quorum

**Pull request merged**
