### PR TITLE
Bug 1958371: UPSTREAM: 98424: register all pending pod deletions and check for kill

### PR DESCRIPTION
**Pull request by ehashman**
https://bugzilla.redhat.com/show_bug.cgi?id=1958371

### CODE REVIEW

**Comment by ehashman** [comment]
Unit test flake on issue fixed by #767, I will backport...

**Comment by ehashman** [comment]
Unit test flake is https://github.com/kubernetes/kubernetes/pull/96048 ... guess I'll backport that too

**Comment by ehashman** [comment]
One more flake fix for this

**Review by mrunalp — APPROVED** [review]

**Comment by derekwaynecarr** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.50

approved

**Pull request merged**
