### PR TITLE
Update to Kubernetes 1.27.3

### PR DESCRIPTION
**Pull request by bertinatto**
Followed steps from https://github.com/openshift/kubernetes/blob/master/REBASE.openshift.md#updating-with-git-merge.

/assign @soltysh

### CODE REVIEW

**Comment by bertinatto** [comment]
> /close Replaced by #1614, which was auto-generated.

I'm sorry, I closed the wrong PR.

**Comment by soltysh** [comment]
/override ci/prow/verify-commits
this never passes on k8s bump 

/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
/hold 
this is blocked on https://issues.redhat.com/browse/OCPBUGS-15226

**Comment by soltysh** [comment]
With https://github.com/openshift/ovn-kubernetes/pull/1717 in let's try
/test e2e-aws-ovn-serial

**Pull request merged**
