### PR TITLE
OCPBUGS-44513: Bump k8s api to 1.29.10

### PR DESCRIPTION
**Pull request by jerpeter1**
Bump kubernetes version to 1.29.10
/cc @bertinatto

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/remove-label backports/unvalidated-commits
/label backports/validated-commits
/lgtm

**Comment by bertinatto** [comment]
/hold
until we find out if the distroless image bump will break meta jobs

**Comment by jerpeter1** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-metal-ipi-ovn-bm

**Comment by jerpeter1** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-bm

**Comment by jerpeter1** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.16-e2e-metal-ipi-ovn-bm

**Pull request merged**
