### PR TITLE
OCPBUGS-32296: Bump K8s api to 1.29.4

### PR DESCRIPTION
**Pull request by sairameshv**
/assign @soltysh

### CODE REVIEW

**Comment by flavianmissi** [comment]
@sairameshv @soltysh can we also link this one to bug https://issues.redhat.com/browse/OCPBUGS-31716?

**Comment by sairameshv** [comment]
> @sairameshv @soltysh can we also link this one to bug https://issues.redhat.com/browse/OCPBUGS-31716?

Done !!

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/remove-label backports/unvalidated-commits
/label backports/validated-commits

**Pull request merged**
