### PR TITLE
[4.12] OCPBUGS-5769: scc admission - seccomp profiles fix

### PR DESCRIPTION
**Pull request by stlaz**
Backport

/assign @ibihim

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve
/remove-label  backports/unvalidated-commits
/label  backports/validated-commits

**Review by ibihim — APPROVED** [review]
/lgtm

**Comment by dhellmann** [comment]
We are also tracking this for OCPBUGS-5850 in MicroShift.

/retest-required

**Pull request merged**
