### PR TITLE
DO NOT MERGE - For review only

### PR DESCRIPTION
**Pull request by liggitt**
Contains the carries and unmerged upstream picks from https://github.com/openshift/kubernetes/commits/stable-20160309

in addition to commits already merged upstream, I dropped: 
* 1101efb15da9f4e46923e5796525e8f6af734aef `UPSTREAM: <carry>: allow specific, skewed group/versions` - replaced by 21909 upstream
* 2cc150c59f6752875672e02df47556bf40ecd795 `UPSTREAM: <carry>: Keep default generator for run 'run-pod/v1'` - will replace with oc-specific overrides
* 055d8eccf9942063113b174b98535f82618327db `UPSTREAM: 12221: Allow custom namespace creation in e2e framework` - replaced by 20808 upstream, @soltysh, can you confirm that does what we need?
* 4267088385ca1599ffefd9bf1b45c4738180d565 `UPSTREAM: 20157: Test specific generators for kubectl` - not needed if kubectl run behaves like upstream
* b03a73a566ec8e73e062c67c2511a6dab1e936ec `UPSTREAM: <carry>: enable daemonsets by default` - replaced by 21130 upstream
* b59c3ea3fa8089c03d7268a8ea5ae4864d5a972d `remove most of the latest package; it should go away completely` - @deads2k looks like this was vestigial debug bits
* da636b2eb217f97a95c1f578b3fc324aa0abc938 `UPSTREAM: <drop>: update generated code, swagger, and api docs after rebase` - replaced with 83a3410097c982e4bae02429de00ab88aafdd0b0
* e4d9fb6906dbef5a069e5f45ee64a49d20418c2e `UPSTREAM: 20706: register internal types with scheme for reference unit test` - @deads2k this was causing a panic in unit tests, I'll revisit when I get into origin

@deads2k, please verify these three commits were satisfied by merges upstream:
* ad2626dda3353613bea33878c5b61df0e52f4811 `UPSTREAM: 20968: make partial resource detection work for singular matches`
* cec8803fc79f942613aaf444bdbae811f0167bb3 `UPSTREAM: 20829: Union rest mapper` - superceded by 21272 upstream
* ef2037ac27a7fd2da8a4a9d805bbf3679360d482 `UPSTREAM: 20814: type RESTMapper errors to better handle MultiRESTMapper errors`

to review:
* d49dd0cac097f7a1d6c2b79c8246f4c362d771ab fixes up the SCC generated client and deep copies, so the generation scripts can be used again - @pweil- PTAL
* aad3a21f3ac9eaf7ae55dc005419a82cd6f2e438 moves the hand-written conversion out of the generated file and updates generated conversions/copies

### CODE REVIEW

**Comment by deads2k** [comment]
> b59c3ea remove most of the latest package; it should go away completely - @deads2k looks like this was vestigial debug bits

agreed

**Comment by deads2k** [comment]
> e4d9fb6 UPSTREAM: 20706: register internal types with scheme for reference unit test - @deads2k this was causing a panic in unit tests, I'll revisit when I get into origin

You'll need this or something in origin.

**Comment by deads2k** [comment]
> @deads2k, please verify these three commits were satisfied by merges upstream:

fine to remove.

**Comment by soltysh** [comment]
> 055d8ec UPSTREAM: 12221: Allow custom namespace creation in e2e framework - replaced by 20808 upstream, @soltysh, can you confirm that does what we need?

Confirmed.

**Comment by liggitt** [comment]
Pushed as https://github.com/openshift/kubernetes/commits/release-1.2-stable-20160309
Based on https://github.com/openshift/kubernetes/commits/release-1.2

**Pull request closed without merging**
