### PR TITLE
Bug 1881688: UPSTREAM: 94984: check readyz before adding endpoint for kube-apiserver

### PR DESCRIPTION
**Pull request by deads2k**
probably leading to messages that dan williams will post.

### CODE REVIEW

**Comment by dcbw** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/279/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1308197296986394624

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/279/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1308197296986394624/artifacts/e2e-aws-ovn/pods/openshift-kube-apiserver_kube-apiserver-ip-10-0-135-248.us-west-1.compute.internal_kube-apiserver.log

W0922 01:26:24.685077      19 patch_genericapiserver.go:119] Request to "/apis/discovery.k8s.io/v1beta1" (source IP 10.0.249.79:23149, user agent "kube-controller-manager/v1.19.0 (linux/amd64) kubernetes/7e8389f/system:serviceaccount:kube-system:namespace-controller") before server is ready, possibly a sign for a broken load balancer setup.

**Comment by dcbw** [comment]
@deads2k commit seems to need a : between UPSTREAM and the PR#

**Comment by sttts** [comment]
Misnamed commit.

**Comment by deads2k** [comment]
was green and tagged.  fixed commit name.  No conflict with abu's metrics.  Merging.

**Pull request merged**
