### PR TITLE
Bug 1993753: UPSTREAM: 104348: Pass additional flags to subpath mount to avoid fla…

### PR DESCRIPTION
**Pull request by dobsonj**
/cc @openshift/storage

### CODE REVIEW

**Comment by duanwei33** [comment]
I'm following JIRA issue DPTP-660 to do the pre-merge verification. Used the cluster-bot launching an env with the still open but Dev-approved PR(s).
The bug is pre-merge verified. So per JIRA issue DPTP-660's Description process, adding QE lgtm:
/lgtm

**Comment by hardys** [comment]
> I'm following JIRA issue [DPTP-660](https://issues.redhat.com/browse/DPTP-660) to do the pre-merge verification. Used the cluster-bot launching an env with the still open but Dev-approved PR(s).
> The bug is pre-merge verified. So per JIRA issue [DPTP-660](https://issues.redhat.com/browse/DPTP-660)'s Description process, adding QE lgtm:
> /lgtm

[patch-manager] I believe we also require the qe-approved label, but I'm taking this comment as approval and will apply the label myself :)

**Comment by hardys** [comment]
[patch-manager] #940 landed and was verified, this PR has qe-approved from pre-merge testing, adding bugzilla/valid-bug and cherry-pick-approved labels

**Pull request merged**
