### PR TITLE
Bug 1879607: UPSTREAM: 95252: Kube-proxy: Perf-fix: Shrink INPUT chain

### PR DESCRIPTION
**Pull request by tssurya**
**What type of PR is this?**

backport for https://github.com/kubernetes/kubernetes/pull/95252

**What this PR does / why we need it**:

In #56164, we had split the reject rules for non-ep existing services
into KUBE-EXTERNAL-SERVICES chain in order to avoid calling KUBE-SERVICES
from INPUT. However in #74394 KUBE-SERVICES was re-added into INPUT.

As noted in #56164, kernel is sensitive to the size of INPUT chain. This
patch refrains from calling the KUBE-SERVICES chain from INPUT and FORWARD,
instead adds the lb reject rule to the KUBE-EXTERNAL-SERVICES chain which will be
called from INPUT and FORWARD.

**Special notes for your reviewer**:

Conflicts:
    pkg/proxy/iptables/proxier.go
Minor conflict due to 1f7ea1656053aa261dd977f058c15352c6de7e95

Needs to be backported to oc-4.4

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm
though you'll need to look at the failed tests

It looks like other people are doing
/cherry-pick 4.6
for 4.6 backports. I think for 4.5 and 4.4 you should use the older process, where you patch the vendored copy of kubernetes in openshift/origin directly, rather than cherry-picking here first.

**Comment by tssurya** [comment]
> /lgtm
> though you'll need to look at the failed tests

ack, looking into them
> 
> It looks like other people are doing
> /cherry-pick 4.6

+1

> for 4.6 backports. I think for 4.5 and 4.4 you should use the older process, where you patch the vendored copy of kubernetes in openshift/origin directly, rather than cherry-picking here first.

wokay, I'll take a look at how others did this and follow the procedure. thanks once again for the quick approval and response/help as usual :)

**Comment by tssurya** [comment]
there is something wrong with the e2e-agnostic-cmd job in general: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-kubernetes-master-e2e-agnostic-cmd ; doesn't seem related to this patch

/test e2e-agnostic-cmd

**Pull request merged**
