### PR TITLE
OCPBUGS-14930: UPSTREAM 119745: Local PV Stress test: don't fail on deleting missing PV

### PR DESCRIPTION
**Pull request by tsmetana**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:
Fixes flaky local PV stress tests.

#### Which issue(s) this PR fixes:

Fixes https://issues.redhat.com/browse/OCPBUGS-14930

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
/hold 
why is this needed, it should already be in master, now that we have k8s 1.29?

**Comment by tsmetana** [comment]
I didn't notice the PR is that old... We really seem to have the fix already inherited from the rebase in master: https://github.com/openshift/kubernetes/blob/master/test/e2e/storage/persistent_volumes-local.go#L531

**Comment by tsmetana** [comment]
Closing. The bug was fixed by the k8s rebase.

**Pull request closed without merging**
