### PR TITLE
OCPBUGS-15246: Bump to k8s 1.26.6

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
[x] Merge commit
[x] Conflict resolution commit
[x] apiserver-library-go bump pointing to the right commit

/lgtm

**Comment by soltysh** [comment]
/remove-label backports/unvalidated-commits
/label backports/validated-commits

Since https://github.com/openshift/kubernetes/pull/1609 merge this is good to go
/remove-label jira/invalid-bug
/remove-label jira/valid-bug

/label backport-risk-assessed

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
