### PR TITLE
WIP: get more logs from OpenStack Cinder

### PR DESCRIPTION
**Pull request by jsafrane**
Debug https://bugzilla.redhat.com/show_bug.cgi?id=2062148

### CODE REVIEW

**Comment by mandre** [comment]
Aha! We're getting somewhere:
```
E0309 20:00:43.741046      17 openstack.go:940] "BlockStorage API V3 not available" err="unable to initialize cinder v3 client for region RegionOne: Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:\"1c0b1cd23e6d449e8e837c6050c31358\", Region:\"RegionOne\", RegionID:\"RegionOne\", Interface:\"public\", URL:\"https://volume.rdo.mtl2.vexxhost.net/v3/0693e2bb538c42b79a49fe6d2e61b0fc\"}, tokens.Endpoint{ID:\"ca9181d4d1aa4121895ed77e47140254\", Region:\"RegionOne\", RegionID:\"RegionOne\", Interface:\"public\", URL:\"https://volume.rdo.mtl2.vexxhost.net/v3/0693e2bb538c42b79a49fe6d2e61b0fc\"}}"
```
From https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1208/pull-ci-openshift-kubernetes-master-e2e-openstack/1501627732201574400/artifacts/e2e-openstack/gather-extra/artifacts/pods/openshift-kube-apiserver_kube-apiserver-9k6gnpl8-b20f0-vlgnp-master-2_kube-apiserver.log

**Comment by jsafrane** [comment]
/close
We got the logs we needed.

**Pull request closed without merging**
