### PR TITLE
UPSTREAM: 121124: Remove problematic Dbus restart test

### PR DESCRIPTION
**Pull request by kwilczynski**
#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:

Restarting the Dbus broker service at runtime is generally not recommended or supported according to the feedback from the systemd maintainers.

Many systemd components (but also other software and services) that rely on Dbus wouldn't reconnect to a new Unix socket following the Dbus broker restart. This can lead to anything from authentication timeouts (since the systemd-logind and the polkitd services would be impacted) to the system generally broken following the Dbus broker restart. 

Different software might handle this differently and choose to reconnect on a socket write or read timeout. However, systemd at large is not one of these.

Given that tests are nowadays commonly run on either Googe Container-optimised OS (COS) or Fedora CoreOS, the addition of the Dbus broker restart has unwelcome side effects on these platforms.

Thus, remove a problematic test that performs Dbus broker restart and, in doing so, fix several currently failing tests on platforms that do not handle Dbus service restart gracefully.

#### Which issue(s) this PR fixes:

Fixes #121124

#### Special notes for your reviewer:

NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by rphillips** [comment]
Commit message needs to be updated to be:

```
UPSTREAM: <carry>: ...
```

**Comment by kwilczynski** [comment]
Hi @rphillips,

> Commit message needs to be updated to be:
> 
> ```
> UPSTREAM: <carry>: ...
> ```

Done.

**Review by sairameshv — COMMENTED** [review]
Should we wait for this change to land in the next rebase?

**Comment by sairameshv** [comment]
/lgtm

I would leave to @rphillips , @soltysh for the approval !!

**Comment by kwilczynski** [comment]
What needs to be done here to help it through the finish line?

@mrunalp, anything left I need to do?

**Review by soltysh — CHANGES_REQUESTED** [review]
I don't see this test being executed nowhere in origin (our main test repository), nor anywhere here (https://github.com/openshift/origin/blob/master/test/extended/util/annotate/generated/zz_generated.annotations.go)  so unless I see an explicit failure this is trying to fix, rather than proactively picking upstream PRs I don't see any value in bringing this down to our fork. 
/hold

**Comment by kwilczynski** [comment]
> I don't see this test being executed nowhere in origin (our main test repository), nor anywhere here (https://github.com/openshift/origin/blob/master/test/extended/util/annotate/generated/zz_generated.annotations.go) so unless I see an explicit failure this is trying to fix, rather than proactively picking upstream PRs I don't see any value in bringing this down to our fork.

@soltysh, I see the following there (from [test/extended/util/annotate/generated/zz_generated.annotations.go#L1426](https://github.com/openshift/origin/blob/master/test/extended/util/annotate/generated/zz_generated.annotations.go#L1426)):

```
"[sig-node][Disruptive][Feature:KubeletGracefulShutdown] Kubelet with graceful shutdown configuration should respect pods termination grace period": " [Serial]",
```

Which should include the test we want to remove? Or, would this not match the annotation?

**Comment by soltysh** [comment]
This will be included in 1.29 bump in #1810

**Pull request closed without merging**
