### PR TITLE
Bug 1897754: HPA: Ignore deleted pods.

### PR DESCRIPTION
**Pull request by joelsmith**
xref https://github.com/kubernetes/kubernetes/pull/95560

### CODE REVIEW

**Comment by soltysh** [comment]
@joelsmith is there any particular reason you want to pick this before we land 1.20 k8s bump which is currently starting?

**Comment by joelsmith** [comment]
@soltysh we are just hoping to be able to backport this to 4.6 and 4.5, but we can't start that process until this code lands in 4.7.  The customer is very anxious to get this fix on their cluster, so we're trying to expedite the process. Will merging this cause problems for the 1.20 bump?

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
