### PR TITLE
Stable 20160510

### PR DESCRIPTION
**Pull request by mfojtik**
Still running verify-all and some tests but it compiles and unit tests seems to work.
Output from unit tests: https://paste.fedoraproject.org/365103/62967286 (I believe the failures are fine since i'm running this on OSX and I get the same failures running tests for k8s master).

@smarterclayton needs to rebase https://github.com/kubernetes/kubernetes/pull/25033

Some other notes from this:

* https://github.com/openshift/kubernetes/commit/1aa8e0381fdf69f36f7aac949ad681f74a2ddca4 was tricky because if `int` -> `int32` conversions (I have to update manually generated v1beta3 conversions and I also generated protobuf for v1beta3 ;-)
* https://github.com/openshift/kubernetes/commit/9dfc20f827ea5da2670df4e4cfdbe8670fd21410 was tricky because of `registry.Store` changes

There were other minor edits to some picks, but I can't remember them, so I advise to check your carry/pick to make sure I did not removed/changed something that I should not.

Also I'm sorry if I changed the author of the pick (i have to amend some changes and I really don't want to reformat the patch unless somebody tell me to do it ;-)

```
Σ~/.../k8s.io/kubernetes ∎ ./hack/verify-all.sh
Running in the silent mode, run with -v if you want to see script logs.
Skipping ./hack/../hack/verify-all.sh
Verifying ./hack/../hack/verify-api-reference-docs.sh
FAILED   ./hack/../hack/verify-api-reference-docs.sh   24s
Verifying ./hack/../hack/verify-boilerplate.sh
SUCCESS  ./hack/../hack/verify-boilerplate.sh  1s
Verifying ./hack/../hack/verify-codecgen.sh
FAILED   ./hack/../hack/verify-codecgen.sh     0s
Verifying ./hack/../hack/verify-codegen.sh
SUCCESS  ./hack/../hack/verify-codegen.sh      10s
Verifying ./hack/../hack/verify-description.sh
FAILED   ./hack/../hack/verify-description.sh  3s
Verifying ./hack/../hack/verify-generated-docs.sh
SUCCESS  ./hack/../hack/verify-generated-docs.sh       62s
Verifying ./hack/../hack/verify-generated-protobuf.sh
SUCCESS  ./hack/../hack/verify-generated-protobuf.sh   30s
Verifying ./hack/../hack/verify-generated-swagger-docs.sh
SUCCESS  ./hack/../hack/verify-generated-swagger-docs.sh       14s
Verifying ./hack/../hack/verify-godep-licenses.sh
SUCCESS  ./hack/../hack/verify-godep-licenses.sh       0s
Verifying ./hack/../hack/verify-godeps.sh
SUCCESS  ./hack/../hack/verify-godeps.sh       0s
Verifying ./hack/../hack/verify-gofmt.sh
SUCCESS   ./hack/../hack/verify-gofmt.sh        5s
Verifying ./hack/../hack/verify-govet.sh
FAILED   ./hack/../hack/verify-govet.sh        31s
Verifying ./hack/../hack/verify-import-boss.sh
SUCCESS  ./hack/../hack/verify-import-boss.sh  5s
Skipping ./hack/../hack/verify-linkcheck.sh
Verifying ./hack/../hack/verify-swagger-spec.sh
FAILED   ./hack/../hack/verify-swagger-spec.sh 42s
Verifying ./hack/../hack/verify-symbols.sh
SUCCESS  ./hack/../hack/verify-symbols.sh      43s
Verifying ./hack/../hack/verify-flags-underscore.py
SUCCESS  ./hack/../hack/verify-flags-underscore.py     21s
```

### CODE REVIEW

**Comment by deads2k** [comment]
We don't care about api docs, swagger, description, or codec gen for now.  It would be best to fix the others where they are broken.

**Comment by mfojtik** [comment]
@deads2k on it

**Comment by soltysh** [comment]
I'd say we don't care about protobuf atm, either.

**Comment by mfojtik** [comment]
@soltysh we don't but serialization tests seems to care...

**Comment by soltysh** [comment]
bummer...

**Comment by mfojtik** [comment]
@pweil- @liggitt PTAL

**Comment by mfojtik** [comment]
(fixed all govet errors related to us, gofmt errors, etc.)

**Comment by liggitt** [comment]
rename `UPSTREAM: <drop>: kubelet: reading cloudinfo from cadvisor` to include upstream PR number (21373)

**Comment by liggitt** [comment]
rename `UPSTREAM: <drop>: make addIndexers safe for sharedInformer` to include upstream PR number (25671)

**Comment by liggitt** [comment]
rename `UPSTREAM: <drop>: prevent nil pointer when starting controllers before running the shared informer` to include upstream PR (25669)

**Comment by mfojtik** [comment]
@deads2k @liggitt we should merge this now, right?

**Comment by deads2k** [comment]
We've been merging these into a stable branch, so that master tracks the latest level we're working on from kube

**Comment by liggitt** [comment]
pushed to https://github.com/openshift/kubernetes/tree/stable-20160615

**Pull request closed without merging**
