### PR TITLE
OCPBUGS-31741: 4.14: UPSTREAM: 124048: Use the right feature gate when updating uncertain volumes

### PR DESCRIPTION
**Pull request by jsafrane**
This is cherry pick of https://github.com/openshift/kubernetes/pull/1919 into 4.14

@openshift/storage

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by duanwei33** [comment]
Verification passed with open PR, see verification way [here](https://issues.redhat.com/browse/OCPBUGS-30957?focusedId=24479385&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24479385)

The pods came back in ~5 mins.
```
ss-storage-test-0                                  0/1     ContainerCreating   1          12m
ss-storage-test-14                                 0/1     ContainerCreating   1          9m39s
ss-storage-test-18                                 0/1     ContainerCreating   1          13m
ss-storage-test-5                                  0/1     ContainerCreating   1          15m
ss-storage-test-0                                  1/1     Running             1          16m
ss-storage-test-14                                 1/1     Running             1          14m
ss-storage-test-11                                 1/1     Running             1          14m
```

**Comment by soltysh** [comment]
/override ci/prow/unit
known failure, will be fixed in k8s patch release

**Pull request merged**
