### PR TITLE
Bug 1908880: UPSTREAM: 97980: kubelet: revert checking sandbox deletion

### PR DESCRIPTION
**Pull request by ehashman**
We've had a regression in 1.20 where pod deletion time has significantly increased due to https://github.com/kubernetes/kubernetes/pull/92817. While we investigate the underlying cause, let's revert this to avoid test flakes.

Upstream bug: https://github.com/kubernetes/kubernetes/issues/97288
Upstream PR: https://github.com/kubernetes/kubernetes/pull/97980
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1908880

/cc @rphillips @mrunalp @kikisdeliveryservice

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Should this be attached to : https://bugzilla.redhat.com/show_bug.cgi?id=1915085 which I thought was the tracking bug?

**Comment by kikisdeliveryservice** [comment]
I dont think my approval carries any weight in this repo but LGTM.

Thanks @ehashman for getting this done so quickly :heart:

**Comment by ehashman** [comment]
> Should this be attached to : https://bugzilla.redhat.com/show_bug.cgi?id=1915085 which I thought was the tracking bug?

That one is not assigned to me, I'm new to this so I'm happy to update to whatever is the correct bug :)

**Comment by wking** [comment]
I think [rhbz#1915085][1] is a separate bug about creation-time issues, while this reversion is addressing a deletion-time issue.  Doesn't really matter though, we can measure impacts of the various symptoms after this lands.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1915085

**Comment by wking** [comment]
[FIPS][1] hit `VpcLimitExceeded`.

/test e2e-aws-fips

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/523/pull-ci-openshift-kubernetes-master-e2e-aws-fips/1349409686994030592#1:build-log.txt%3A79

**Comment by rphillips** [comment]
`VpcLimitExceeded` hit again

**Comment by kikisdeliveryservice** [comment]
`msg=Error: Request "Create IAM Members roles/storage.admin serviceAccount:ci-op-wyb9m9ft-b2c4f-mtgqb-w@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" returned error: Batch request and retried single request "Create IAM Members roles/storage.admin serviceAccount:ci-op-wyb9m9ft-b2c4f-mtgqb-w@openshift-gce-devel-ci.iam.gserviceaccount.com for \"project \\\"openshift-gce-devel-ci\\\"\"" both failed. Final error: Error applying IAM policy for project "openshift-gce-devel-ci": Error setting IAM policy for project "openshift-gce-devel-ci": googleapi: Error 400: Service account ci-op-650lws-openshift-i-wf2c9@openshift-gce-devel-ci.iam.gserviceaccount.com does not exist., badRequest`

**Comment by ehashman** [comment]
Looks like https://bugzilla.redhat.com/show_bug.cgi?id=1896218 maybe?

I think the VPCs have been fixed...

/retest

**Comment by kikisdeliveryservice** [comment]
re: e2e-aws-fips (1000 role limit), it's been reported and jobs need to be reaped but that's having issues rn. :frowning_face:

**Comment by wking** [comment]
Another [`Error setting IAM policy...`][1] CI-contention flake on GCP.

/retest

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/523/pull-ci-openshift-kubernetes-master-e2e-gcp/1349640884395708417

**Pull request merged**
