### PR TITLE
OCPBUGS-25812: Fix device uncertain errors on reboot - 4.15

### PR DESCRIPTION
**Pull request by gnufied**
fixes https://issues.redhat.com/browse/OCPBUGS-25812

### CODE REVIEW

**Comment by duanwei33** [comment]
The issue could be reproduced in 4.15.0-ec.3, and when tested with the open PR, it did not hit the issue again.
It looks good from the QE side.

**Review by soltysh — APPROVED** [review]
/approve
/label backport-risk-assessed

**Pull request merged**
