### PR TITLE
BUG 1858871: UPSTREAM: 93478: kubelet: eviction: remove unexpected output from TestGetReclaimableThreshold

### PR DESCRIPTION
**Pull request by sjenning**
@derekwaynecarr 

xref https://bugzilla.redhat.com/show_bug.cgi?id=1858871
xref https://github.com/kubernetes/kubernetes/pull/93478

### CODE REVIEW

**Comment by sjenning** [comment]
/hold
for upstream merge

**Comment by deads2k** [comment]
/override ci/prow/kubernetes-e2e

this is a unit test fix for.... some reason I'm sure sjenning has a good one

**Pull request merged**
