### PR TITLE
Bug 2099800: bump to k8s 1.24.2

### PR DESCRIPTION
**Pull request by soltysh**
Alternative to https://github.com/openshift/kubernetes/pull/1291
/assign @ravisantoshgudimetla

### CODE REVIEW

**Comment by soltysh** [comment]
/override ci/prow/verify-commits 
this never passes on k8s bumps

**Comment by ravisantoshgudimetla** [comment]
/retitle Bug 2099800: bump to k8s 1.24.2

**Comment by ravisantoshgudimetla** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregator-periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1539997775880523776

OVN upgrade job failures are related to github returning wrong values.

**Comment by ravisantoshgudimetla** [comment]
https://github.com/openshift/release/pull/29824 merged.

/retest

**Comment by soltysh** [comment]
Replaced with https://github.com/openshift/kubernetes/pull/1326

**Pull request closed without merging**
