### PR TITLE
[DO NOT MERGE] openshift picks for 1.6

### PR DESCRIPTION
**Pull request by deads2k**
@sttts @ncdc do a sanity check for me?  I used `UPSTREAM_REPO_LOCATION=/home/deads/workspaces/kube/src/k8s.io/kubernetes/ TARGET_BRANCH=picks hack/move-upstream.sh e8d67d3ea07a726c1bbd34d5c0a86872c54567de..master` to pick these.

As I recall, we generally push these instead of merging, but I don't feel strongly if you guys want to argue one way or the other.

@liggitt @smarterclayton our branches are all over the place.  Let's actually plan what we're going to do.

### CODE REVIEW

**Comment by ncdc** [comment]
@deads2k it looks like maybe you're missing `5a2ed74 UPSTREAM: <drop>: missing test file`?

**Comment by sttts** [comment]
A quick scan matches with what I get here locally. But the order is slightly different than a `git log --oneline e8d67d3ea07a726c1bbd34d5c0a86872c54567de..origin/master vendor/k8s.io/kubernetes | grep -v Merge`. And one commit was added on-top.

**Comment by ncdc** [comment]
I had an exact match for all commits except the one I listed above

**Comment by sttts** [comment]
Double checked in detail, same result as @ncdc

**Comment by deads2k** [comment]
> @deads2k it looks like maybe you're missing 5a2ed74 UPSTREAM: <drop>: missing test file?

The file added in that commit is already present in openshift/kubernetes here https://github.com/openshift/kubernetes/blob/openshift-1.6-20170501/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_apis_test.go . No idea why it wasn't in openshift's vendored copy when I needed it.

**Comment by ncdc** [comment]
Ok

**Comment by smarterclayton** [comment]
Something is weird about UPSTREAM: 40423: Support for v1/v2/autoprobe openstack cinder blockstorage - i don't see those dependencies in the repo.

**Pull request closed without merging**
