### PR TITLE
Bug 1916489: (e2e/scheduler) Ensure minimum memory limit in createBalancedPodForNodes

### PR DESCRIPTION
**Pull request by damemi**
Pulls changes from https://github.com/kubernetes/kubernetes/pull/98073
/hold 
for upstream review

### CODE REVIEW

**Comment by marun** [comment]
@damemi Failures appears to point to a problem with what is proposed in this PR?

**Comment by damemi** [comment]
Interesting failure because it's not happening in the upstream PR, but it seems like the nodeName I'm trying to set for the selector is nil.

There was also some upstream questions about how this affects other runtimes. I'm assuming openshift is based on cri-o, but I need to talk to containers folks about that because it's out of my expertise

**Review by damemi — COMMENTED** [review]
/hold cancel
/bugzilla refresh
/cc @soltysh 
this has merged upstream now, commit picked and rebased here. ready for review

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/retest

**Pull request merged**
