### PR TITLE
OCPBUGS-15726: UPSTREAM: 118879: make apiservices.apiregistration.k8s.io discoverabl…

### PR DESCRIPTION
**Pull request by ardaguclu**
Carrying https://github.com/kubernetes/kubernetes/pull/118879

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by ardaguclu** [comment]
This aws-ovn-fips job https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1629/pull-ci-openshift-kubernetes-master-e2e-aws-ovn-fips/1679760031450402816 has passed to testing stage.
/hold cancel

**Comment by ardaguclu** [comment]
unrelated;
/retest-required

**Comment by ardaguclu** [comment]
unfortunately verify is permafailing again;
/hold

**Comment by atiratree** [comment]
verify should be passing: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1646/pull-ci-openshift-kubernetes-master-verify/1683581031002673152
/test verify

**Comment by atiratree** [comment]
verify is failing because we are using a container image with old golang version (1.20.3), but kubernetes requires at least version 1.20.5: https://github.com/kubernetes/kubernetes/pull/118553

this causes the difference in go.mod which fails our `verify-vendor.sh`: 
https://github.com/kubernetes/kubernetes/pull/118553/commits/e0a2a6efdd1ed709ca0edec61faa6bb51a0ce685#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63

**Comment by ardaguclu** [comment]
@atiratree could you please tag this?. Thanks.

**Comment by atiratree** [comment]
verify should pass after https://github.com/openshift/kubernetes/pull/1645 merges
/lgtm

**Comment by ardaguclu** [comment]
it is too early for retesting but let's try once;
/test verify

**Pull request merged**
