### PR TITLE
Bug 1912563: UPSTREAM: 97206: clean up executing request on panic

### PR DESCRIPTION
**Pull request by tkashem**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
clean up executing request on panic

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

but you need to be green
/hold

holding until green.

**Comment by tkashem** [comment]
unit test `TestPriorityAndFairnessWithPanicRecoverAndTimeoutFilter` is expected to fail - needs p&f controller deadlock carry merged first - https://github.com/openshift/kubernetes/pull/503 merged first.

**Comment by tkashem** [comment]
mistakenly pushed to 4.7 branch, master is still open for 4.7, closing in favor of https://github.com/openshift/kubernetes/pull/509

/close

**Pull request closed without merging**
