### PR TITLE
OCPBUGS-25815:  Fix device uncertain errors on reboot 4.12

### PR DESCRIPTION
**Pull request by gnufied**
https://issues.redhat.com/browse/OCPBUGS-25815

### CODE REVIEW

**Comment by duanwei33** [comment]
The issue could be reproduced in both 4.12.0-0.nightly-2023-12-18-194028, and when tested with the open PR, it did not hit the issue again.
It looks good from the QE side.

**Review by soltysh — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by soltysh** [comment]
This PR has sufficient pass rate (see https://prow.ci.openshift.org/pr-history/?org=openshift&repo=kubernetes&pr=1833), it looks like changes from https://github.com/openshift/release/pull/47115 and https://github.com/openshift/release/pull/47117 broke 4.12 branch.

/override ci/prow/e2e-aws-ovn-fips
/override ci/prow/k8s-e2e-gcp-serial
/override ci/prow/e2e-aws-ovn-cgroupsv2
/override ci/prow/verify-commits
/override ci/prow/k8s-e2e-gcp-ovn
/override ci/prow/k8s-e2e-conformance-aws
/override ci/prow/e2e-gcp
/override ci/prow/e2e-agnostic-ovn-cmd
/override ci/prow/integration
/override ci/prow/unit
/override ci/prow/verify
/override ci/prow/e2e-aws-ovn-serial
/override ci/prow/e2e-gcp-ovn-upgrade
/override ci/prow/images
/override ci/prow/e2e-aws-ovn-crun

**Pull request merged**
